# PhonePe Pulse Data Analysis
Extracting PhonePe transaction data from JSON files, cleaning it, and loading into PostgreSQL for analysis.

In [1]:
# importing all the libraries I need
import pandas as pd
import json
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
import re
import plotly.express as px
import psycopg
import os
from sqlalchemy import create_engine,text

## Aggregated Transactions

In [2]:
# checking what state folders are available in the dataset


path = "D:/Movies/Guvi_2/PhonePe/phonepe-pulse/data/aggregated/transaction/country/india/state"
aggState_list = os.listdir(path)
aggState_list

['andaman-&-nicobar-islands',
 'andhra-pradesh',
 'arunachal-pradesh',
 'assam',
 'bihar',
 'chandigarh',
 'chhattisgarh',
 'dadra-&-nagar-haveli-&-daman-&-diu',
 'delhi',
 'goa',
 'gujarat',
 'haryana',
 'himachal-pradesh',
 'jammu-&-kashmir',
 'jharkhand',
 'karnataka',
 'kerala',
 'ladakh',
 'lakshadweep',
 'madhya-pradesh',
 'maharashtra',
 'manipur',
 'meghalaya',
 'mizoram',
 'nagaland',
 'odisha',
 'puducherry',
 'punjab',
 'rajasthan',
 'sikkim',
 'tamil-nadu',
 'telangana',
 'tripura',
 'uttar-pradesh',
 'uttarakhand',
 'west-bengal']

In [3]:
# looping through each state → year → quarter folder to read all JSON files
# and collecting transaction data into a dictionary, then converting to dataframe

path = "D:/Movies/Guvi_2/PhonePe/phonepe-pulse/data/aggregated/transaction/country/india/state/"

Agg_state_list=os.listdir(path)
Agg_state_list
#Agg_state_list--> to get the list of states in India



#This is to extract the data's to create a dataframe

clm={'State':[], 'Year':[],'Quater':[],'Transaction_type':[], 'Transaction_count':[], 'Transaction_amount':[]}

for i in Agg_state_list:
    p_i=path+i+"/"
    Agg_yr=os.listdir(p_i)
    for j in Agg_yr:
        p_j=p_i+j+"/"
        Agg_yr_list=os.listdir(p_j)
        for k in Agg_yr_list:
            p_k=p_j+k
            Data=open(p_k,'r')
            D=json.load(Data)
            for z in D['data']['transactionData']:
              Name=z['name']
              count=z['paymentInstruments'][0]['count']
              amount=z['paymentInstruments'][0]['amount']
              clm['Transaction_type'].append(Name)
              clm['Transaction_count'].append(count)
              clm['Transaction_amount'].append(amount)
              clm['State'].append(i)
              clm['Year'].append(j)
              clm['Quater'].append(int(k.strip('.json')))
#Succesfully created a dataframe
agg_trans=pd.DataFrame(clm)

In [4]:
# checking if the data looks correct

agg_trans.head(15)

,State,Year,Quater,Transaction_type,Transaction_count,Transaction_amount
0,andaman-&-nicobar-islands,2018,1,Recharge & bill payments,4200,1.845307e+06
1,andaman-&-nicobar-islands,2018,1,Peer-to-peer payments,1871,1.213866e+07
2,andaman-&-nicobar-islands,2018,1,Merchant payments,298,4.525072e+05
3,andaman-&-nicobar-islands,2018,1,Financial Services,33,1.060142e+04
4,andaman-&-nicobar-islands,2018,1,Others,256,1.846899e+05
5,andaman-&-nicobar-islands,2018,2,Recharge & bill payments,6735,2.320945e+06
6,andaman-&-nicobar-islands,2018,2,Peer-to-peer payments,3575,2.451193e+07
7,andaman-&-nicobar-islands,2018,2,Merchant payments,603,1.024491e+06
8,andaman-&-nicobar-islands,2018,2,Financial Services,59,1.213360e+05
9,andaman-&-nicobar-islands,2018,2,Others,368,3.598385e+05
10,andaman-&-nicobar-islands,2018,3,Recharge & bill payments,8636,4.343505e+06
11,andaman-&-nicobar-islands,2018,3,Peer-to-peer payments,6448,4.927078e+07
12,andaman-&-nicobar-islands,2018,3,Merchant payments,945,1.627360e+06
13,andaman-&-nicobar-islands,2018,3,Financial Services,42,1.481491e+03
14,andaman-&-nicobar-islands,2018,3,Others,194,3.143434e+05

In [5]:
# state names are in lowercase like "andaman-&-nicobar-islands", capitalizing them


agg_trans['State'] = agg_trans['State'].str.capitalize()

##caps_agg.head(15)
list(agg_trans['State'].unique())

['Andaman-&-nicobar-islands',
 'Andhra-pradesh',
 'Arunachal-pradesh',
 'Assam',
 'Bihar',
 'Chandigarh',
 'Chhattisgarh',
 'Dadra-&-nagar-haveli-&-daman-&-diu',
 'Delhi',
 'Goa',
 'Gujarat',
 'Haryana',
 'Himachal-pradesh',
 'Jammu-&-kashmir',
 'Jharkhand',
 'Karnataka',
 'Kerala',
 'Ladakh',
 'Lakshadweep',
 'Madhya-pradesh',
 'Maharashtra',
 'Manipur',
 'Meghalaya',
 'Mizoram',
 'Nagaland',
 'Odisha',
 'Puducherry',
 'Punjab',
 'Rajasthan',
 'Sikkim',
 'Tamil-nadu',
 'Telangana',
 'Tripura',
 'Uttar-pradesh',
 'Uttarakhand',
 'West-bengal']

In [6]:
# replacing hyphens with spaces and capitalizing each word to make state names readable


def modify(s):
    s = s.replace('-', ' ')
    return ' '.join(word.capitalize() for word in s.split())

agg_trans['State'] = agg_trans['State'].apply(modify)

In [7]:
# some state names don't match the geojson map, so renaming them to match
# without this the choropleth map won't show those states


update_cat = {
    "Andaman & Nicobar Islands": "Andaman & Nicobar",
    "Dadra & Nagar Haveli & Daman & Diu": "Dadra and Nagar Haveli and Daman and Diu"
}

agg_trans['State'] = agg_trans['State'].replace(update_cat)

# this was done bcz the map was not loading

In [8]:
# converting Year to integer


agg_trans['Year'] = pd.to_datetime(agg_trans['Year']).dt.year

agg_trans['Year'].info()
agg_trans['Year']

<class 'pandas.Series'>
RangeIndex: 5034 entries, 0 to 5033
Series name: Year
Non-Null Count  Dtype
--------------  -----
5034 non-null   int32
dtypes: int32(1)
memory usage: 19.8 KB

0       2018
1       2018
2       2018
3       2018
4       2018
        ...
5029    2024
5030    2024
5031    2024
5032    2024
5033    2024
Name: Year, Length: 5034, dtype: int32

In [9]:
# checking data types and if there are any null values

agg_trans.info()

<class 'pandas.DataFrame'>
RangeIndex: 5034 entries, 0 to 5033
Data columns (total 6 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   State               5034 non-null   str
 1   Year                5034 non-null   int32
 2   Quater              5034 non-null   int64
 3   Transaction_type    5034 non-null   str
 4   Transaction_count   5034 non-null   int64
 5   Transaction_amount  5034 non-null   float64
dtypes: float64(1), int32(1), int64(2), str(2)
memory usage: 351.2 KB

In [10]:
agg_trans['Transaction_type'].unique()

<ArrowStringArray>
['Recharge & bill payments',    'Peer-to-peer payments',
        'Merchant payments',       'Financial Services',
                   'Others']
Length: 5, dtype: str

In [11]:
agg_trans['Transaction_count'].unique()

array([    4200,     1871,      298, ..., 76043195,  2352084,   421806],
      dtype=int64)

In [12]:
agg_trans['Transaction_amount'].unique()

array([1.84530747e+06, 1.21386553e+07, 4.52507169e+05, ...,
       5.75340565e+10, 8.47296537e+08, 5.05364108e+08])

In [13]:
# pd.set_option('display.max_rows', None)

In [14]:
agg_trans.head(5)

,State,Year,Quater,Transaction_type,Transaction_count,Transaction_amount
0,Andaman & Nicobar,2018,1,Recharge & bill payments,4200,1.845307e+06
1,Andaman & Nicobar,2018,1,Peer-to-peer payments,1871,1.213866e+07
2,Andaman & Nicobar,2018,1,Merchant payments,298,4.525072e+05
3,Andaman & Nicobar,2018,1,Financial Services,33,1.060142e+04
4,Andaman & Nicobar,2018,1,Others,256,1.846899e+05

In [15]:
agg_trans.isnull().sum()

State                 0
Year                  0
Quater                0
Transaction_type      0
Transaction_count     0
Transaction_amount    0
dtype: int64

In [16]:
# agg_trans['Transaction_amount'] = agg_trans['Transaction_amount'].astype(int)
# agg_trans['Transaction_amount']

In [17]:
df_grp = agg_trans.groupby('State')['Transaction_count'].sum().reset_index()
# df_grp['YoY_Growth_%'] = df_grp.groupby('State')['Transaction_count'].pct_change()*100

df_grp.head()

               State  Transaction_count
0  Andaman & Nicobar           39706951
1     Andhra Pradesh        18918696723
2  Arunachal Pradesh          160223357
3              Assam         2262440836
4              Bihar        10941026824

In [18]:
# grouping by state to get total transaction count — will use this for the map

agg_trans.groupby('State')['Transaction_amount'].sum().sort_values(ascending=False)

State
Telangana                                   4.165596e+13
Karnataka                                   4.067872e+13
Maharashtra                                 4.037420e+13
Andhra Pradesh                              3.466908e+13
Uttar Pradesh                               2.688521e+13
Rajasthan                                   2.634324e+13
Madhya Pradesh                              1.912528e+13
Bihar                                       1.790135e+13
West Bengal                                 1.558416e+13
Odisha                                      1.226398e+13
Tamil Nadu                                  1.193622e+13
Delhi                                       1.163752e+13
Gujarat                                     1.019291e+13
Haryana                                     9.645037e+12
Jharkhand                                   5.906646e+12
Chhattisgarh                                4.890472e+12
Assam                                       3.460792e+12
Kerala                                      3.076269e+12
Punjab                                      2.983078e+12
Uttarakhand                                 1.916489e+12
Jammu & Kashmir                             1.184683e+12
Himachal Pradesh                            6.875374e+11
Goa                                         5.110212e+11
Chandigarh                                  2.929066e+11
Arunachal Pradesh                           2.744350e+11
Puducherry                                  2.373171e+11
Dadra and Nagar Haveli and Daman and Diu    2.017199e+11
Tripura                                     2.005834e+11
Manipur                                     1.862656e+11
Meghalaya                                   1.625439e+11
Nagaland                                    1.303586e+11
Sikkim                                      1.189454e+11
Ladakh                                      8.899462e+10
Andaman & Nicobar                           7.066745e+10
Mizoram                                     4.610210e+10
Lakshadweep                                 1.609321e+09
Name: Transaction_amount, dtype: float64

In [19]:
agg_trans.groupby('Transaction_type')['Transaction_count'].sum()

Transaction_type
Financial Services             154208943
Merchant payments           130238755487
Others                         262050188
Peer-to-peer payments        85032446653
Recharge & bill payments     19596755603
Name: Transaction_count, dtype: int64

In [20]:
# how many transactions per payment type (P2P, Recharge, Merchant, etc.)


one = agg_trans.groupby('Transaction_type')['Transaction_count'].sum()
one = one.sort_values(ascending=False)
one

Transaction_type
Merchant payments           130238755487
Peer-to-peer payments        85032446653
Recharge & bill payments     19596755603
Others                         262050188
Financial Services             154208943
Name: Transaction_count, dtype: int64

In [21]:
df_grp.sort_values( by="Transaction_count",ascending=False).head(10)

             State  Transaction_count
20     Maharashtra        31985208732
15       Karnataka        30970946279
31       Telangana        26174684592
1   Andhra Pradesh        18918696723
33   Uttar Pradesh        18523603727
28       Rajasthan        17108537898
19  Madhya Pradesh        14072176059
4            Bihar        10941026824
35     West Bengal         9191499687
25          Odisha         8918527452

In [22]:
# Quarter wise transaction count

quatr = agg_trans.groupby(['Year', 'Quater'])['Transaction_count'].sum().reset_index()
quatr

    Year  Quater  Transaction_count
0   2018       1          134425599
1   2018       2          187365440
2   2018       3          341299764
3   2018       4          417111607
4   2019       1          708992981
5   2019       2          815380896
6   2019       3         1095009675
7   2019       4         1460443663
8   2020       1         1623038046
9   2020       2         1448608890
10  2020       3         2033051183
11  2020       4         2869276622
12  2021       1         3457585463
13  2021       2         3941370465
14  2021       3         5263737270
15  2021       4         6625736022
16  2022       1         7593179960
17  2022       2         9131576368
18  2022       3        10545339960
19  2022       4        12031197446
20  2023       1        13090517630
21  2023       2        15109557411
22  2023       3        17041723189
23  2023       4        19015256457
24  2024       1        21237053999
25  2024       2        24026109645
26  2024       3        25821015384
27  2024       4        28219255839

In [23]:
agg_trans['State'].unique()

<ArrowStringArray>
[                       'Andaman & Nicobar',
                           'Andhra Pradesh',
                        'Arunachal Pradesh',
                                    'Assam',
                                    'Bihar',
                               'Chandigarh',
                             'Chhattisgarh',
 'Dadra and Nagar Haveli and Daman and Diu',
                                    'Delhi',
                                      'Goa',
                                  'Gujarat',
                                  'Haryana',
                         'Himachal Pradesh',
                          'Jammu & Kashmir',
                                'Jharkhand',
                                'Karnataka',
                                   'Kerala',
                                   'Ladakh',
                              'Lakshadweep',
                           'Madhya Pradesh',
                              'Maharashtra',
                                  'Manipur',
                                'Meghalaya',
                                  'Mizoram',
                                 'Nagaland',
                                   'Odisha',
                               'Puducherry',
                                   'Punjab',
                                'Rajasthan',
                                   'Sikkim',
                               'Tamil Nadu',
                                'Telangana',
                                  'Tripura',
                            'Uttar Pradesh',
                              'Uttarakhand',
                              'West Bengal']
Length: 36, dtype: str

In [24]:
#Southern states show consistently higher transaction volumes, indicating mature digital adoption,
#while North‑Eastern states show lower volumes but steady growth, 
# suggesting emerging markets for targeted campaigns.

In [25]:

# plotting India map to show which states have more transactions

df = df_grp

fig = px.choropleth(
    df,
    geojson="https://gist.githubusercontent.com/jbrobst/56c13bbbf9d97d187fea01ca62ea5112/raw/e388c4cae20aa53cb5090210a42ebb9b765c0a36/india_states.geojson",
    featureidkey='properties.ST_NM',
    locations='State',
    color='Transaction_count',
    color_continuous_scale='Reds'
)

fig.update_geos(fitbounds="locations", visible=False)

fig.show()

## Aggregated Insurance
Insurance data starts from Q2 2020 because PhonePe launched insurance in Q2 2020.

In [26]:
# extracting insurance data — same approach as transactions

path = "D:/Movies/Guvi_2/PhonePe/phonepe-pulse/data/aggregated/insurance/country/india/state/"


Agg_ins_list=os.listdir(path)
Agg_ins_list
#Agg_state_list--> to get the list of states in India

#<------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------>#

#This is to extract the data's to create a dataframe

clm={'State':[], 'Year':[],'Quater':[],'Transaction_type':[], 'Transaction_count':[], 'Transaction_amount':[]}

for i in Agg_ins_list:
    p_i=path+i+"/"
    Agg_yr=os.listdir(p_i)
    for j in Agg_yr:
        p_j=p_i+j+"/"
        Agg_yr_list=os.listdir(p_j)
        for k in Agg_yr_list:
            p_k=p_j+k
            Data=open(p_k,'r')
            D=json.load(Data)
            for z in D['data']['transactionData']:
              Name=z['name']
              count=z['paymentInstruments'][0]['count']
              amount=z['paymentInstruments'][0]['amount']
              clm['Transaction_type'].append(Name)
              clm['Transaction_count'].append(count)
              clm['Transaction_amount'].append(amount)
              clm['State'].append(i)
              clm['Year'].append(j)
              clm['Quater'].append(int(k.strip('.json')))
#Succesfully created a dataframe
agg_ins=pd.DataFrame(clm)

In [27]:
# cleaning state names same as before

def modify(s):
    s = s.replace('-', ' ')
    return ' '.join(word.capitalize() for word in s.split())

agg_ins['State'] = agg_ins['State'].apply(modify)

update_cat = {
    "Andaman & Nicobar Islands": "Andaman & Nicobar",
    "Dadra & Nagar Haveli & Daman & Diu": "Dadra and Nagar Haveli and Daman and Diu"
}

agg_ins['State'] = agg_ins['State'].replace(update_cat)

In [28]:
# converting year to integer

agg_ins['Year'] = pd.to_datetime(agg_ins['Year']).dt.year
agg_ins['Year'].info()
agg_ins['Year']

<class 'pandas.Series'>
RangeIndex: 682 entries, 0 to 681
Series name: Year
Non-Null Count  Dtype
--------------  -----
682 non-null    int32
dtypes: int32(1)
memory usage: 2.8 KB

0      2020
1      2020
2      2020
3      2021
4      2021
       ...
677    2023
678    2024
679    2024
680    2024
681    2024
Name: Year, Length: 682, dtype: int32

In [29]:
agg_ins.info()

<class 'pandas.DataFrame'>
RangeIndex: 682 entries, 0 to 681
Data columns (total 6 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   State               682 non-null    str
 1   Year                682 non-null    int32
 2   Quater              682 non-null    int64
 3   Transaction_type    682 non-null    str
 4   Transaction_count   682 non-null    int64
 5   Transaction_amount  682 non-null    float64
dtypes: float64(1), int32(1), int64(2), str(2)
memory usage: 42.2 KB

In [30]:
agg_ins.head()

,State,Year,Quater,Transaction_type,Transaction_count,Transaction_amount
0,Andaman & Nicobar,2020,2,Insurance,6,1360.0
1,Andaman & Nicobar,2020,3,Insurance,41,15380.0
2,Andaman & Nicobar,2020,4,Insurance,124,157975.0
3,Andaman & Nicobar,2021,1,Insurance,225,244266.0
4,Andaman & Nicobar,2021,2,Insurance,137,181504.0

In [31]:
# States with better digital development have higher insurance usage,
# while many other regions still have low insurance coverage.
df_grp_ins = agg_ins.groupby('State')[['Transaction_count', 'Transaction_amount']].sum().reset_index()
df_grp_ins.head(10)

,State,Transaction_count,Transaction_amount
0,Andaman & Nicobar,12997,19386792.0
1,Andhra Pradesh,697769,812222985.0
2,Arunachal Pradesh,10214,23420755.0
3,Assam,262818,411831038.0
4,Bihar,536592,671056815.0
5,Chandigarh,22079,33285885.0
6,Chhattisgarh,189517,274344886.0
7,Dadra and Nagar Haveli and Daman and Diu,13792,17992414.0
8,Delhi,652514,815365172.0
9,Goa,59872,83730005.0

In [32]:
# converting transaction amount to integer for cleaner numbers

agg_ins['Transaction_amount'] = agg_ins['Transaction_amount'].astype(int)

In [33]:
# Shows growth.


ins_trend = (agg_ins.groupby(['Year', 'Quater'])['Transaction_amount'].sum().reset_index())
ins_trend

    Year  Quater  Transaction_amount
0   2020       2            33732166
1   2020       3            89495076
2   2020       4           170979933
3   2021       1           206295702
4   2021       2           295065422
5   2021       3           342388829
6   2021       4           655420085
7   2022       1           887413773
8   2022       2           857012844
9   2022       3          1054672890
10  2022       4          1439743924
11  2023       1          1408776725
12  2023       2          1347352521
13  2023       3          1445209417
14  2023       4          1855267395
15  2024       1          1931922471
16  2024       2          1759607284
17  2024       3          1941265641
18  2024       4          2293956286

In [34]:
# India map showing insurance transactions by state

df = df_grp_ins

fig = px.choropleth(
    df,
    geojson="https://gist.githubusercontent.com/jbrobst/56c13bbbf9d97d187fea01ca62ea5112/raw/e388c4cae20aa53cb5090210a42ebb9b765c0a36/india_states.geojson",
    featureidkey='properties.ST_NM',
    locations='State',
    color='Transaction_count',
    color_continuous_scale='Rainbow'
)

fig.update_geos(fitbounds="locations", visible=False)
fig.update_layout(title_text='Insurance Transactions by State in India')

fig.show()

## Aggregated Users

In [35]:
# extracting user data — registered users, app opens, device brands

path = "D:/Movies/Guvi_2/PhonePe/phonepe-pulse/data/aggregated/user/country/india/state/"
agg_user_list = os.listdir(path)

# <-------------------------------------------------------------------->
# Columns for agg_user table

clm = {
    'State': [],
    'Year': [],
    'Quarter': [],
    'Registered_users': [],
    'App_opens': [],
    'Brand': [],
    'User_count': [],
    'User_percentage': []
}

for i in agg_user_list:               
    p_i = path + i + "/"
    user_yr = os.listdir(p_i)

    for j in user_yr:                   
        p_j = p_i + j + "/"
        user_qtr = os.listdir(p_j)

        for k in user_qtr:                
            p_k = p_j + k

            with open(p_k, 'r') as Data:
                D = json.load(Data)

                # 🔹 Aggregated user data
                aggregated = D['data'].get('aggregated', {})
                reg_users = aggregated.get('registeredUsers')
                app_opens = aggregated.get('appOpens')

                # 🔹 Device-wise data
                users = D['data'].get('usersByDevice')
                if users is None:
                    continue

                for z in users:
                    clm['State'].append(i)
                    clm['Year'].append(j)
                    clm['Quarter'].append(int(k.strip('.json')))
                    clm['Registered_users'].append(reg_users)
                    clm['App_opens'].append(app_opens)
                    clm['Brand'].append(z['brand'])
                    clm['User_count'].append(z['count'])
                    clm['User_percentage'].append(z['percentage'])

agg_user = pd.DataFrame(clm)

In [36]:
agg_user.head(5)

,State,Year,Quarter,Registered_users,App_opens,Brand,User_count,User_percentage
0,andaman-&-nicobar-islands,2018,1,6740,0,Xiaomi,1665,0.247033
1,andaman-&-nicobar-islands,2018,1,6740,0,Samsung,1445,0.214392
2,andaman-&-nicobar-islands,2018,1,6740,0,Vivo,982,0.145697
3,andaman-&-nicobar-islands,2018,1,6740,0,Oppo,501,0.074332
4,andaman-&-nicobar-islands,2018,1,6740,0,OnePlus,332,0.049258

In [37]:
# cleaning state names

def modify(s):
    s = s.replace('-', ' ')
    return ' '.join(word.capitalize() for word in s.split())

agg_user['State'] = agg_user['State'].apply(modify)

update_cat = {
    "Andaman & Nicobar Islands": "Andaman & Nicobar",
    "Dadra & Nagar Haveli & Daman & Diu": "Dadra and Nagar Haveli and Daman and Diu"
}

agg_user['State'] = agg_user['State'].replace(update_cat)

In [38]:
agg_user.info()

<class 'pandas.DataFrame'>
RangeIndex: 6732 entries, 0 to 6731
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   State             6732 non-null   str
 1   Year              6732 non-null   str
 2   Quarter           6732 non-null   int64
 3   Registered_users  6732 non-null   int64
 4   App_opens         6732 non-null   int64
 5   Brand             6732 non-null   str
 6   User_count        6732 non-null   int64
 7   User_percentage   6732 non-null   float64
dtypes: float64(1), int64(4), str(3)
memory usage: 553.2 KB

In [39]:
agg_user['Year'] = pd.to_datetime(agg_user['Year']).dt.year

agg_user['Year'].info()
agg_user['Year']

<class 'pandas.Series'>
RangeIndex: 6732 entries, 0 to 6731
Series name: Year
Non-Null Count  Dtype
--------------  -----
6732 non-null   int32
dtypes: int32(1)
memory usage: 26.4 KB

0       2018
1       2018
2       2018
3       2018
4       2018
        ...
6727    2022
6728    2022
6729    2022
6730    2022
6731    2022
Name: Year, Length: 6732, dtype: int32

In [40]:
# which states have the most registered users
most_users = agg_user.groupby('State')['User_count'].sum().reset_index()
most_users.sort_values(by='User_count', ascending=False)

                                       State  User_count
20                               Maharashtra   452075011
33                             Uttar Pradesh   355969633
15                                 Karnataka   291372780
1                             Andhra Pradesh   225414835
28                                 Rajasthan   215645588
31                                 Telangana   211907753
35                               West Bengal   206129775
30                                Tamil Nadu   193665028
10                                   Gujarat   180731308
19                            Madhya Pradesh   180662446
4                                      Bihar   167266170
8                                      Delhi   133679039
11                                   Haryana   121872882
25                                    Odisha   114580607
16                                    Kerala    76662576
27                                    Punjab    66429452
14                                 Jharkhand    64541996
6                               Chhattisgarh    54136914
3                                      Assam    39481411
34                               Uttarakhand    34161100
12                          Himachal Pradesh    19411836
13                           Jammu & Kashmir    14122428
9                                        Goa     6844584
5                                 Chandigarh     5335570
32                                   Tripura     5299920
26                                Puducherry     4052989
7   Dadra and Nagar Haveli and Daman and Diu     3896519
21                                   Manipur     3479129
2                          Arunachal Pradesh     2805570
24                                  Nagaland     2218657
22                                 Meghalaya     2155644
29                                    Sikkim     1870915
23                                   Mizoram      929959
17                                    Ladakh      840584
0                          Andaman & Nicobar      623446
18                               Lakshadweep       51138

In [41]:
# user count trend over time
usr_trnd = agg_user.groupby(['Year','Quarter'])['User_count'].sum().reset_index()
usr_trnd

    Year  Quarter  User_count
0   2018        1    46877653
1   2018        2    63648009
2   2018        3    80010589
3   2018        4   102261621
4   2019        1   123432188
5   2019        2   141807654
6   2019        3   159293319
7   2019        4   178278417
8   2020        1   197574459
9   2020        2   218995596
10  2020        3   241168896
11  2020        4   264270434
12  2021        1   284984511
13  2021        2   305257101
14  2021        3   328353856
15  2021        4   351160262
16  2022        1   372950627

In [42]:

# df = df_grp_agg_user

# fig = px.choropleth(
#     df,
#     geojson="https://gist.githubusercontent.com/jbrobst/56c13bbbf9d97d187fea01ca62ea5112/raw/e388c4cae20aa53cb5090210a42ebb9b765c0a36/india_states.geojson",
#     featureidkey='properties.ST_NM',
#     locations='State',
#     color='User_count',
#     color_continuous_scale='Oranges'
# )

# fig.update_geos(fitbounds="locations", visible=False)
# fig.update_layout(title_text='Agg Users by State in India')

# fig.show()

## Map (District Level) Transactions

In [43]:
path = "D:/Movies/Guvi_2/PhonePe/phonepe-pulse/data/map/transaction/hover/country/india/state/"


map_tran_list = os.listdir(path)
map_tran_list

#<------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------>#

#This is to extract the data's to create a dataframe

clm={'State':[], 'Year':[],'Quater':[],'Transaction_type':[], 'Transaction_count':[], 'Transaction_amount':[]}

for i in map_tran_list:
    p_i=path+i+"/"
    map_yr=os.listdir(p_i)
    for j in map_yr:
        p_j=p_i+j+"/"
        map_yr_list=os.listdir(p_j)
        for k in map_yr_list:
            p_k=p_j+k
            Data=open(p_k,'r')
            D=json.load(Data)
            for z in D['data']['hoverDataList']:
              Name=z['name']
              count=z['metric'][0]['count']
              amount=z['metric'][0]['amount']
              clm['Transaction_type'].append(Name)
              clm['Transaction_count'].append(count)
              clm['Transaction_amount'].append(amount)
              clm['State'].append(i)
              clm['Year'].append(j)
              clm['Quater'].append(int(k.strip('.json')))
#Succesfully created a dataframe
map_trans=pd.DataFrame(clm)

In [44]:
map_trans.head()

,State,Year,Quater,Transaction_type,Transaction_count,Transaction_amount
0,andaman-&-nicobar-islands,2018,1,north and middle andaman district,442,9.316631e+05
1,andaman-&-nicobar-islands,2018,1,south andaman district,5688,1.256025e+07
2,andaman-&-nicobar-islands,2018,1,nicobars district,528,1.139849e+06
3,andaman-&-nicobar-islands,2018,2,north and middle andaman district,825,1.317863e+06
4,andaman-&-nicobar-islands,2018,2,south andaman district,9395,2.394824e+07

In [45]:
def modify(s):
    s = s.replace('-', ' ')
    return ' '.join(word.capitalize() for word in s.split())

map_trans['State'] = map_trans['State'].apply(modify)
map_trans['Transaction_type'] = map_trans['Transaction_type'].apply(modify)

update_cat = {
    "Andaman & Nicobar Islands": "Andaman & Nicobar",
    "Dadra & Nagar Haveli & Daman & Diu": "Dadra and Nagar Haveli and Daman and Diu"
}

map_trans['State'] = map_trans['State'].replace(update_cat)

In [46]:
map_trans.info()

<class 'pandas.DataFrame'>
RangeIndex: 20604 entries, 0 to 20603
Data columns (total 6 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   State               20604 non-null  str
 1   Year                20604 non-null  str
 2   Quater              20604 non-null  int64
 3   Transaction_type    20604 non-null  str
 4   Transaction_count   20604 non-null  int64
 5   Transaction_amount  20604 non-null  float64
dtypes: float64(1), int64(2), str(3)
memory usage: 1.6 MB

In [47]:
map_trans['Year'] = pd.to_datetime(map_trans['Year']).dt.year

map_trans['Year'].info()
map_trans['Year']

<class 'pandas.Series'>
RangeIndex: 20604 entries, 0 to 20603
Series name: Year
Non-Null Count  Dtype
--------------  -----
20604 non-null  int32
dtypes: int32(1)
memory usage: 80.6 KB

0        2018
1        2018
2        2018
3        2018
4        2018
         ...
20599    2024
20600    2024
20601    2024
20602    2024
20603    2024
Name: Year, Length: 20604, dtype: int32

In [48]:
df_grp_map_trans= map_trans.groupby('State')['Transaction_count'].sum().reset_index()
df_grp_map_trans.info()

<class 'pandas.DataFrame'>
RangeIndex: 36 entries, 0 to 35
Data columns (total 2 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   State              36 non-null     str
 1   Transaction_count  36 non-null     int64
dtypes: int64(1), str(1)
memory usage: 1.1 KB

In [49]:
# India map — district level transactions by state


df = df_grp_map_trans

fig = px.choropleth(
    df,
    geojson="https://gist.githubusercontent.com/jbrobst/56c13bbbf9d97d187fea01ca62ea5112/raw/e388c4cae20aa53cb5090210a42ebb9b765c0a36/india_states.geojson",
    featureidkey='properties.ST_NM',
    locations='State',
    color='Transaction_count',
    color_continuous_scale='Burg'
)

fig.update_geos(fitbounds="locations", visible=False)
fig.update_layout(title_text='Insurance Transactions by State in India')

fig.show()

## Map (District Level) Insurance

In [50]:
path = "D:/Movies/Guvi_2/PhonePe/phonepe-pulse/data/map/insurance/hover/country/india/state/"

map_ins_list=os.listdir(path)
map_ins_list
#Agg_state_list--> to get the list of states in India

#<------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------>#

#This is to extract the data's to create a dataframe

clm={'State':[], 'Year':[],'Quater':[],'District':[], 'Transaction_count':[]}

for i in map_ins_list:
    p_i=path+i+"/"
    map_yr=os.listdir(p_i)
    for j in map_yr:
        p_j=p_i+j+"/"
        map_yr_list=os.listdir(p_j)
        for k in map_yr_list:
            p_k=p_j+k
            Data=open(p_k,'r')
            D=json.load(Data)
            for z in D['data']['hoverDataList']:
              Name=z['name']
              count=z['metric'][0]['count']
              clm['District'].append(Name)
              clm['Transaction_count'].append(count)
              clm['State'].append(i)
              clm['Year'].append(j)
              clm['Quater'].append(int(k.strip('.json')))
#Succesfully created a dataframe
map_ins=pd.DataFrame(clm)

In [51]:
map_ins.head()

,State,Year,Quater,District,Transaction_count
0,andaman-&-nicobar-islands,2020,2,south andaman district,3
1,andaman-&-nicobar-islands,2020,2,nicobars district,3
2,andaman-&-nicobar-islands,2020,3,north and middle andaman district,1
3,andaman-&-nicobar-islands,2020,3,south andaman district,35
4,andaman-&-nicobar-islands,2020,3,nicobars district,5

In [52]:
def modify(s):
    s = s.replace('-', ' ')
    return ' '.join(word.capitalize() for word in s.split())

map_ins['State'] = map_ins['State'].apply(modify)
map_ins['District'] = map_ins['District'].apply(modify)

update_cat = {
    "Andaman & Nicobar Islands": "Andaman & Nicobar",
    "Dadra & Nagar Haveli & Daman & Diu": "Dadra and Nagar Haveli and Daman and Diu"
}

map_ins['State'] = map_ins['State'].replace(update_cat)

In [53]:
map_trans.info()

<class 'pandas.DataFrame'>
RangeIndex: 20604 entries, 0 to 20603
Data columns (total 6 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   State               20604 non-null  str
 1   Year                20604 non-null  int32
 2   Quater              20604 non-null  int64
 3   Transaction_type    20604 non-null  str
 4   Transaction_count   20604 non-null  int64
 5   Transaction_amount  20604 non-null  float64
dtypes: float64(1), int32(1), int64(2), str(2)
memory usage: 1.4 MB

In [54]:
df_grp_map_ins = map_ins.groupby('State')['Transaction_count'].sum().reset_index()
df_grp_map_ins.info()

<class 'pandas.DataFrame'>
RangeIndex: 36 entries, 0 to 35
Data columns (total 2 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   State              36 non-null     str
 1   Transaction_count  36 non-null     int64
dtypes: int64(1), str(1)
memory usage: 1.1 KB

In [55]:

# India map — district level insurance by state

df = df_grp_map_ins

fig = px.choropleth(
    df,
    geojson="https://gist.githubusercontent.com/jbrobst/56c13bbbf9d97d187fea01ca62ea5112/raw/e388c4cae20aa53cb5090210a42ebb9b765c0a36/india_states.geojson",
    featureidkey='properties.ST_NM',
    locations='State',
    color='Transaction_count',
    color_continuous_scale='Aggrnyl'
)

fig.update_geos(fitbounds="locations", visible=False)
fig.update_layout(title_text='Map Insurance Transactions by State in India')

fig.show()

## Map (District Level) Users

In [56]:
# extracting district level user data
path = "D:/Movies/Guvi_2/PhonePe/phonepe-pulse/data/map/user/hover/country/india/state/"

map_user_list = os.listdir(path)
map_user_list



clm = {
    'State': [],
    'Year': [],
    'Quarter': [],
    'District': [],
    'Registered_users': [],
    'App_opens': []
}

for i in map_user_list:                
    p_i = path + i + "/"
    user_yr = os.listdir(p_i)
    
    for j in user_yr:                  
        p_j = p_i + j + "/"
        user_yr_list = os.listdir(p_j)
        
        for k in user_yr_list:         
            p_k = p_j + k
            
            with open(p_k, 'r') as Data:
                D = json.load(Data)

                # SAFE ACCESS
                hover_data = D['data'].get('hoverData')

                # Skip if data is missing
                if hover_data is None:
                    continue

                for district, metrics in hover_data.items():
                    users = metrics['registeredUsers']
                    opens = metrics['appOpens']

                    clm['District'].append(district)
                    clm['Registered_users'].append(users)
                    clm['App_opens'].append(opens)
                    clm['State'].append(i)
                    clm['Year'].append(j)
                    clm['Quarter'].append(int(k.strip('.json')))

map_user_list = pd.DataFrame(clm)

map_user_list.head()

,State,Year,Quarter,District,Registered_users,App_opens
0,andaman-&-nicobar-islands,2018,1,north and middle andaman district,632,0
1,andaman-&-nicobar-islands,2018,1,south andaman district,5846,0
2,andaman-&-nicobar-islands,2018,1,nicobars district,262,0
3,andaman-&-nicobar-islands,2018,2,north and middle andaman district,911,0
4,andaman-&-nicobar-islands,2018,2,south andaman district,8143,0

In [57]:
def modify(s):
    s = s.replace('-', ' ')
    return ' '.join(word.capitalize() for word in s.split())

map_user_list['State'] = map_user_list['State'].apply(modify)
map_user_list['District'] = map_user_list['District'].apply(modify)


update_cat = {
    "Andaman & Nicobar Islands": "Andaman & Nicobar",
    "Dadra & Nagar Haveli & Daman & Diu": "Dadra and Nagar Haveli and Daman and Diu"
}

map_user_list['State'] = map_user_list['State'].replace(update_cat)

In [58]:
map_user_list.info()

<class 'pandas.DataFrame'>
RangeIndex: 20608 entries, 0 to 20607
Data columns (total 6 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   State             20608 non-null  str
 1   Year              20608 non-null  str
 2   Quarter           20608 non-null  int64
 3   District          20608 non-null  str
 4   Registered_users  20608 non-null  int64
 5   App_opens         20608 non-null  int64
dtypes: int64(3), str(3)
memory usage: 1.6 MB

In [59]:
map_user_list['Year'] = pd.to_datetime(map_user_list['Year']).dt.year

map_user_list['Year'].info()
map_user_list['Year']

<class 'pandas.Series'>
RangeIndex: 20608 entries, 0 to 20607
Series name: Year
Non-Null Count  Dtype
--------------  -----
20608 non-null  int32
dtypes: int32(1)
memory usage: 80.6 KB

0        2018
1        2018
2        2018
3        2018
4        2018
         ...
20603    2024
20604    2024
20605    2024
20606    2024
20607    2024
Name: Year, Length: 20608, dtype: int32

In [60]:
df_grp_map_user= map_user_list.groupby('State')['Registered_users'].sum().reset_index()
df_grp_map_user.info()

<class 'pandas.DataFrame'>
RangeIndex: 36 entries, 0 to 35
Data columns (total 2 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   State             36 non-null     str
 1   Registered_users  36 non-null     int64
dtypes: int64(1), str(1)
memory usage: 1.1 KB

In [61]:

# India map — registered users by state

df = df_grp_map_user

fig = px.choropleth(
    df,
    geojson="https://gist.githubusercontent.com/jbrobst/56c13bbbf9d97d187fea01ca62ea5112/raw/e388c4cae20aa53cb5090210a42ebb9b765c0a36/india_states.geojson",
    featureidkey='properties.ST_NM',
    locations='State',
    color='Registered_users',
    color_continuous_scale='Burg'
)

fig.update_geos(fitbounds="locations", visible=False)
fig.update_layout(title_text='Insurance Transactions by State in India')

fig.show()

## Top Transactions

In [62]:
# extracting top transaction data by state/district/pincode

path = "D:/Movies/Guvi_2/PhonePe/phonepe-pulse/data/top/transaction/country/india/state/"

top_tran_list = os.listdir(path)
top_tran_list

#<------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------>#

#This is to extract the data's to create a dataframe
clm = {
    'State': [],
    'Year': [],
    'Quarter': [],
    'District': [],
    'Transaction_count': [],
    'Transaction_amount': []
}

for i in map_tran_list:                
    p_i = path + i + "/"
    map_yr = os.listdir(p_i)
    for j in map_yr:                    
        p_j = p_i + j + "/"
        map_yr_list = os.listdir(p_j)
        for k in map_yr_list:           
            p_k = p_j + k
            with open(p_k, 'r') as Data:
                D = json.load(Data)
                for z in D['data']['districts']:
                    district = z['entityName']
                    count = z['metric']['count']
                    amount = z['metric']['amount']
                    clm['District'].append(district)
                    clm['Transaction_count'].append(count)
                    clm['Transaction_amount'].append(amount)
                    clm['State'].append(i)
                    clm['Year'].append(j)
                    clm['Quarter'].append(int(k.strip('.json')))
top_trans=pd.DataFrame(clm)

In [63]:
top_trans.head()

,State,Year,Quarter,District,Transaction_count,Transaction_amount
0,andaman-&-nicobar-islands,2018,1,south andaman,5688,1.256025e+07
1,andaman-&-nicobar-islands,2018,1,nicobars,528,1.139849e+06
2,andaman-&-nicobar-islands,2018,1,north and middle andaman,442,9.316631e+05
3,andaman-&-nicobar-islands,2018,2,south andaman,9395,2.394824e+07
4,andaman-&-nicobar-islands,2018,2,nicobars,1120,3.072437e+06

In [64]:

def modify(s):
    s = s.replace('-', ' ')
    return ' '.join(word.capitalize() for word in s.split())

top_trans['State'] = top_trans['State'].apply(modify)
top_trans['District'] = top_trans['District'].apply(modify)


update_cat = {
    "Andaman & Nicobar Islands": "Andaman & Nicobar",
    "Dadra & Nagar Haveli & Daman & Diu": "Dadra and Nagar Haveli and Daman and Diu"
}

top_trans['State'] = top_trans['State'].replace(update_cat)

In [65]:
top_trans.info()

<class 'pandas.DataFrame'>
RangeIndex: 8296 entries, 0 to 8295
Data columns (total 6 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   State               8296 non-null   str
 1   Year                8296 non-null   str
 2   Quarter             8296 non-null   int64
 3   District            8296 non-null   str
 4   Transaction_count   8296 non-null   int64
 5   Transaction_amount  8296 non-null   float64
dtypes: float64(1), int64(2), str(3)
memory usage: 570.9 KB

In [66]:
top_trans['Year'] = pd.to_datetime(top_trans['Year']).dt.year

top_trans['Year'].info()
top_trans['Year']

<class 'pandas.Series'>
RangeIndex: 8296 entries, 0 to 8295
Series name: Year
Non-Null Count  Dtype
--------------  -----
8296 non-null   int32
dtypes: int32(1)
memory usage: 32.5 KB

0       2018
1       2018
2       2018
3       2018
4       2018
        ...
8291    2024
8292    2024
8293    2024
8294    2024
8295    2024
Name: Year, Length: 8296, dtype: int32

In [67]:
df_grp_top_trans = top_trans.groupby('State')['Transaction_count'].sum().reset_index()
df_grp_top_trans.info()

<class 'pandas.DataFrame'>
RangeIndex: 36 entries, 0 to 35
Data columns (total 2 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   State              36 non-null     str
 1   Transaction_count  36 non-null     int64
dtypes: int64(1), str(1)
memory usage: 1.1 KB

In [68]:
# India map — top states by transactions

df = df_grp_top_trans

fig = px.choropleth(
    df,
    geojson="https://gist.githubusercontent.com/jbrobst/56c13bbbf9d97d187fea01ca62ea5112/raw/e388c4cae20aa53cb5090210a42ebb9b765c0a36/india_states.geojson",
    featureidkey='properties.ST_NM',
    locations='State',
    color='Transaction_count',
    color_continuous_scale='Teal'
)

fig.update_geos(fitbounds="locations", visible=False)
fig.update_layout(title_text='Insurance Transactions by State in India')

fig.show()

## Top Users

In [69]:
# extracting top user data


path = "D:/Movies/Guvi_2/PhonePe/phonepe-pulse/data/top/user/country/india/state/"


top_user_list = os.listdir(path)
top_user_list



clm = {
    'State': [],
    'Year': [],
    'Quarter': [],
    'District': [],
    'Registered_users': []
}

for i in top_user_list:                 # state
    p_i = path + i + "/"
    user_yr = os.listdir(p_i)

    for j in user_yr:                   # year
        p_j = p_i + j + "/"
        user_yr_list = os.listdir(p_j)

        for k in user_yr_list:          # quarter json
            p_k = p_j + k

            with open(p_k, 'r') as Data:
                D = json.load(Data)

                # SAFE ACCESS
                districts = D['data'].get('districts')

                # Skip if data is missing
                if districts is None:
                    continue

                for z in districts:
                    district = z['name']
                    users = z['registeredUsers']

                    clm['District'].append(district)
                    clm['Registered_users'].append(users)
                    clm['State'].append(i)
                    clm['Year'].append(j)
                    clm['Quarter'].append(int(k.strip('.json')))

# Successfully created dataframe
top_user_list = pd.DataFrame(clm)

top_user_list.head()

,State,Year,Quarter,District,Registered_users
0,andaman-&-nicobar-islands,2018,1,south andaman,5846
1,andaman-&-nicobar-islands,2018,1,north and middle andaman,632
2,andaman-&-nicobar-islands,2018,1,nicobars,262
3,andaman-&-nicobar-islands,2018,2,south andaman,8143
4,andaman-&-nicobar-islands,2018,2,north and middle andaman,911

In [70]:

def modify(s):
    s = s.replace('-', ' ')
    return ' '.join(word.capitalize() for word in s.split())

top_user_list['State'] = top_user_list['State'].apply(modify)
top_user_list['District'] = top_user_list['District'].apply(modify)

update_cat = {
    "Andaman & Nicobar Islands": "Andaman & Nicobar",
    "Dadra & Nagar Haveli & Daman & Diu": "Dadra and Nagar Haveli and Daman and Diu"
}

top_user_list['State'] = top_user_list['State'].replace(update_cat)

In [71]:
top_user_list.info()
top_user_list.head()

<class 'pandas.DataFrame'>
RangeIndex: 8296 entries, 0 to 8295
Data columns (total 5 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   State             8296 non-null   str
 1   Year              8296 non-null   str
 2   Quarter           8296 non-null   int64
 3   District          8296 non-null   str
 4   Registered_users  8296 non-null   int64
dtypes: int64(2), str(3)
memory usage: 507.0 KB

,State,Year,Quarter,District,Registered_users
0,Andaman & Nicobar,2018,1,South Andaman,5846
1,Andaman & Nicobar,2018,1,North And Middle Andaman,632
2,Andaman & Nicobar,2018,1,Nicobars,262
3,Andaman & Nicobar,2018,2,South Andaman,8143
4,Andaman & Nicobar,2018,2,North And Middle Andaman,911

In [72]:
top_user_list['Year'] = pd.to_datetime(top_user_list['Year']).dt.year

top_user_list['Year'].info()
top_user_list['Year']

<class 'pandas.Series'>
RangeIndex: 8296 entries, 0 to 8295
Series name: Year
Non-Null Count  Dtype
--------------  -----
8296 non-null   int32
dtypes: int32(1)
memory usage: 32.5 KB

0       2018
1       2018
2       2018
3       2018
4       2018
        ...
8291    2024
8292    2024
8293    2024
8294    2024
8295    2024
Name: Year, Length: 8296, dtype: int32

In [73]:


# df = df_grp_top_user

# fig = px.choropleth(
#     df,
#     geojson="https://gist.githubusercontent.com/jbrobst/56c13bbbf9d97d187fea01ca62ea5112/raw/e388c4cae20aa53cb5090210a42ebb9b765c0a36/india_states.geojson",
#     featureidkey='properties.ST_NM',
#     locations='State',
#     color='Registered_users',
#     color_continuous_scale='Turbo'
# )

# fig.update_geos(fitbounds="locations", visible=False)
# fig.update_layout(title_text='Agg Users by State in India')

# fig.show()

## Top Insurance

In [74]:
# extracting top insurance data

path = "D:/Movies/Guvi_2/PhonePe/phonepe-pulse/data/top/insurance/country/india/state/"

top_ins_list=os.listdir(path)
top_ins_list


clm = {
    'State': [],
    'Year': [],
    'Quarter': [],
    'District': [],
    'Transaction_count': [],
    'Transaction_amount': []
}

for i in top_ins_list:                
    p_i = path + i + "/"
    map_yr = os.listdir(p_i)
    for j in map_yr:                    
        p_j = p_i + j + "/"
        map_yr_list = os.listdir(p_j)
        for k in map_yr_list:           
            p_k = p_j + k
            with open(p_k, 'r') as Data:
                D = json.load(Data)
                for z in D['data']['districts']:
                    district = z['entityName']
                    count = z['metric']['count']
                    amount = z['metric']['amount']
                    clm['District'].append(district)
                    clm['Transaction_count'].append(count)
                    clm['Transaction_amount'].append(amount)
                    clm['State'].append(i)
                    clm['Year'].append(j)
                    clm['Quarter'].append(int(k.strip('.json')))
top_ins=pd.DataFrame(clm)

In [75]:
top_ins.head()

,State,Year,Quarter,District,Transaction_count,Transaction_amount
0,andaman-&-nicobar-islands,2020,2,nicobars,3,565.0
1,andaman-&-nicobar-islands,2020,2,south andaman,3,795.0
2,andaman-&-nicobar-islands,2020,3,south andaman,35,13651.0
3,andaman-&-nicobar-islands,2020,3,nicobars,5,1448.0
4,andaman-&-nicobar-islands,2020,3,north and middle andaman,1,281.0

In [76]:

def modify(s):
    s = s.replace('-', ' ')
    return ' '.join(word.capitalize() for word in s.split())

top_ins['State'] = top_ins['State'].apply(modify)
top_ins['District'] = top_ins['District'].apply(modify)

update_cat = {
    "Andaman & Nicobar Islands": "Andaman & Nicobar",
    "Dadra & Nagar Haveli & Daman & Diu": "Dadra and Nagar Haveli and Daman and Diu"
}

top_ins['State'] = top_ins['State'].replace(update_cat)

In [77]:
top_ins.info()

<class 'pandas.DataFrame'>
RangeIndex: 5608 entries, 0 to 5607
Data columns (total 6 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   State               5608 non-null   str
 1   Year                5608 non-null   str
 2   Quarter             5608 non-null   int64
 3   District            5608 non-null   str
 4   Transaction_count   5608 non-null   int64
 5   Transaction_amount  5608 non-null   float64
dtypes: float64(1), int64(2), str(3)
memory usage: 386.4 KB

In [78]:
top_ins['Year'] = pd.to_datetime(top_ins['Year']).dt.year

top_ins['Year'].info()
top_ins['Year']

<class 'pandas.Series'>
RangeIndex: 5608 entries, 0 to 5607
Series name: Year
Non-Null Count  Dtype
--------------  -----
5608 non-null   int32
dtypes: int32(1)
memory usage: 22.0 KB

0       2020
1       2020
2       2020
3       2020
4       2020
        ...
5603    2024
5604    2024
5605    2024
5606    2024
5607    2024
Name: Year, Length: 5608, dtype: int32

In [79]:
df_grp_top_ins = top_ins.groupby('State')['Transaction_count'].sum().reset_index()
df_grp_top_ins.info()

<class 'pandas.DataFrame'>
RangeIndex: 36 entries, 0 to 35
Data columns (total 2 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   State              36 non-null     str
 1   Transaction_count  36 non-null     int64
dtypes: int64(1), str(1)
memory usage: 1.1 KB

In [80]:
# India map — top insurance by state

df = df_grp_top_ins

fig = px.choropleth(
    df,
    geojson="https://gist.githubusercontent.com/jbrobst/56c13bbbf9d97d187fea01ca62ea5112/raw/e388c4cae20aa53cb5090210a42ebb9b765c0a36/india_states.geojson",
    featureidkey='properties.ST_NM',
    locations='State',
    color='Transaction_count',
    color_continuous_scale='Oranges'
)

fig.update_geos(fitbounds="locations", visible=False)
fig.update_layout(title_text='Map Insurance Transactions by State in India')

fig.show()

## Database Connection & Loading into PostgreSQL

In [81]:
# installing database packages
!pip install sqlalchemy psycopg pandas;
!pip install psycopg2-binary

Requirement already satisfied: sqlalchemy in c:\users\farooque\anaconda3\lib\site-packages (2.0.46)
Requirement already satisfied: psycopg in c:\users\farooque\anaconda3\lib\site-packages (3.2.9)
Requirement already satisfied: pandas in c:\users\farooque\anaconda3\lib\site-packages (3.0.1)
Requirement already satisfied: greenlet>=1 in c:\users\farooque\anaconda3\lib\site-packages (from sqlalchemy) (3.0.1)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\farooque\anaconda3\lib\site-packages (from sqlalchemy) (4.15.0)
Requirement already satisfied: tzdata in c:\users\farooque\anaconda3\lib\site-packages (from psycopg) (2023.3)
Requirement already satisfied: numpy>=1.26.0 in c:\users\farooque\anaconda3\lib\site-packages (from pandas) (1.26.4)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\farooque\anaconda3\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in c:\users\farooque\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Requirement already satisfied: psycopg2-binary in c:\users\farooque\anaconda3\lib\site-packages (2.9.10)

In [82]:
# connecting to postgresql — password stored in environment variable
engine = create_engine(
    os.environ.get("PHONEPE_DB_URL", "postgresql+psycopg2://postgres:YOUR_PASSWORD@127.0.0.1:5432/phonepe_data")
)

In [83]:
try:
    with engine.connect() as conn:
        print(" SQL Alchemy connected to PostgreSQL")
except Exception as e:
    print(" Connection failed:", e)

 SQL Alchemy connected to PostgreSQL

In [84]:
# loading all 9 dataframes into postgresql tables
# AGG tables 

agg_trans.to_sql(
    name="agg_trans",
    con=engine,
    if_exists="append",
    index=False
)


agg_ins.to_sql(
    name="agg_ins",
    con=engine,
    if_exists="append",
    index=False
)

agg_user.to_sql(
    name="agg_user",
    con=engine,
    if_exists="append",
    index=False
)


# MAP tables

map_trans.to_sql(
    name="map_trans",
    con=engine,
    if_exists="append",
    index=False
)

map_ins.to_sql(
    name="map_ins",
    con=engine,
    if_exists="append",
    index=False
)

map_user_list.to_sql(
    name="map_user_list",
    con=engine,
    if_exists="append",
    index=False
)

#TOP TABLE 

top_trans.to_sql(
    name="top_trans",
    con=engine,
    if_exists="append",
    index=False
)


top_ins.to_sql(
    name="top_ins",
    con=engine,
    if_exists="append",
    index=False
)

top_user_list.to_sql(
    name="top_user_list",
    con=engine,
    if_exists="append",
    index=False
)

-1

In [85]:
# # DELETE TABLES

# tables = [
    
#     "agg_trans",
#     "agg_ins",
#     "agg_user",
#     "map_trans",
#     "map_ins",
#     "map_user_list",
#     "top_trans",
#     "top_ins",
#     "top_user_list"
# ]
#     
# with engine.connect() as conn:
#     for table in tables:
#         conn.execute(text(f"DROP TABLE IF EXISTS {table} CASCADE;"))
#     conn.commit()
#     print("table deleted successfully")

## SQL Business Case Studies
Answering business questions using SQL and comparing with pandas results.

In [86]:
# checking all tables are loaded in the database
query = """
SELECT table_name
FROM information_schema.tables
WHERE table_schema = 'public';
"""

df = pd.read_sql_query(query, engine)
print(df)

      table_name
0      agg_trans
1        agg_ins
2       agg_user
3      map_trans
4        map_ins
5  map_user_list
6      top_trans
7        top_ins
8  top_user_list

In [87]:
# checking column names and types
query = """
SELECT column_name, data_type
FROM information_schema.columns
WHERE table_schema = 'public'
  AND table_name = 'map_trans';
"""

df = pd.read_sql_query(query, engine)
df

          column_name         data_type
0               State              text
1                Year           integer
2              Quater            bigint
3    Transaction_type              text
4   Transaction_count            bigint
5  Transaction_amount  double precision

In [88]:
# Scenario - 1

# 1. Decoding Transaction Dynamics on PhonePe

# PhonePe, a leading digital payments platform, 
# has recently identified significant variations in transaction behavior across states, quarters, 
# and payment categories.
# While some regions and transaction types demonstrate consistent growth,
# thers show stagnation or decline.
# The leadership team seeks a deeper understanding of these patterns to drive targeted business strategies.

In [89]:
# States with higher digital adoption contribute significantly to overall transaction volume.
# first doing the analysis with pandas then checking with SQL to make sure results match

state_trn = agg_trans.groupby('State')[['Transaction_count']] \
                     .sum().reset_index()
state_trn.sort_values(by='Transaction_count', ascending=False).head(10)

             State  Transaction_count
20     Maharashtra        31985208732
15       Karnataka        30970946279
31       Telangana        26174684592
1   Andhra Pradesh        18918696723
33   Uttar Pradesh        18523603727
28       Rajasthan        17108537898
19  Madhya Pradesh        14072176059
4            Bihar        10941026824
35     West Bengal         9191499687
25          Odisha         8918527452

In [90]:
# same query in SQL to cross-check the pandas result

query = """
                SELECT 
                "State",
                SUM("Transaction_count") AS total_transaction_count
                FROM agg_trans
                GROUP BY "State"
                ORDER BY total_transaction_count DESC
                LIMIT 10;
                
                """

top_states = pd.read_sql_query(query, engine)
top_states

            State  total_transaction_count
0     Maharashtra             1.919113e+11
1       Karnataka             1.858257e+11
2       Telangana             1.570481e+11
3  Andhra Pradesh             1.135122e+11
4   Uttar Pradesh             1.111416e+11
5       Rajasthan             1.026512e+11
6  Madhya Pradesh             8.443306e+10
7           Bihar             6.564616e+10
8     West Bengal             5.514900e+10
9          Odisha             5.351116e+10

In [91]:
# Map Fig
# showing the results on India map


df = df_grp # from agg_transactions

fig = px.choropleth(
    df,
    geojson="https://gist.githubusercontent.com/jbrobst/56c13bbbf9d97d187fea01ca62ea5112/raw/e388c4cae20aa53cb5090210a42ebb9b765c0a36/india_states.geojson",
    featureidkey='properties.ST_NM',
    locations='State',
    color='Transaction_count',
    color_continuous_scale='Reds'
)

fig.update_geos(fitbounds="locations", visible=False)

fig.show()

In [92]:
agg_ins.info()

<class 'pandas.DataFrame'>
RangeIndex: 682 entries, 0 to 681
Data columns (total 6 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   State               682 non-null    str
 1   Year                682 non-null    int32
 2   Quater              682 non-null    int64
 3   Transaction_type    682 non-null    str
 4   Transaction_count   682 non-null    int64
 5   Transaction_amount  682 non-null    int32
dtypes: int32(2), int64(2), str(2)
memory usage: 39.6 KB

In [93]:
# Scenario 
# 3. Insurance Penetration and Growth Potential Analysis
#Scenario
#PhonePe has ventured into the insurance domain, providing users with options to secure various policies. 
# With increasing transactions in this segment, the company seeks to analyze its growth trajectory and identify untapped opportunities for insurance adoption at the state level. 
# This data will help prioritize regions for marketing efforts and partnerships with insurers.

In [94]:
# which states have the most insurance transactions

high_ins_state = agg_ins.groupby('State')['Transaction_count'].sum().reset_index()
high_ins_state.sort_values(by='Transaction_count', ascending=False).head(10)

             State  Transaction_count
15       Karnataka            1957404
20     Maharashtra            1815539
30      Tamil Nadu            1215269
33   Uttar Pradesh            1139153
31       Telangana             894342
35     West Bengal             839715
16          Kerala             824235
1   Andhra Pradesh             697769
8            Delhi             652514
28       Rajasthan             639684

In [95]:
# I performed state‑wise aggregation of insurance transaction counts using Pandas and 
# validated the same logic using SQL to identify states with the highest insurance adoption

In [96]:
# SQL

query = """
                SELECT 
                "State",
                SUM("Transaction_count") AS total_transaction_count
                FROM agg_ins
                GROUP BY "State"
                ORDER BY total_transaction_count DESC
                LIMIT 10;
                
                """

top_states = pd.read_sql_query(query, engine)
top_states

            State  total_transaction_count
0       Karnataka               11744424.0
1     Maharashtra               10893234.0
2      Tamil Nadu                7291614.0
3   Uttar Pradesh                6834918.0
4       Telangana                5366052.0
5     West Bengal                5038290.0
6          Kerala                4945410.0
7  Andhra Pradesh                4186614.0
8           Delhi                3915084.0
9       Rajasthan                3838104.0

In [97]:
# checking user data before analysis
agg_user.head()

,State,Year,Quarter,Registered_users,App_opens,Brand,User_count,User_percentage
0,Andaman & Nicobar,2018,1,6740,0,Xiaomi,1665,0.247033
1,Andaman & Nicobar,2018,1,6740,0,Samsung,1445,0.214392
2,Andaman & Nicobar,2018,1,6740,0,Vivo,982,0.145697
3,Andaman & Nicobar,2018,1,6740,0,Oppo,501,0.074332
4,Andaman & Nicobar,2018,1,6740,0,OnePlus,332,0.049258

In [98]:
# 5. User Engagement and Growth Strategy
# PhonePe seeks to enhance its market position by analyzing user engagement across different states and districts. With a significant number of registered users and app opens, 
# understanding user behavior can provide valuable insights for strategic decision-making and growth opportunities.

In [99]:
# Analyzing state-wise registered users to identify regions with the highest user base.
num_reg_user = agg_user.groupby('State')['Registered_users'].sum().reset_index()
num_reg_user.sort_values(by='Registered_users', ascending=False)

                                       State  Registered_users
20                               Maharashtra        4972825121
33                             Uttar Pradesh        3915665963
15                                 Karnataka        3205100580
1                             Andhra Pradesh        2479563185
28                                 Rajasthan        2372101468
31                                 Telangana        2330985283
35                               West Bengal        2267427525
30                                Tamil Nadu        2130315308
10                                   Gujarat        1988044388
19                            Madhya Pradesh        1987286906
4                                      Bihar        1839927870
8                                      Delhi        1470469429
11                                   Haryana        1340601702
25                                    Odisha        1260386677
16                                    Kerala         843288336
27                                    Punjab         730723972
14                                 Jharkhand         709961956
6                               Chhattisgarh         595506054
3                                      Assam         434295521
34                               Uttarakhand         375772100
12                          Himachal Pradesh         213530196
13                           Jammu & Kashmir         155346708
9                                        Goa          75290424
5                                 Chandigarh          58691270
32                                   Tripura          58299120
26                                Puducherry          44582879
7   Dadra and Nagar Haveli and Daman and Diu          42861709
21                                   Manipur          38270419
2                          Arunachal Pradesh          30861270
24                                  Nagaland          24405227
22                                 Meghalaya          23712084
29                                    Sikkim          20580065
23                                   Mizoram          10229549
17                                    Ladakh           9246424
0                          Andaman & Nicobar           6857906
18                               Lakshadweep            562518

In [100]:
# Analyzing state-wise registered users to identify regions with the highest user base.

# SQL

query = """
                SELECT 
                "State",
                SUM("Registered_users") AS total_reg_user
                FROM agg_user
                GROUP BY "State"
                ORDER BY total_reg_user DESC
                LIMIT 10;
                
                """

reg_usr = pd.read_sql_query(query, engine)
reg_usr

            State  total_reg_user
0     Maharashtra    2.983695e+10
1   Uttar Pradesh    2.349400e+10
2       Karnataka    1.923060e+10
3  Andhra Pradesh    1.487738e+10
4       Rajasthan    1.423261e+10
5       Telangana    1.398591e+10
6     West Bengal    1.360457e+10
7      Tamil Nadu    1.278189e+10
8         Gujarat    1.192827e+10
9  Madhya Pradesh    1.192372e+10

In [101]:
# Analyzing brand popularity based on app opens.

st_op_ap = agg_user.groupby('State')['App_opens'].sum().reset_index()
st_op_ap.sort_values(by='App_opens', ascending=False)

                                       State     App_opens
20                               Maharashtra  130902916881
15                                 Karnataka  121505737078
1                             Andhra Pradesh  102445420418
28                                 Rajasthan  100093362160
31                                 Telangana   92639879035
33                             Uttar Pradesh   72178186487
19                            Madhya Pradesh   71524173336
30                                Tamil Nadu   39578469623
25                                    Odisha   38536362216
4                                      Bihar   37722567135
35                               West Bengal   34139202185
10                                   Gujarat   32833356204
11                                   Haryana   27171892935
8                                      Delhi   24283682984
6                               Chhattisgarh   19289157437
14                                 Jharkhand   18582919839
16                                    Kerala   10436263288
3                                      Assam   10221542419
27                                    Punjab    9517363669
34                               Uttarakhand    7395508890
12                          Himachal Pradesh    3776042127
13                           Jammu & Kashmir    2701659246
9                                        Goa    1470646166
2                          Arunachal Pradesh    1172571323
32                                   Tripura     946642158
21                                   Manipur     741405544
7   Dadra and Nagar Haveli and Daman and Diu     720764308
5                                 Chandigarh     701611790
22                                 Meghalaya     684106731
26                                Puducherry     682759682
24                                  Nagaland     677649346
29                                    Sikkim     467816008
23                                   Mizoram     353093059
17                                    Ladakh     317989606
0                          Andaman & Nicobar     161003601
18                               Lakshadweep       4524025

In [102]:
# SQL

query = """
                SELECT 
                "State",
                SUM("App_opens") AS open_app_count
                FROM agg_user
                GROUP BY "State"
                ORDER BY open_app_count DESC;
                
                
                """

st_open_app = pd.read_sql_query(query, engine)
st_open_app

                                       State  open_app_count
0                                Maharashtra    7.854175e+11
1                                  Karnataka    7.290344e+11
2                             Andhra Pradesh    6.146725e+11
3                                  Rajasthan    6.005602e+11
4                                  Telangana    5.558393e+11
5                              Uttar Pradesh    4.330691e+11
6                             Madhya Pradesh    4.291450e+11
7                                 Tamil Nadu    2.374708e+11
8                                     Odisha    2.312182e+11
9                                      Bihar    2.263354e+11
10                               West Bengal    2.048352e+11
11                                   Gujarat    1.970001e+11
12                                   Haryana    1.630314e+11
13                                     Delhi    1.457021e+11
14                              Chhattisgarh    1.157349e+11
15                                 Jharkhand    1.114975e+11
16                                    Kerala    6.261758e+10
17                                     Assam    6.132925e+10
18                                    Punjab    5.710418e+10
19                               Uttarakhand    4.437305e+10
20                          Himachal Pradesh    2.265625e+10
21                           Jammu & Kashmir    1.620996e+10
22                                       Goa    8.823877e+09
23                         Arunachal Pradesh    7.035428e+09
24                                   Tripura    5.679853e+09
25                                   Manipur    4.448433e+09
26  Dadra and Nagar Haveli and Daman and Diu    4.324586e+09
27                                Chandigarh    4.209671e+09
28                                 Meghalaya    4.104640e+09
29                                Puducherry    4.096558e+09
30                                  Nagaland    4.065896e+09
31                                    Sikkim    2.806896e+09
32                                   Mizoram    2.118558e+09
33                                    Ladakh    1.907938e+09
34                         Andaman & Nicobar    9.660216e+08
35                               Lakshadweep    2.714415e+07

In [103]:
# States with low engagement ratios despite high registrations represent growth opportunities 
# where PhonePe can improve user activity through targeted strategies.

In [104]:
# SQL

query = """
        SELECT
            "State",
            SUM("Registered_users") AS total_registered_users,
            SUM("App_opens") AS total_app_opens,
            SUM("App_opens") * 1.0 / SUM("Registered_users") AS engagement_ratio
        FROM agg_user
        GROUP BY "State"
        ORDER BY engagement_ratio ASC
        LIMIT 10;
        """

low_engagement_states = pd.read_sql_query(query, engine)
low_engagement_states

,State,total_registered_users,total_app_opens,engagement_ratio
0,Lakshadweep,3.375108e+06,2.714415e+07,8.042454
1,Chandigarh,3.521476e+08,4.209671e+09,11.954279
2,Kerala,5.059730e+09,6.261758e+10,12.375676
3,Punjab,4.384344e+09,5.710418e+10,13.024567
4,West Bengal,1.360457e+10,2.048352e+11,15.056359
5,Puducherry,2.674973e+08,4.096558e+09,15.314392
6,Tripura,3.497947e+08,5.679853e+09,16.237675
7,Delhi,8.822817e+09,1.457021e+11,16.514239
8,Gujarat,1.192827e+10,1.970001e+11,16.515404
9,Dadra and Nagar Haveli and Daman and Diu,2.571703e+08,4.324586e+09,16.816042

In [105]:
#6. Insurance Engagement Analysis
#Scenario
# PhonePe aims to analyze insurance transactions across various states and districts to understand the uptake of insurance services among users. 
# This analysis will provide insights into user behavior, market demand, and potential areas for growth in insurance offerings.

In [106]:
agg_ins.head(2)

,State,Year,Quater,Transaction_type,Transaction_count,Transaction_amount
0,Andaman & Nicobar,2020,2,Insurance,6,1360
1,Andaman & Nicobar,2020,3,Insurance,41,15380

In [107]:
# state with highest insurance counts

# SQL

query = """
                SELECT 
                "State",
                SUM("Transaction_count") AS insurance_counts
                FROM agg_ins
                GROUP BY "State"
                ORDER BY insurance_counts DESC;
                
                
                """

st_high_ins = pd.read_sql_query(query, engine)
st_high_ins

                                       State  insurance_counts
0                                  Karnataka        11744424.0
1                                Maharashtra        10893234.0
2                                 Tamil Nadu         7291614.0
3                              Uttar Pradesh         6834918.0
4                                  Telangana         5366052.0
5                                West Bengal         5038290.0
6                                     Kerala         4945410.0
7                             Andhra Pradesh         4186614.0
8                                      Delhi         3915084.0
9                                  Rajasthan         3838104.0
10                                   Haryana         3442428.0
11                                   Gujarat         3375570.0
12                                     Bihar         3219552.0
13                            Madhya Pradesh         2923080.0
14                                    Odisha         1912614.0
15                                     Assam         1576908.0
16                                 Jharkhand         1564962.0
17                              Chhattisgarh         1137102.0
18                                    Punjab         1080066.0
19                               Uttarakhand          746244.0
20                           Jammu & Kashmir          470250.0
21                          Himachal Pradesh          370740.0
22                                       Goa          359232.0
23                                Puducherry          167640.0
24                                   Tripura          151152.0
25                                Chandigarh          132474.0
26  Dadra and Nagar Haveli and Daman and Diu           82752.0
27                         Andaman & Nicobar           77982.0
28                                 Meghalaya           62766.0
29                         Arunachal Pradesh           61284.0
30                                    Sikkim           29376.0
31                                  Nagaland           28470.0
32                                   Manipur           22386.0
33                                   Mizoram           22344.0
34                                    Ladakh           20028.0
35                               Lakshadweep            2976.0

In [108]:
# insurance adoption changed over time?

# SQL

query = """
                SELECT 
                "Year","Quater",
                SUM("Transaction_count") AS Num_insurance_adoption
                FROM agg_ins
                GROUP BY "Year","Quater"
                ORDER BY Num_insurance_adoption DESC;
                
                
                """

ins_adop = pd.read_sql_query(query, engine)
ins_adop

    Year  Quater  num_insurance_adoption
0   2024       4               8852574.0
1   2024       1               7642566.0
2   2024       3               7281774.0
3   2023       4               6954234.0
4   2024       2               6630150.0
5   2022       4               6212058.0
6   2023       3               6061152.0
7   2023       1               5538882.0
8   2023       2               5362854.0
9   2022       3               4838724.0
10  2022       2               3784464.0
11  2022       1               3705450.0
12  2021       4               3157914.0
13  2021       3               2249160.0
14  2021       2               2183928.0
15  2020       3               2125704.0
16  2021       1               1908690.0
17  2020       4               1491756.0
18  2020       2               1112088.0

In [109]:
# Districts with low insurance adoption (growth potential)

query = """
        SELECT
            "State",
            "District",
            SUM("Transaction_count") AS Low_insurance_adoption
        FROM map_ins
        GROUP BY "State", "District"
        ORDER BY Low_insurance_adoption ASC
        LIMIT 10;
        """

low_ins_adop = pd.read_sql_query(query, engine)
low_ins_adop

       State                           District  low_insurance_adoption
0    Mizoram                 Hnahthial District                    12.0
1   Nagaland                  Shamator District                    12.0
2   Nagaland                  Tseminyu District                    18.0
3    Mizoram                  Khawzawl District                    18.0
4    Manipur                  Pherzawl District                    18.0
5   Nagaland                    Noklak District                    30.0
6    Mizoram                   Saitual District                    54.0
7  Meghalaya  Eastern West Khasi Hills District                    72.0
8    Manipur                   Kamjong District                    90.0
9    Mizoram                     Siaha District                   126.0

In [110]:
# 8. User Registration Analysis

# Scenario

# PhonePe aims to conduct an analysis of user registration data to identify the top states, 
# districts, and pin codes from which the most users registered during a specific year-quarter combination.
#  This analysis will provide insights into user engagement patterns and highlight potential growth areas.

In [111]:
top_user_list.head()

,State,Year,Quarter,District,Registered_users
0,Andaman & Nicobar,2018,1,South Andaman,5846
1,Andaman & Nicobar,2018,1,North And Middle Andaman,632
2,Andaman & Nicobar,2018,1,Nicobars,262
3,Andaman & Nicobar,2018,2,South Andaman,8143
4,Andaman & Nicobar,2018,2,North And Middle Andaman,911

In [112]:
top_user_list.info()

<class 'pandas.DataFrame'>
RangeIndex: 8296 entries, 0 to 8295
Data columns (total 5 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   State             8296 non-null   str
 1   Year              8296 non-null   int32
 2   Quarter           8296 non-null   int64
 3   District          8296 non-null   str
 4   Registered_users  8296 non-null   int64
dtypes: int32(1), int64(2), str(2)
memory usage: 442.2 KB

In [113]:
# highest registered users by state
# SQL

query = """
                SELECT 
                "State",
                SUM("Registered_users") AS reg_user
                FROM top_user_list
                GROUP BY "State"
                ORDER BY reg_user DESC
                LIMIT 10;
                
                """

high_reg_users = pd.read_sql_query(query, engine)
high_reg_users

            State      reg_user
0     Maharashtra  4.572892e+09
1       Karnataka  3.077892e+09
2  Andhra Pradesh  2.768131e+09
3   Uttar Pradesh  2.309569e+09
4       Telangana  2.284570e+09
5     West Bengal  2.233466e+09
6       Rajasthan  1.973033e+09
7         Gujarat  1.962021e+09
8           Delhi  1.842016e+09
9      Tamil Nadu  1.838866e+09

In [114]:
#districts with highest registered users

query = """
                SELECT
                "State",
                "District",
                SUM("Registered_users") AS reg_user
                FROM top_user_list
                GROUP BY "State", "District"
                ORDER BY reg_user DESC
                LIMIT 10;
                
                """

high_reg_districts = pd.read_sql_query(query, engine)
high_reg_districts

         State                    District      reg_user
0    Karnataka             Bengaluru Urban  1.821979e+09
1  Maharashtra                        Pune  1.196077e+09
2  Maharashtra                       Thane  7.350099e+08
3    Rajasthan                      Jaipur  7.184357e+08
4  Maharashtra             Mumbai Suburban  7.140773e+08
5    Telangana                   Hyderabad  6.109459e+08
6    Telangana                  Rangareddy  5.415666e+08
7      Gujarat                   Ahmadabad  4.906039e+08
8      Gujarat                       Surat  4.648170e+08
9  West Bengal  North Twenty Four Parganas  4.643778e+08

In [115]:
map_user_list.head()

,State,Year,Quarter,District,Registered_users,App_opens
0,Andaman & Nicobar,2018,1,North And Middle Andaman District,632,0
1,Andaman & Nicobar,2018,1,South Andaman District,5846,0
2,Andaman & Nicobar,2018,1,Nicobars District,262,0
3,Andaman & Nicobar,2018,2,North And Middle Andaman District,911,0
4,Andaman & Nicobar,2018,2,South Andaman District,8143,0

In [116]:
# Top districts by registered users 

query = """
        SELECT
            "State",
            "District",
            SUM("Registered_users") AS total_registered_users
        FROM map_user_list
        WHERE "Year" = '2018'
          AND "Quarter" = 1
        GROUP BY "State", "District"
        ORDER BY total_registered_users DESC
        LIMIT 10;
        """

top_districts_yq = pd.read_sql_query(query, engine)
top_districts_yq

            State                     District  total_registered_users
0       Karnataka     Bengaluru Urban District              11534208.0
1     Maharashtra                Pune District               7269858.0
2       Rajasthan              Jaipur District               5404638.0
3     Maharashtra     Mumbai Suburban District               4315800.0
4       Telangana           Hyderabad District               3931050.0
5       Telangana          Rangareddy District               3811050.0
6     Maharashtra               Thane District               3791184.0
7         Gujarat           Ahmadabad District               3436866.0
8       Telangana  Medchal Malkajgiri District               3296574.0
9  Andhra Pradesh       Visakhapatnam District               2983122.0

In [117]:
####    in 2020 there is no data available in 1st quarter hence there is no data 
agg_ins[(agg_ins["Year"] == 2020) & (agg_ins["Quater"] == 1)]

Empty DataFrame
Columns: [State, Year, Quater, Transaction_type, Transaction_count, Transaction_amount]
Index: []

In [118]:
agg_ins[(agg_ins["Year"] == 2020) & (agg_ins["Quater"] == 2)]

,State,Year,Quater,Transaction_type,Transaction_count,Transaction_amount
0,Andaman & Nicobar,2020,2,Insurance,6,1360
19,Andhra Pradesh,2020,2,Insurance,22104,3982391
38,Arunachal Pradesh,2020,2,Insurance,65,14329
57,Assam,2020,2,Insurance,978,210034
76,Bihar,2020,2,Insurance,2816,595621
95,Chandigarh,2020,2,Insurance,149,29537
114,Chhattisgarh,2020,2,Insurance,1346,279005
133,Dadra and Nagar Haveli and Daman and Diu,2020,2,Insurance,651,101029
152,Delhi,2020,2,Insurance,11716,1897480
171,Goa,2020,2,Insurance,341,71100
190,Gujarat,2020,2,Insurance,7697,1430591
209,Haryana,2020,2,Insurance,6321,1179814
228,Himachal Pradesh,2020,2,Insurance,392,77936
247,Jammu & Kashmir,2020,2,Insurance,206,48484
266,Jharkhand,2020,2,Insurance,2063,405031
285,Karnataka,2020,2,Insurance,27358,4794150
304,Kerala,2020,2,Insurance,1588,360216
323,Ladakh,2020,2,Insurance,14,2538
359,Madhya Pradesh,2020,2,Insurance,6283,1198701
378,Maharashtra,2020,2,Insurance,39836,6879717
397,Manipur,2020,2,Insurance,55,12554
416,Meghalaya,2020,2,Insurance,41,8829
435,Mizoram,2020,2,Insurance,31,7322
454,Nagaland,2020,2,Insurance,41,9791
473,Odisha,2020,2,Insurance,2981,615193
492,Puducherry,2020,2,Insurance,112,22251
511,Punjab,2020,2,Insurance,2036,399452
530,Rajasthan,2020,2,Insurance,5373,1095933
549,Sikkim,2020,2,Insurance,21,4789
568,Tamil Nadu,2020,2,Insurance,5473,1075552
587,Telangana,2020,2,Insurance,19003,3419453
606,Tripura,2020,2,Insurance,88,22054
625,Uttar Pradesh,2020,2,Insurance,9884,1912266
644,Uttarakhand,2020,2,Insurance,660,134899
663,West Bengal,2020,2,Insurance,7619,1432764