In [200]:

import pandas as pd
import json
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
import re
import plotly.express as px

In [201]:
import os
path = "D:/Movies/Guvi_2/PhonePe/phonepe-pulse/data/aggregated/transaction/country/india/state"
aggState_list = os.listdir(path)
aggState_list

['andaman-&-nicobar-islands',
 'andhra-pradesh',
 'arunachal-pradesh',
 'assam',
 'bihar',
 'chandigarh',
 'chhattisgarh',
 'dadra-&-nagar-haveli-&-daman-&-diu',
 'delhi',
 'goa',
 'gujarat',
 'haryana',
 'himachal-pradesh',
 'jammu-&-kashmir',
 'jharkhand',
 'karnataka',
 'kerala',
 'ladakh',
 'lakshadweep',
 'madhya-pradesh',
 'maharashtra',
 'manipur',
 'meghalaya',
 'mizoram',
 'nagaland',
 'odisha',
 'puducherry',
 'punjab',
 'rajasthan',
 'sikkim',
 'tamil-nadu',
 'telangana',
 'tripura',
 'uttar-pradesh',
 'uttarakhand',
 'west-bengal']

In [202]:
import os
path = "D:/Movies/Guvi_2/PhonePe/phonepe-pulse/data/aggregated/transaction/country/india/state/"

Agg_state_list=os.listdir(path)
Agg_state_list
#Agg_state_list--> to get the list of states in India

#<------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------>#

#This is to extract the data's to create a dataframe

clm={'State':[], 'Year':[],'Quater':[],'Transaction_type':[], 'Transaction_count':[], 'Transaction_amount':[]}

for i in Agg_state_list:
    p_i=path+i+"/"
    Agg_yr=os.listdir(p_i)
    for j in Agg_yr:
        p_j=p_i+j+"/"
        Agg_yr_list=os.listdir(p_j)
        for k in Agg_yr_list:
            p_k=p_j+k
            Data=open(p_k,'r')
            D=json.load(Data)
            for z in D['data']['transactionData']:
              Name=z['name']
              count=z['paymentInstruments'][0]['count']
              amount=z['paymentInstruments'][0]['amount']
              clm['Transaction_type'].append(Name)
              clm['Transaction_count'].append(count)
              clm['Transaction_amount'].append(amount)
              clm['State'].append(i)
              clm['Year'].append(j)
              clm['Quater'].append(int(k.strip('.json')))
#Succesfully created a dataframe
agg_trans=pd.DataFrame(clm)

In [203]:
agg_trans.head()

,State,Year,Quater,Transaction_type,Transaction_count,Transaction_amount
0,andaman-&-nicobar-islands,2018,1,Recharge & bill payments,4200,1.845307e+06
1,andaman-&-nicobar-islands,2018,1,Peer-to-peer payments,1871,1.213866e+07
2,andaman-&-nicobar-islands,2018,1,Merchant payments,298,4.525072e+05
3,andaman-&-nicobar-islands,2018,1,Financial Services,33,1.060142e+04
4,andaman-&-nicobar-islands,2018,1,Others,256,1.846899e+05

In [204]:

agg_trans['State'] = agg_trans['State'].str.capitalize()

##caps_agg.head(15)
list(agg_trans['State'].unique())

['Andaman-&-nicobar-islands',
 'Andhra-pradesh',
 'Arunachal-pradesh',
 'Assam',
 'Bihar',
 'Chandigarh',
 'Chhattisgarh',
 'Dadra-&-nagar-haveli-&-daman-&-diu',
 'Delhi',
 'Goa',
 'Gujarat',
 'Haryana',
 'Himachal-pradesh',
 'Jammu-&-kashmir',
 'Jharkhand',
 'Karnataka',
 'Kerala',
 'Ladakh',
 'Lakshadweep',
 'Madhya-pradesh',
 'Maharashtra',
 'Manipur',
 'Meghalaya',
 'Mizoram',
 'Nagaland',
 'Odisha',
 'Puducherry',
 'Punjab',
 'Rajasthan',
 'Sikkim',
 'Tamil-nadu',
 'Telangana',
 'Tripura',
 'Uttar-pradesh',
 'Uttarakhand',
 'West-bengal']

In [205]:
import re
def modify(s):
    s = s.replace('-', ' ')
    return ' '.join(word.capitalize() for word in s.split())

agg_trans['State'] = agg_trans['State'].apply(modify)

In [206]:
update_cat = {
    "Andaman & Nicobar Islands": "Andaman & Nicobar",
    "Dadra & Nagar Haveli & Daman & Diu": "Dadra and Nagar Haveli and Daman and Diu"
}

agg_trans['State'] = agg_trans['State'].replace(update_cat)

In [207]:
agg_trans['Year'] = pd.to_datetime(agg_trans['Year']).dt.year

agg_trans['Year'].info()
agg_trans['Year']

<class 'pandas.core.series.Series'>
RangeIndex: 5034 entries, 0 to 5033
Series name: Year
Non-Null Count  Dtype
--------------  -----
5034 non-null   int32
dtypes: int32(1)
memory usage: 19.8 KB

0       2018
1       2018
2       2018
3       2018
4       2018
5       2018
6       2018
7       2018
8       2018
9       2018
10      2018
11      2018
12      2018
13      2018
14      2018
15      2018
16      2018
17      2018
18      2018
19      2018
20      2019
21      2019
22      2019
23      2019
24      2019
25      2019
26      2019
27      2019
28      2019
29      2019
30      2019
31      2019
32      2019
33      2019
34      2019
35      2019
36      2019
37      2019
38      2019
39      2019
40      2020
41      2020
42      2020
43      2020
44      2020
45      2020
46      2020
47      2020
48      2020
49      2020
50      2020
51      2020
52      2020
53      2020
54      2020
55      2020
56      2020
57      2020
58      2020
59      2020
60      2021
61      2021
62      2021
63      2021
64      2021
65      2021
66      2021
67      2021
68      2021
69      2021
70      2021
71      2021
72      2021
73      2021
74      2021
75      2021
76      2021
77      2021
78      2021
79      2021
80      2022
81      2022
82      2022
83      2022
84      2022
85      2022
86      2022
87      2022
88      2022
89      2022
90      2022
91      2022
92      2022
93      2022
94      2022
95      2022
96      2022
97      2022
98      2022
99      2022
100     2023
101     2023
102     2023
103     2023
104     2023
105     2023
106     2023
107     2023
108     2023
109     2023
110     2023
111     2023
112     2023
113     2023
114     2023
115     2023
116     2023
117     2023
118     2023
119     2023
120     2024
121     2024
122     2024
123     2024
124     2024
125     2024
126     2024
127     2024
128     2024
129     2024
130     2024
131     2024
132     2024
133     2024
134     2024
135     2024
136     2024
137     2024
138     2024
139     2024
140     2018
141     2018
142     2018
143     2018
144     2018
145     2018
146     2018
147     2018
148     2018
149     2018
150     2018
151     2018
152     2018
153     2018
154     2018
155     2018
156     2018
157     2018
158     2018
159     2018
160     2019
161     2019
162     2019
163     2019
164     2019
165     2019
166     2019
167     2019
168     2019
169     2019
170     2019
171     2019
172     2019
173     2019
174     2019
175     2019
176     2019
177     2019
178     2019
179     2019
180     2020
181     2020
182     2020
183     2020
184     2020
185     2020
186     2020
187     2020
188     2020
189     2020
190     2020
191     2020
192     2020
193     2020
194     2020
195     2020
196     2020
197     2020
198     2020
199     2020
200     2021
201     2021
202     2021
203     2021
204     2021
205     2021
206     2021
207     2021
208     2021
209     2021
210     2021
211     2021
212     2021
213     2021
214     2021
215     2021
216     2021
217     2021
218     2021
219     2021
220     2022
221     2022
222     2022
223     2022
224     2022
225     2022
226     2022
227     2022
228     2022
229     2022
230     2022
231     2022
232     2022
233     2022
234     2022
235     2022
236     2022
237     2022
238     2022
239     2022
240     2023
241     2023
242     2023
243     2023
244     2023
245     2023
246     2023
247     2023
248     2023
249     2023
250     2023
251     2023
252     2023
253     2023
254     2023
255     2023
256     2023
257     2023
258     2023
259     2023
260     2024
261     2024
262     2024
263     2024
264     2024
265     2024
266     2024
267     2024
268     2024
269     2024
270     2024
271     2024
272     2024
273     2024
274     2024
275     2024
276     2024
277     2024
278     2024
279     2024
280     2018
281     2018
282     2018
283     2018
284     2018
285     2018
286     2018
287     2018
288     2018
289     2018
290     2018
291     2018
292     2018
293     2018
294     2018
295     2018
296     2018
297     2018
298     2018
299     2018
300     2019
301     2019
302     2019
303     2019
304     2019
305     2019
306     2019
307     2019
308     2019
309     2019
310     2019
311     2019
312     2019
313     2019
314     2019
315     2019
316     2019
317     2019
318     2019
319     2019
320     2020
321     2020
322     2020
323     2020
324     2020
325     2020
326     2020
327     2020
328     2020
329     2020
330     2020
331     2020
332     2020
333     2020
334     2020
335     2020
336     2020
337     2020
338     2020
339     2020
340     2021
341     2021
342     2021
343     2021
344     2021
345     2021
346     2021
347     2021
348     2021
349     2021
350     2021
351     2021
352     2021
353     2021
354     2021
355     2021
356     2021
357     2021
358     2021
359     2021
360     2022
361     2022
362     2022
363     2022
364     2022
365     2022
366     2022
367     2022
368     2022
369     2022
370     2022
371     2022
372     2022
373     2022
374     2022
375     2022
376     2022
377     2022
378     2022
379     2022
380     2023
381     2023
382     2023
383     2023
384     2023
385     2023
386     2023
387     2023
388     2023
389     2023
390     2023
391     2023
392     2023
393     2023
394     2023
395     2023
396     2023
397     2023
398     2023
399     2023
400     2024
401     2024
402     2024
403     2024
404     2024
405     2024
406     2024
407     2024
408     2024
409     2024
410     2024
411     2024
412     2024
413     2024
414     2024
415     2024
416     2024
417     2024
418     2024
419     2024
420     2018
421     2018
422     2018
423     2018
424     2018
425     2018
426     2018
427     2018
428     2018
429     2018
430     2018
431     2018
432     2018
433     2018
434     2018
435     2018
436     2018
437     2018
438     2018
439     2018
440     2019
441     2019
442     2019
443     2019
444     2019
445     2019
446     2019
447     2019
448     2019
449     2019
450     2019
451     2019
452     2019
453     2019
454     2019
455     2019
456     2019
457     2019
458     2019
459     2019
460     2020
461     2020
462     2020
463     2020
464     2020
465     2020
466     2020
467     2020
468     2020
469     2020
470     2020
471     2020
472     2020
473     2020
474     2020
475     2020
476     2020
477     2020
478     2020
479     2020
480     2021
481     2021
482     2021
483     2021
484     2021
485     2021
486     2021
487     2021
488     2021
489     2021
490     2021
491     2021
492     2021
493     2021
494     2021
495     2021
496     2021
497     2021
498     2021
499     2021
500     2022
501     2022
502     2022
503     2022
504     2022
505     2022
506     2022
507     2022
508     2022
509     2022
510     2022
511     2022
512     2022
513     2022
514     2022
515     2022
516     2022
517     2022
518     2022
519     2022
520     2023
521     2023
522     2023
523     2023
524     2023
525     2023
526     2023
527     2023
528     2023
529     2023
530     2023
531     2023
532     2023
533     2023
534     2023
535     2023
536     2023
537     2023
538     2023
539     2023
540     2024
541     2024
542     2024
543     2024
544     2024
545     2024
546     2024
547     2024
548     2024
549     2024
550     2024
551     2024
552     2024
553     2024
554     2024
555     2024
556     2024
557     2024
558     2024
559     2024
560     2018
561     2018
562     2018
563     2018
564     2018
565     2018
566     2018
567     2018
568     2018
569     2018
570     2018
571     2018
572     2018
573     2018
574     2018
575     2018
576     2018
577     2018
578     2018
579     2018
580     2019
581     2019
582     2019
583     2019
584     2019
585     2019
586     2019
587     2019
588     2019
589     2019
590     2019
591     2019
592     2019
593     2019
594     2019
595     2019
596     2019
597     2019
598     2019
599     2019
600     2020
601     2020
602     2020
603     2020
604     2020
605     2020
606     2020
607     2020
608     2020
609     2020
610     2020
611     2020
612     2020
613     2020
614     2020
615     2020
616     2020
617     2020
618     2020
619     2020
620     2021
621     2021
622     2021
623     2021
624     2021
625     2021
626     2021
627     2021
628     2021
629     2021
630     2021
631     2021
632     2021
633     2021
634     2021
635     2021
636     2021
637     2021
638     2021
639     2021
640     2022
641     2022
642     2022
643     2022
644     2022
645     2022
646     2022
647     2022
648     2022
649     2022
650     2022
651     2022
652     2022
653     2022
654     2022
655     2022
656     2022
657     2022
658     2022
659     2022
660     2023
661     2023
662     2023
663     2023
664     2023
665     2023
666     2023
667     2023
668     2023
669     2023
670     2023
671     2023
672     2023
673     2023
674     2023
675     2023
676     2023
677     2023
678     2023
679     2023
680     2024
681     2024
682     2024
683     2024
684     2024
685     2024
686     2024
687     2024
688     2024
689     2024
690     2024
691     2024
692     2024
693     2024
694     2024
695     2024
696     2024
697     2024
698     2024
699     2024
700     2018
701     2018
702     2018
703     2018
704     2018
705     2018
706     2018
707     2018
708     2018
709     2018
710     2018
711     2018
712     2018
713     2018
714     2018
715     2018
716     2018
717     2018
718     2018
719     2018
720     2019
721     2019
722     2019
723     2019
724     2019
725     2019
726     2019
727     2019
728     2019
729     2019
730     2019
731     2019
732     2019
733     2019
734     2019
735     2019
736     2019
737     2019
738     2019
739     2019
740     2020
741     2020
742     2020
743     2020
744     2020
745     2020
746     2020
747     2020
748     2020
749     2020
750     2020
751     2020
752     2020
753     2020
754     2020
755     2020
756     2020
757     2020
758     2020
759     2020
760     2021
761     2021
762     2021
763     2021
764     2021
765     2021
766     2021
767     2021
768     2021
769     2021
770     2021
771     2021
772     2021
773     2021
774     2021
775     2021
776     2021
777     2021
778     2021
779     2021
780     2022
781     2022
782     2022
783     2022
784     2022
785     2022
786     2022
787     2022
788     2022
789     2022
790     2022
791     2022
792     2022
793     2022
794     2022
795     2022
796     2022
797     2022
798     2022
799     2022
800     2023
801     2023
802     2023
803     2023
804     2023
805     2023
806     2023
807     2023
808     2023
809     2023
810     2023
811     2023
812     2023
813     2023
814     2023
815     2023
816     2023
817     2023
818     2023
819     2023
820     2024
821     2024
822     2024
823     2024
824     2024
825     2024
826     2024
827     2024
828     2024
829     2024
830     2024
831     2024
832     2024
833     2024
834     2024
835     2024
836     2024
837     2024
838     2024
839     2024
840     2018
841     2018
842     2018
843     2018
844     2018
845     2018
846     2018
847     2018
848     2018
849     2018
850     2018
851     2018
852     2018
853     2018
854     2018
855     2018
856     2018
857     2018
858     2018
859     2018
860     2019
861     2019
862     2019
863     2019
864     2019
865     2019
866     2019
867     2019
868     2019
869     2019
870     2019
871     2019
872     2019
873     2019
874     2019
875     2019
876     2019
877     2019
878     2019
879     2019
880     2020
881     2020
882     2020
883     2020
884     2020
885     2020
886     2020
887     2020
888     2020
889     2020
890     2020
891     2020
892     2020
893     2020
894     2020
895     2020
896     2020
897     2020
898     2020
899     2020
900     2021
901     2021
902     2021
903     2021
904     2021
905     2021
906     2021
907     2021
908     2021
909     2021
910     2021
911     2021
912     2021
913     2021
914     2021
915     2021
916     2021
917     2021
918     2021
919     2021
920     2022
921     2022
922     2022
923     2022
924     2022
925     2022
926     2022
927     2022
928     2022
929     2022
930     2022
931     2022
932     2022
933     2022
934     2022
935     2022
936     2022
937     2022
938     2022
939     2022
940     2023
941     2023
942     2023
943     2023
944     2023
945     2023
946     2023
947     2023
948     2023
949     2023
950     2023
951     2023
952     2023
953     2023
954     2023
955     2023
956     2023
957     2023
958     2023
959     2023
960     2024
961     2024
962     2024
963     2024
964     2024
965     2024
966     2024
967     2024
968     2024
969     2024
970     2024
971     2024
972     2024
973     2024
974     2024
975     2024
976     2024
977     2024
978     2024
979     2024
980     2018
981     2018
982     2018
983     2018
984     2018
985     2018
986     2018
987     2018
988     2018
989     2018
990     2018
991     2018
992     2018
993     2018
994     2018
995     2018
996     2018
997     2018
998     2018
999     2018
1000    2019
1001    2019
1002    2019
1003    2019
1004    2019
1005    2019
1006    2019
1007    2019
1008    2019
1009    2019
1010    2019
1011    2019
1012    2019
1013    2019
1014    2019
1015    2019
1016    2019
1017    2019
1018    2019
1019    2019
1020    2020
1021    2020
1022    2020
1023    2020
1024    2020
1025    2020
1026    2020
1027    2020
1028    2020
1029    2020
1030    2020
1031    2020
1032    2020
1033    2020
1034    2020
1035    2020
1036    2020
1037    2020
1038    2020
1039    2020
1040    2021
1041    2021
1042    2021
1043    2021
1044    2021
1045    2021
1046    2021
1047    2021
1048    2021
1049    2021
1050    2021
1051    2021
1052    2021
1053    2021
1054    2021
1055    2021
1056    2021
1057    2021
1058    2021
1059    2021
1060    2022
1061    2022
1062    2022
1063    2022
1064    2022
1065    2022
1066    2022
1067    2022
1068    2022
1069    2022
1070    2022
1071    2022
1072    2022
1073    2022
1074    2022
1075    2022
1076    2022
1077    2022
1078    2022
1079    2022
1080    2023
1081    2023
1082    2023
1083    2023
1084    2023
1085    2023
1086    2023
1087    2023
1088    2023
1089    2023
1090    2023
1091    2023
1092    2023
1093    2023
1094    2023
1095    2023
1096    2023
1097    2023
1098    2023
1099    2023
1100    2024
1101    2024
1102    2024
1103    2024
1104    2024
1105    2024
1106    2024
1107    2024
1108    2024
1109    2024
1110    2024
1111    2024
1112    2024
1113    2024
1114    2024
1115    2024
1116    2024
1117    2024
1118    2024
1119    2024
1120    2018
1121    2018
1122    2018
1123    2018
1124    2018
1125    2018
1126    2018
1127    2018
1128    2018
1129    2018
1130    2018
1131    2018
1132    2018
1133    2018
1134    2018
1135    2018
1136    2018
1137    2018
1138    2018
1139    2018
1140    2019
1141    2019
1142    2019
1143    2019
1144    2019
1145    2019
1146    2019
1147    2019
1148    2019
1149    2019
1150    2019
1151    2019
1152    2019
1153    2019
1154    2019
1155    2019
1156    2019
1157    2019
1158    2019
1159    2019
1160    2020
1161    2020
1162    2020
1163    2020
1164    2020
1165    2020
1166    2020
1167    2020
1168    2020
1169    2020
1170    2020
1171    2020
1172    2020
1173    2020
1174    2020
1175    2020
1176    2020
1177    2020
1178    2020
1179    2020
1180    2021
1181    2021
1182    2021
1183    2021
1184    2021
1185    2021
1186    2021
1187    2021
1188    2021
1189    2021
1190    2021
1191    2021
1192    2021
1193    2021
1194    2021
1195    2021
1196    2021
1197    2021
1198    2021
1199    2021
1200    2022
1201    2022
1202    2022
1203    2022
1204    2022
1205    2022
1206    2022
1207    2022
1208    2022
1209    2022
1210    2022
1211    2022
1212    2022
1213    2022
1214    2022
1215    2022
1216    2022
1217    2022
1218    2022
1219    2022
1220    2023
1221    2023
1222    2023
1223    2023
1224    2023
1225    2023
1226    2023
1227    2023
1228    2023
1229    2023
1230    2023
1231    2023
1232    2023
1233    2023
1234    2023
1235    2023
1236    2023
1237    2023
1238    2023
1239    2023
1240    2024
1241    2024
1242    2024
1243    2024
1244    2024
1245    2024
1246    2024
1247    2024
1248    2024
1249    2024
1250    2024
1251    2024
1252    2024
1253    2024
1254    2024
1255    2024
1256    2024
1257    2024
1258    2024
1259    2024
1260    2018
1261    2018
1262    2018
1263    2018
1264    2018
1265    2018
1266    2018
1267    2018
1268    2018
1269    2018
1270    2018
1271    2018
1272    2018
1273    2018
1274    2018
1275    2018
1276    2018
1277    2018
1278    2018
1279    2018
1280    2019
1281    2019
1282    2019
1283    2019
1284    2019
1285    2019
1286    2019
1287    2019
1288    2019
1289    2019
1290    2019
1291    2019
1292    2019
1293    2019
1294    2019
1295    2019
1296    2019
1297    2019
1298    2019
1299    2019
1300    2020
1301    2020
1302    2020
1303    2020
1304    2020
1305    2020
1306    2020
1307    2020
1308    2020
1309    2020
1310    2020
1311    2020
1312    2020
1313    2020
1314    2020
1315    2020
1316    2020
1317    2020
1318    2020
1319    2020
1320    2021
1321    2021
1322    2021
1323    2021
1324    2021
1325    2021
1326    2021
1327    2021
1328    2021
1329    2021
1330    2021
1331    2021
1332    2021
1333    2021
1334    2021
1335    2021
1336    2021
1337    2021
1338    2021
1339    2021
1340    2022
1341    2022
1342    2022
1343    2022
1344    2022
1345    2022
1346    2022
1347    2022
1348    2022
1349    2022
1350    2022
1351    2022
1352    2022
1353    2022
1354    2022
1355    2022
1356    2022
1357    2022
1358    2022
1359    2022
1360    2023
1361    2023
1362    2023
1363    2023
1364    2023
1365    2023
1366    2023
1367    2023
1368    2023
1369    2023
1370    2023
1371    2023
1372    2023
1373    2023
1374    2023
1375    2023
1376    2023
1377    2023
1378    2023
1379    2023
1380    2024
1381    2024
1382    2024
1383    2024
1384    2024
1385    2024
1386    2024
1387    2024
1388    2024
1389    2024
1390    2024
1391    2024
1392    2024
1393    2024
1394    2024
1395    2024
1396    2024
1397    2024
1398    2024
1399    2024
1400    2018
1401    2018
1402    2018
1403    2018
1404    2018
1405    2018
1406    2018
1407    2018
1408    2018
1409    2018
1410    2018
1411    2018
1412    2018
1413    2018
1414    2018
1415    2018
1416    2018
1417    2018
1418    2018
1419    2018
1420    2019
1421    2019
1422    2019
1423    2019
1424    2019
1425    2019
1426    2019
1427    2019
1428    2019
1429    2019
1430    2019
1431    2019
1432    2019
1433    2019
1434    2019
1435    2019
1436    2019
1437    2019
1438    2019
1439    2019
1440    2020
1441    2020
1442    2020
1443    2020
1444    2020
1445    2020
1446    2020
1447    2020
1448    2020
1449    2020
1450    2020
1451    2020
1452    2020
1453    2020
1454    2020
1455    2020
1456    2020
1457    2020
1458    2020
1459    2020
1460    2021
1461    2021
1462    2021
1463    2021
1464    2021
1465    2021
1466    2021
1467    2021
1468    2021
1469    2021
1470    2021
1471    2021
1472    2021
1473    2021
1474    2021
1475    2021
1476    2021
1477    2021
1478    2021
1479    2021
1480    2022
1481    2022
1482    2022
1483    2022
1484    2022
1485    2022
1486    2022
1487    2022
1488    2022
1489    2022
1490    2022
1491    2022
1492    2022
1493    2022
1494    2022
1495    2022
1496    2022
1497    2022
1498    2022
1499    2022
1500    2023
1501    2023
1502    2023
1503    2023
1504    2023
1505    2023
1506    2023
1507    2023
1508    2023
1509    2023
1510    2023
1511    2023
1512    2023
1513    2023
1514    2023
1515    2023
1516    2023
1517    2023
1518    2023
1519    2023
1520    2024
1521    2024
1522    2024
1523    2024
1524    2024
1525    2024
1526    2024
1527    2024
1528    2024
1529    2024
1530    2024
1531    2024
1532    2024
1533    2024
1534    2024
1535    2024
1536    2024
1537    2024

In [208]:
agg_trans.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5034 entries, 0 to 5033
Data columns (total 6 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   State               5034 non-null   object
 1   Year                5034 non-null   int32
 2   Quater              5034 non-null   int64
 3   Transaction_type    5034 non-null   object
 4   Transaction_count   5034 non-null   int64
 5   Transaction_amount  5034 non-null   float64
dtypes: float64(1), int32(1), int64(2), object(2)
memory usage: 216.4+ KB

In [209]:
agg_trans['Transaction_type'].unique()

array(['Recharge & bill payments', 'Peer-to-peer payments',
       'Merchant payments', 'Financial Services', 'Others'], dtype=object)

In [210]:
agg_trans['Transaction_count'].unique()

array([    4200,     1871,      298, ..., 76043195,  2352084,   421806],
      dtype=int64)

In [211]:
agg_trans['Transaction_amount'].unique()

array([1.84530747e+06, 1.21386553e+07, 4.52507169e+05, ...,
       5.75340565e+10, 8.47296537e+08, 5.05364108e+08])

In [212]:
# pd.set_option('display.max_rows', None)

In [213]:
# pd.set_option('display.max_rows', None)

In [214]:
agg_trans.head(5)

,State,Year,Quater,Transaction_type,Transaction_count,Transaction_amount
0,Andaman & Nicobar,2018,1,Recharge & bill payments,4200,1.845307e+06
1,Andaman & Nicobar,2018,1,Peer-to-peer payments,1871,1.213866e+07
2,Andaman & Nicobar,2018,1,Merchant payments,298,4.525072e+05
3,Andaman & Nicobar,2018,1,Financial Services,33,1.060142e+04
4,Andaman & Nicobar,2018,1,Others,256,1.846899e+05

In [215]:
agg_trans.isnull().sum()

State                 0
Year                  0
Quater                0
Transaction_type      0
Transaction_count     0
Transaction_amount    0
dtype: int64

In [216]:
# agg_trans['Transaction_amount'] = agg_trans['Transaction_amount'].astype(int)
# agg_trans['Transaction_amount']

In [217]:
df_grp = agg_trans.groupby('State')['Transaction_count'].sum().reset_index()
# df_grp['YoY_Growth_%'] = df_grp.groupby('State')['Transaction_count'].pct_change()*100

df_grp.head()

               State  Transaction_count
0  Andaman & Nicobar           39706951
1     Andhra Pradesh        18918696723
2  Arunachal Pradesh          160223357
3              Assam         2262440836
4              Bihar        10941026824

In [218]:
agg_trans.groupby('State')['Transaction_amount'].sum().sort_values(ascending=False)

State
Telangana                                   4.165596e+13
Karnataka                                   4.067872e+13
Maharashtra                                 4.037420e+13
Andhra Pradesh                              3.466908e+13
Uttar Pradesh                               2.688521e+13
Rajasthan                                   2.634324e+13
Madhya Pradesh                              1.912528e+13
Bihar                                       1.790135e+13
West Bengal                                 1.558416e+13
Odisha                                      1.226398e+13
Tamil Nadu                                  1.193622e+13
Delhi                                       1.163752e+13
Gujarat                                     1.019291e+13
Haryana                                     9.645037e+12
Jharkhand                                   5.906646e+12
Chhattisgarh                                4.890472e+12
Assam                                       3.460792e+12
Kerala                                      3.076269e+12
Punjab                                      2.983078e+12
Uttarakhand                                 1.916489e+12
Jammu & Kashmir                             1.184683e+12
Himachal Pradesh                            6.875374e+11
Goa                                         5.110212e+11
Chandigarh                                  2.929066e+11
Arunachal Pradesh                           2.744350e+11
Puducherry                                  2.373171e+11
Dadra and Nagar Haveli and Daman and Diu    2.017199e+11
Tripura                                     2.005834e+11
Manipur                                     1.862656e+11
Meghalaya                                   1.625439e+11
Nagaland                                    1.303586e+11
Sikkim                                      1.189454e+11
Ladakh                                      8.899462e+10
Andaman & Nicobar                           7.066745e+10
Mizoram                                     4.610210e+10
Lakshadweep                                 1.609321e+09
Name: Transaction_amount, dtype: float64

In [219]:
agg_trans.groupby('Transaction_type')['Transaction_count'].sum()

Transaction_type
Financial Services             154208943
Merchant payments           130238755487
Others                         262050188
Peer-to-peer payments        85032446653
Recharge & bill payments     19596755603
Name: Transaction_count, dtype: int64

In [220]:
#Which category is declining

one = agg_trans.groupby('Transaction_type')['Transaction_count'].sum()
one = one.sort_values(ascending=False)
one

Transaction_type
Merchant payments           130238755487
Peer-to-peer payments        85032446653
Recharge & bill payments     19596755603
Others                         262050188
Financial Services             154208943
Name: Transaction_count, dtype: int64

In [221]:
df_grp.sort_values( by="Transaction_count",ascending=False).head(10)

             State  Transaction_count
20     Maharashtra        31985208732
15       Karnataka        30970946279
31       Telangana        26174684592
1   Andhra Pradesh        18918696723
33   Uttar Pradesh        18523603727
28       Rajasthan        17108537898
19  Madhya Pradesh        14072176059
4            Bihar        10941026824
35     West Bengal         9191499687
25          Odisha         8918527452

In [222]:
# Quarter wise transaction count

quatr = agg_trans.groupby(['Year', 'Quater'])['Transaction_count'].sum().reset_index()
quatr

    Year  Quater  Transaction_count
0   2018       1          134425599
1   2018       2          187365440
2   2018       3          341299764
3   2018       4          417111607
4   2019       1          708992981
5   2019       2          815380896
6   2019       3         1095009675
7   2019       4         1460443663
8   2020       1         1623038046
9   2020       2         1448608890
10  2020       3         2033051183
11  2020       4         2869276622
12  2021       1         3457585463
13  2021       2         3941370465
14  2021       3         5263737270
15  2021       4         6625736022
16  2022       1         7593179960
17  2022       2         9131576368
18  2022       3        10545339960
19  2022       4        12031197446
20  2023       1        13090517630
21  2023       2        15109557411
22  2023       3        17041723189
23  2023       4        19015256457
24  2024       1        21237053999
25  2024       2        24026109645
26  2024       3        25821015384
27  2024       4        28219255839

In [223]:
agg_trans['State'].unique()

array(['Andaman & Nicobar', 'Andhra Pradesh', 'Arunachal Pradesh',
       'Assam', 'Bihar', 'Chandigarh', 'Chhattisgarh',
       'Dadra and Nagar Haveli and Daman and Diu', 'Delhi', 'Goa',
       'Gujarat', 'Haryana', 'Himachal Pradesh', 'Jammu & Kashmir',
       'Jharkhand', 'Karnataka', 'Kerala', 'Ladakh', 'Lakshadweep',
       'Madhya Pradesh', 'Maharashtra', 'Manipur', 'Meghalaya', 'Mizoram',
       'Nagaland', 'Odisha', 'Puducherry', 'Punjab', 'Rajasthan',
       'Sikkim', 'Tamil Nadu', 'Telangana', 'Tripura', 'Uttar Pradesh',
       'Uttarakhand', 'West Bengal'], dtype=object)

In [224]:
#Southern states show consistently higher transaction volumes, indicating mature digital adoption,
#while North‑Eastern states show lower volumes but steady growth, 
# suggesting emerging markets for targeted campaigns.

In [225]:
import pandas as pd
import json
import os

df = df_grp

fig = px.choropleth(
    df,
    geojson="https://gist.githubusercontent.com/jbrobst/56c13bbbf9d97d187fea01ca62ea5112/raw/e388c4cae20aa53cb5090210a42ebb9b765c0a36/india_states.geojson",
    featureidkey='properties.ST_NM',
    locations='State',
    color='Transaction_count',
    color_continuous_scale='Reds'
)

fig.update_geos(fitbounds="locations", visible=False)

fig.show()

In [226]:
import os
path = "D:/Movies/Guvi_2/PhonePe/phonepe-pulse/data/aggregated/insurance/country/india/state/"


Agg_ins_list=os.listdir(path)
Agg_ins_list
#Agg_state_list--> to get the list of states in India

#<------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------>#

#This is to extract the data's to create a dataframe

clm={'State':[], 'Year':[],'Quater':[],'Transaction_type':[], 'Transaction_count':[], 'Transaction_amount':[]}

for i in Agg_ins_list:
    p_i=path+i+"/"
    Agg_yr=os.listdir(p_i)
    for j in Agg_yr:
        p_j=p_i+j+"/"
        Agg_yr_list=os.listdir(p_j)
        for k in Agg_yr_list:
            p_k=p_j+k
            Data=open(p_k,'r')
            D=json.load(Data)
            for z in D['data']['transactionData']:
              Name=z['name']
              count=z['paymentInstruments'][0]['count']
              amount=z['paymentInstruments'][0]['amount']
              clm['Transaction_type'].append(Name)
              clm['Transaction_count'].append(count)
              clm['Transaction_amount'].append(amount)
              clm['State'].append(i)
              clm['Year'].append(j)
              clm['Quater'].append(int(k.strip('.json')))
#Succesfully created a dataframe
agg_ins=pd.DataFrame(clm)

In [227]:
import re
def modify(s):
    s = s.replace('-', ' ')
    return ' '.join(word.capitalize() for word in s.split())

agg_ins['State'] = agg_ins['State'].apply(modify)

update_cat = {
    "Andaman & Nicobar Islands": "Andaman & Nicobar",
    "Dadra & Nagar Haveli & Daman & Diu": "Dadra and Nagar Haveli and Daman and Diu"
}

agg_ins['State'] = agg_ins['State'].replace(update_cat)

In [228]:
agg_ins['Year'] = pd.to_datetime(agg_ins['Year']).dt.year
agg_ins['Year'].info()
agg_ins['Year']

<class 'pandas.core.series.Series'>
RangeIndex: 682 entries, 0 to 681
Series name: Year
Non-Null Count  Dtype
--------------  -----
682 non-null    int32
dtypes: int32(1)
memory usage: 2.8 KB

0      2020
1      2020
2      2020
3      2021
4      2021
5      2021
6      2021
7      2022
8      2022
9      2022
10     2022
11     2023
12     2023
13     2023
14     2023
15     2024
16     2024
17     2024
18     2024
19     2020
20     2020
21     2020
22     2021
23     2021
24     2021
25     2021
26     2022
27     2022
28     2022
29     2022
30     2023
31     2023
32     2023
33     2023
34     2024
35     2024
36     2024
37     2024
38     2020
39     2020
40     2020
41     2021
42     2021
43     2021
44     2021
45     2022
46     2022
47     2022
48     2022
49     2023
50     2023
51     2023
52     2023
53     2024
54     2024
55     2024
56     2024
57     2020
58     2020
59     2020
60     2021
61     2021
62     2021
63     2021
64     2022
65     2022
66     2022
67     2022
68     2023
69     2023
70     2023
71     2023
72     2024
73     2024
74     2024
75     2024
76     2020
77     2020
78     2020
79     2021
80     2021
81     2021
82     2021
83     2022
84     2022
85     2022
86     2022
87     2023
88     2023
89     2023
90     2023
91     2024
92     2024
93     2024
94     2024
95     2020
96     2020
97     2020
98     2021
99     2021
100    2021
101    2021
102    2022
103    2022
104    2022
105    2022
106    2023
107    2023
108    2023
109    2023
110    2024
111    2024
112    2024
113    2024
114    2020
115    2020
116    2020
117    2021
118    2021
119    2021
120    2021
121    2022
122    2022
123    2022
124    2022
125    2023
126    2023
127    2023
128    2023
129    2024
130    2024
131    2024
132    2024
133    2020
134    2020
135    2020
136    2021
137    2021
138    2021
139    2021
140    2022
141    2022
142    2022
143    2022
144    2023
145    2023
146    2023
147    2023
148    2024
149    2024
150    2024
151    2024
152    2020
153    2020
154    2020
155    2021
156    2021
157    2021
158    2021
159    2022
160    2022
161    2022
162    2022
163    2023
164    2023
165    2023
166    2023
167    2024
168    2024
169    2024
170    2024
171    2020
172    2020
173    2020
174    2021
175    2021
176    2021
177    2021
178    2022
179    2022
180    2022
181    2022
182    2023
183    2023
184    2023
185    2023
186    2024
187    2024
188    2024
189    2024
190    2020
191    2020
192    2020
193    2021
194    2021
195    2021
196    2021
197    2022
198    2022
199    2022
200    2022
201    2023
202    2023
203    2023
204    2023
205    2024
206    2024
207    2024
208    2024
209    2020
210    2020
211    2020
212    2021
213    2021
214    2021
215    2021
216    2022
217    2022
218    2022
219    2022
220    2023
221    2023
222    2023
223    2023
224    2024
225    2024
226    2024
227    2024
228    2020
229    2020
230    2020
231    2021
232    2021
233    2021
234    2021
235    2022
236    2022
237    2022
238    2022
239    2023
240    2023
241    2023
242    2023
243    2024
244    2024
245    2024
246    2024
247    2020
248    2020
249    2020
250    2021
251    2021
252    2021
253    2021
254    2022
255    2022
256    2022
257    2022
258    2023
259    2023
260    2023
261    2023
262    2024
263    2024
264    2024
265    2024
266    2020
267    2020
268    2020
269    2021
270    2021
271    2021
272    2021
273    2022
274    2022
275    2022
276    2022
277    2023
278    2023
279    2023
280    2023
281    2024
282    2024
283    2024
284    2024
285    2020
286    2020
287    2020
288    2021
289    2021
290    2021
291    2021
292    2022
293    2022
294    2022
295    2022
296    2023
297    2023
298    2023
299    2023
300    2024
301    2024
302    2024
303    2024
304    2020
305    2020
306    2020
307    2021
308    2021
309    2021
310    2021
311    2022
312    2022
313    2022
314    2022
315    2023
316    2023
317    2023
318    2023
319    2024
320    2024
321    2024
322    2024
323    2020
324    2020
325    2020
326    2021
327    2021
328    2021
329    2021
330    2022
331    2022
332    2022
333    2022
334    2023
335    2023
336    2023
337    2023
338    2024
339    2024
340    2024
341    2024
342    2020
343    2021
344    2021
345    2021
346    2021
347    2022
348    2022
349    2022
350    2022
351    2023
352    2023
353    2023
354    2023
355    2024
356    2024
357    2024
358    2024
359    2020
360    2020
361    2020
362    2021
363    2021
364    2021
365    2021
366    2022
367    2022
368    2022
369    2022
370    2023
371    2023
372    2023
373    2023
374    2024
375    2024
376    2024
377    2024
378    2020
379    2020
380    2020
381    2021
382    2021
383    2021
384    2021
385    2022
386    2022
387    2022
388    2022
389    2023
390    2023
391    2023
392    2023
393    2024
394    2024
395    2024
396    2024
397    2020
398    2020
399    2020
400    2021
401    2021
402    2021
403    2021
404    2022
405    2022
406    2022
407    2022
408    2023
409    2023
410    2023
411    2023
412    2024
413    2024
414    2024
415    2024
416    2020
417    2020
418    2020
419    2021
420    2021
421    2021
422    2021
423    2022
424    2022
425    2022
426    2022
427    2023
428    2023
429    2023
430    2023
431    2024
432    2024
433    2024
434    2024
435    2020
436    2020
437    2020
438    2021
439    2021
440    2021
441    2021
442    2022
443    2022
444    2022
445    2022
446    2023
447    2023
448    2023
449    2023
450    2024
451    2024
452    2024
453    2024
454    2020
455    2020
456    2020
457    2021
458    2021
459    2021
460    2021
461    2022
462    2022
463    2022
464    2022
465    2023
466    2023
467    2023
468    2023
469    2024
470    2024
471    2024
472    2024
473    2020
474    2020
475    2020
476    2021
477    2021
478    2021
479    2021
480    2022
481    2022
482    2022
483    2022
484    2023
485    2023
486    2023
487    2023
488    2024
489    2024
490    2024
491    2024
492    2020
493    2020
494    2020
495    2021
496    2021
497    2021
498    2021
499    2022
500    2022
501    2022
502    2022
503    2023
504    2023
505    2023
506    2023
507    2024
508    2024
509    2024
510    2024
511    2020
512    2020
513    2020
514    2021
515    2021
516    2021
517    2021
518    2022
519    2022
520    2022
521    2022
522    2023
523    2023
524    2023
525    2023
526    2024
527    2024
528    2024
529    2024
530    2020
531    2020
532    2020
533    2021
534    2021
535    2021
536    2021
537    2022
538    2022
539    2022
540    2022
541    2023
542    2023
543    2023
544    2023
545    2024
546    2024
547    2024
548    2024
549    2020
550    2020
551    2020
552    2021
553    2021
554    2021
555    2021
556    2022
557    2022
558    2022
559    2022
560    2023
561    2023
562    2023
563    2023
564    2024
565    2024
566    2024
567    2024
568    2020
569    2020
570    2020
571    2021
572    2021
573    2021
574    2021
575    2022
576    2022
577    2022
578    2022
579    2023
580    2023
581    2023
582    2023
583    2024
584    2024
585    2024
586    2024
587    2020
588    2020
589    2020
590    2021
591    2021
592    2021
593    2021
594    2022
595    2022
596    2022
597    2022
598    2023
599    2023
600    2023
601    2023
602    2024
603    2024
604    2024
605    2024
606    2020
607    2020
608    2020
609    2021
610    2021
611    2021
612    2021
613    2022
614    2022
615    2022
616    2022
617    2023
618    2023
619    2023
620    2023
621    2024
622    2024
623    2024
624    2024
625    2020
626    2020
627    2020
628    2021
629    2021
630    2021
631    2021
632    2022
633    2022
634    2022
635    2022
636    2023
637    2023
638    2023
639    2023
640    2024
641    2024
642    2024
643    2024
644    2020
645    2020
646    2020
647    2021
648    2021
649    2021
650    2021
651    2022
652    2022
653    2022
654    2022
655    2023
656    2023
657    2023
658    2023
659    2024
660    2024
661    2024
662    2024
663    2020
664    2020
665    2020
666    2021
667    2021
668    2021
669    2021
670    2022
671    2022
672    2022
673    2022
674    2023
675    2023
676    2023
677    2023
678    2024
679    2024
680    2024
681    2024
Name: Year, dtype: int32

In [229]:
agg_ins.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 682 entries, 0 to 681
Data columns (total 6 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   State               682 non-null    object
 1   Year                682 non-null    int32
 2   Quater              682 non-null    int64
 3   Transaction_type    682 non-null    object
 4   Transaction_count   682 non-null    int64
 5   Transaction_amount  682 non-null    float64
dtypes: float64(1), int32(1), int64(2), object(2)
memory usage: 29.4+ KB

In [230]:
agg_ins.head()

,State,Year,Quater,Transaction_type,Transaction_count,Transaction_amount
0,Andaman & Nicobar,2020,2,Insurance,6,1360.0
1,Andaman & Nicobar,2020,3,Insurance,41,15380.0
2,Andaman & Nicobar,2020,4,Insurance,124,157975.0
3,Andaman & Nicobar,2021,1,Insurance,225,244266.0
4,Andaman & Nicobar,2021,2,Insurance,137,181504.0

In [231]:
# States with better digital development have higher insurance usage, while many other regions still have low insurance coverage.
df_grp_ins = agg_ins.groupby('State')[['Transaction_count', 'Transaction_amount']].sum().reset_index()
df_grp_ins.head(10)

,State,Transaction_count,Transaction_amount
0,Andaman & Nicobar,12997,19386792.0
1,Andhra Pradesh,697769,812222985.0
2,Arunachal Pradesh,10214,23420755.0
3,Assam,262818,411831038.0
4,Bihar,536592,671056815.0
5,Chandigarh,22079,33285885.0
6,Chhattisgarh,189517,274344886.0
7,Dadra and Nagar Haveli and Daman and Diu,13792,17992414.0
8,Delhi,652514,815365172.0
9,Goa,59872,83730005.0

In [232]:
agg_ins['Transaction_amount'] = agg_ins['Transaction_amount'].astype(int)

In [233]:
# Shows growth.


ins_trend = (agg_ins.groupby(['Year', 'Quater'])['Transaction_amount'].sum().reset_index())
ins_trend

    Year  Quater  Transaction_amount
0   2020       2            33732166
1   2020       3            89495076
2   2020       4           170979933
3   2021       1           206295702
4   2021       2           295065422
5   2021       3           342388829
6   2021       4           655420085
7   2022       1           887413773
8   2022       2           857012844
9   2022       3          1054672890
10  2022       4          1439743924
11  2023       1          1408776725
12  2023       2          1347352521
13  2023       3          1445209417
14  2023       4          1855267395
15  2024       1          1931922471
16  2024       2          1759607284
17  2024       3          1941265641
18  2024       4          2293956286

In [234]:
import pandas as pd
import json
import os

df = df_grp_ins

fig = px.choropleth(
    df,
    geojson="https://gist.githubusercontent.com/jbrobst/56c13bbbf9d97d187fea01ca62ea5112/raw/e388c4cae20aa53cb5090210a42ebb9b765c0a36/india_states.geojson",
    featureidkey='properties.ST_NM',
    locations='State',
    color='Transaction_count',
    color_continuous_scale='Rainbow'
)

fig.update_geos(fitbounds="locations", visible=False)
fig.update_layout(title_text='Insurance Transactions by State in India')

fig.show()

In [235]:
# path = D:\Movies\Guvi_2\PhonePe\phonepe-pulse\data\aggregated\user\country\india\state\andaman-&-nicobar-islands

In [236]:
import os
import json
import pandas as pd

path = "D:/Movies/Guvi_2/PhonePe/phonepe-pulse/data/aggregated/user/country/india/state/"
agg_user_list = os.listdir(path)

# <-------------------------------------------------------------------->
# Columns for agg_user table

clm = {
    'State': [],
    'Year': [],
    'Quarter': [],
    'Registered_users': [],
    'App_opens': [],
    'Brand': [],
    'User_count': [],
    'User_percentage': []
}

for i in agg_user_list:               
    p_i = path + i + "/"
    user_yr = os.listdir(p_i)

    for j in user_yr:                   
        p_j = p_i + j + "/"
        user_qtr = os.listdir(p_j)

        for k in user_qtr:                
            p_k = p_j + k

            with open(p_k, 'r') as Data:
                D = json.load(Data)

                # 🔹 Aggregated user data
                aggregated = D['data'].get('aggregated', {})
                reg_users = aggregated.get('registeredUsers')
                app_opens = aggregated.get('appOpens')

                # 🔹 Device-wise data
                users = D['data'].get('usersByDevice')
                if users is None:
                    continue

                for z in users:
                    clm['State'].append(i)
                    clm['Year'].append(j)
                    clm['Quarter'].append(int(k.strip('.json')))
                    clm['Registered_users'].append(reg_users)
                    clm['App_opens'].append(app_opens)
                    clm['Brand'].append(z['brand'])
                    clm['User_count'].append(z['count'])
                    clm['User_percentage'].append(z['percentage'])

agg_user = pd.DataFrame(clm)

In [237]:
# import os

# path = "D:/Movies/Guvi_2/PhonePe/phonepe-pulse/data/aggregated/user/country/india/state/"


# agg_user_list=os.listdir(path)
# agg_user_list

# #<------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------>#

# #This is to extract the data's to create a dataframe

# clm = {
#     'State': [],
#     'Year': [],
#     'Quarter': [],
#     'Brand': [],
#     'User_count': [],
#     'User_percentage': []
# }

# for i in agg_user_list:                 # state
#     p_i = path + i + "/"
#     user_yr = os.listdir(p_i)
    
#     for j in user_yr:               # year
#         p_j = p_i + j + "/"
#         user_yr_list = os.listdir(p_j)
        
#         for k in user_yr_list:      # quarter json
#             p_k = p_j + k
            
#             with open(p_k, 'r') as Data:
#                 D = json.load(Data)

#                 # 🔒 SAFE ACCESS
#                 users = D['data'].get('usersByDevice')

#                 # Skip if data is missing
#                 if users is None:
#                     continue

#                 for z in users:
#                     brand = z['brand']
#                     count = z['count']
#                     percentage = z['percentage']

#                     clm['Brand'].append(brand)
#                     clm['User_count'].append(count)
#                     clm['User_percentage'].append(percentage)
#                     clm['State'].append(i)
#                     clm['Year'].append(j)
#                     clm['Quarter'].append(int(k.strip('.json')))
                    
# agg_user=pd.DataFrame(clm)

In [238]:
agg_user.head(5)

,State,Year,Quarter,Registered_users,App_opens,Brand,User_count,User_percentage
0,andaman-&-nicobar-islands,2018,1,6740,0,Xiaomi,1665,0.247033
1,andaman-&-nicobar-islands,2018,1,6740,0,Samsung,1445,0.214392
2,andaman-&-nicobar-islands,2018,1,6740,0,Vivo,982,0.145697
3,andaman-&-nicobar-islands,2018,1,6740,0,Oppo,501,0.074332
4,andaman-&-nicobar-islands,2018,1,6740,0,OnePlus,332,0.049258

In [239]:
import re
def modify(s):
    s = s.replace('-', ' ')
    return ' '.join(word.capitalize() for word in s.split())

agg_user['State'] = agg_user['State'].apply(modify)

update_cat = {
    "Andaman & Nicobar Islands": "Andaman & Nicobar",
    "Dadra & Nagar Haveli & Daman & Diu": "Dadra and Nagar Haveli and Daman and Diu"
}

agg_user['State'] = agg_user['State'].replace(update_cat)

In [240]:
agg_user.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6732 entries, 0 to 6731
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   State             6732 non-null   object
 1   Year              6732 non-null   object
 2   Quarter           6732 non-null   int64
 3   Registered_users  6732 non-null   int64
 4   App_opens         6732 non-null   int64
 5   Brand             6732 non-null   object
 6   User_count        6732 non-null   int64
 7   User_percentage   6732 non-null   float64
dtypes: float64(1), int64(4), object(3)
memory usage: 420.9+ KB

In [241]:
agg_user['Year'] = pd.to_datetime(agg_user['Year']).dt.year

agg_user['Year'].info()
agg_user['Year']

<class 'pandas.core.series.Series'>
RangeIndex: 6732 entries, 0 to 6731
Series name: Year
Non-Null Count  Dtype
--------------  -----
6732 non-null   int32
dtypes: int32(1)
memory usage: 26.4 KB

0       2018
1       2018
2       2018
3       2018
4       2018
5       2018
6       2018
7       2018
8       2018
9       2018
10      2018
11      2018
12      2018
13      2018
14      2018
15      2018
16      2018
17      2018
18      2018
19      2018
20      2018
21      2018
22      2018
23      2018
24      2018
25      2018
26      2018
27      2018
28      2018
29      2018
30      2018
31      2018
32      2018
33      2018
34      2018
35      2018
36      2018
37      2018
38      2018
39      2018
40      2018
41      2018
42      2018
43      2018
44      2019
45      2019
46      2019
47      2019
48      2019
49      2019
50      2019
51      2019
52      2019
53      2019
54      2019
55      2019
56      2019
57      2019
58      2019
59      2019
60      2019
61      2019
62      2019
63      2019
64      2019
65      2019
66      2019
67      2019
68      2019
69      2019
70      2019
71      2019
72      2019
73      2019
74      2019
75      2019
76      2019
77      2019
78      2019
79      2019
80      2019
81      2019
82      2019
83      2019
84      2019
85      2019
86      2019
87      2019
88      2020
89      2020
90      2020
91      2020
92      2020
93      2020
94      2020
95      2020
96      2020
97      2020
98      2020
99      2020
100     2020
101     2020
102     2020
103     2020
104     2020
105     2020
106     2020
107     2020
108     2020
109     2020
110     2020
111     2020
112     2020
113     2020
114     2020
115     2020
116     2020
117     2020
118     2020
119     2020
120     2020
121     2020
122     2020
123     2020
124     2020
125     2020
126     2020
127     2020
128     2020
129     2020
130     2020
131     2020
132     2021
133     2021
134     2021
135     2021
136     2021
137     2021
138     2021
139     2021
140     2021
141     2021
142     2021
143     2021
144     2021
145     2021
146     2021
147     2021
148     2021
149     2021
150     2021
151     2021
152     2021
153     2021
154     2021
155     2021
156     2021
157     2021
158     2021
159     2021
160     2021
161     2021
162     2021
163     2021
164     2021
165     2021
166     2021
167     2021
168     2021
169     2021
170     2021
171     2021
172     2021
173     2021
174     2021
175     2021
176     2022
177     2022
178     2022
179     2022
180     2022
181     2022
182     2022
183     2022
184     2022
185     2022
186     2022
187     2018
188     2018
189     2018
190     2018
191     2018
192     2018
193     2018
194     2018
195     2018
196     2018
197     2018
198     2018
199     2018
200     2018
201     2018
202     2018
203     2018
204     2018
205     2018
206     2018
207     2018
208     2018
209     2018
210     2018
211     2018
212     2018
213     2018
214     2018
215     2018
216     2018
217     2018
218     2018
219     2018
220     2018
221     2018
222     2018
223     2018
224     2018
225     2018
226     2018
227     2018
228     2018
229     2018
230     2018
231     2019
232     2019
233     2019
234     2019
235     2019
236     2019
237     2019
238     2019
239     2019
240     2019
241     2019
242     2019
243     2019
244     2019
245     2019
246     2019
247     2019
248     2019
249     2019
250     2019
251     2019
252     2019
253     2019
254     2019
255     2019
256     2019
257     2019
258     2019
259     2019
260     2019
261     2019
262     2019
263     2019
264     2019
265     2019
266     2019
267     2019
268     2019
269     2019
270     2019
271     2019
272     2019
273     2019
274     2019
275     2020
276     2020
277     2020
278     2020
279     2020
280     2020
281     2020
282     2020
283     2020
284     2020
285     2020
286     2020
287     2020
288     2020
289     2020
290     2020
291     2020
292     2020
293     2020
294     2020
295     2020
296     2020
297     2020
298     2020
299     2020
300     2020
301     2020
302     2020
303     2020
304     2020
305     2020
306     2020
307     2020
308     2020
309     2020
310     2020
311     2020
312     2020
313     2020
314     2020
315     2020
316     2020
317     2020
318     2020
319     2021
320     2021
321     2021
322     2021
323     2021
324     2021
325     2021
326     2021
327     2021
328     2021
329     2021
330     2021
331     2021
332     2021
333     2021
334     2021
335     2021
336     2021
337     2021
338     2021
339     2021
340     2021
341     2021
342     2021
343     2021
344     2021
345     2021
346     2021
347     2021
348     2021
349     2021
350     2021
351     2021
352     2021
353     2021
354     2021
355     2021
356     2021
357     2021
358     2021
359     2021
360     2021
361     2021
362     2021
363     2022
364     2022
365     2022
366     2022
367     2022
368     2022
369     2022
370     2022
371     2022
372     2022
373     2022
374     2018
375     2018
376     2018
377     2018
378     2018
379     2018
380     2018
381     2018
382     2018
383     2018
384     2018
385     2018
386     2018
387     2018
388     2018
389     2018
390     2018
391     2018
392     2018
393     2018
394     2018
395     2018
396     2018
397     2018
398     2018
399     2018
400     2018
401     2018
402     2018
403     2018
404     2018
405     2018
406     2018
407     2018
408     2018
409     2018
410     2018
411     2018
412     2018
413     2018
414     2018
415     2018
416     2018
417     2018
418     2019
419     2019
420     2019
421     2019
422     2019
423     2019
424     2019
425     2019
426     2019
427     2019
428     2019
429     2019
430     2019
431     2019
432     2019
433     2019
434     2019
435     2019
436     2019
437     2019
438     2019
439     2019
440     2019
441     2019
442     2019
443     2019
444     2019
445     2019
446     2019
447     2019
448     2019
449     2019
450     2019
451     2019
452     2019
453     2019
454     2019
455     2019
456     2019
457     2019
458     2019
459     2019
460     2019
461     2019
462     2020
463     2020
464     2020
465     2020
466     2020
467     2020
468     2020
469     2020
470     2020
471     2020
472     2020
473     2020
474     2020
475     2020
476     2020
477     2020
478     2020
479     2020
480     2020
481     2020
482     2020
483     2020
484     2020
485     2020
486     2020
487     2020
488     2020
489     2020
490     2020
491     2020
492     2020
493     2020
494     2020
495     2020
496     2020
497     2020
498     2020
499     2020
500     2020
501     2020
502     2020
503     2020
504     2020
505     2020
506     2021
507     2021
508     2021
509     2021
510     2021
511     2021
512     2021
513     2021
514     2021
515     2021
516     2021
517     2021
518     2021
519     2021
520     2021
521     2021
522     2021
523     2021
524     2021
525     2021
526     2021
527     2021
528     2021
529     2021
530     2021
531     2021
532     2021
533     2021
534     2021
535     2021
536     2021
537     2021
538     2021
539     2021
540     2021
541     2021
542     2021
543     2021
544     2021
545     2021
546     2021
547     2021
548     2021
549     2021
550     2022
551     2022
552     2022
553     2022
554     2022
555     2022
556     2022
557     2022
558     2022
559     2022
560     2022
561     2018
562     2018
563     2018
564     2018
565     2018
566     2018
567     2018
568     2018
569     2018
570     2018
571     2018
572     2018
573     2018
574     2018
575     2018
576     2018
577     2018
578     2018
579     2018
580     2018
581     2018
582     2018
583     2018
584     2018
585     2018
586     2018
587     2018
588     2018
589     2018
590     2018
591     2018
592     2018
593     2018
594     2018
595     2018
596     2018
597     2018
598     2018
599     2018
600     2018
601     2018
602     2018
603     2018
604     2018
605     2019
606     2019
607     2019
608     2019
609     2019
610     2019
611     2019
612     2019
613     2019
614     2019
615     2019
616     2019
617     2019
618     2019
619     2019
620     2019
621     2019
622     2019
623     2019
624     2019
625     2019
626     2019
627     2019
628     2019
629     2019
630     2019
631     2019
632     2019
633     2019
634     2019
635     2019
636     2019
637     2019
638     2019
639     2019
640     2019
641     2019
642     2019
643     2019
644     2019
645     2019
646     2019
647     2019
648     2019
649     2020
650     2020
651     2020
652     2020
653     2020
654     2020
655     2020
656     2020
657     2020
658     2020
659     2020
660     2020
661     2020
662     2020
663     2020
664     2020
665     2020
666     2020
667     2020
668     2020
669     2020
670     2020
671     2020
672     2020
673     2020
674     2020
675     2020
676     2020
677     2020
678     2020
679     2020
680     2020
681     2020
682     2020
683     2020
684     2020
685     2020
686     2020
687     2020
688     2020
689     2020
690     2020
691     2020
692     2020
693     2021
694     2021
695     2021
696     2021
697     2021
698     2021
699     2021
700     2021
701     2021
702     2021
703     2021
704     2021
705     2021
706     2021
707     2021
708     2021
709     2021
710     2021
711     2021
712     2021
713     2021
714     2021
715     2021
716     2021
717     2021
718     2021
719     2021
720     2021
721     2021
722     2021
723     2021
724     2021
725     2021
726     2021
727     2021
728     2021
729     2021
730     2021
731     2021
732     2021
733     2021
734     2021
735     2021
736     2021
737     2022
738     2022
739     2022
740     2022
741     2022
742     2022
743     2022
744     2022
745     2022
746     2022
747     2022
748     2018
749     2018
750     2018
751     2018
752     2018
753     2018
754     2018
755     2018
756     2018
757     2018
758     2018
759     2018
760     2018
761     2018
762     2018
763     2018
764     2018
765     2018
766     2018
767     2018
768     2018
769     2018
770     2018
771     2018
772     2018
773     2018
774     2018
775     2018
776     2018
777     2018
778     2018
779     2018
780     2018
781     2018
782     2018
783     2018
784     2018
785     2018
786     2018
787     2018
788     2018
789     2018
790     2018
791     2018
792     2019
793     2019
794     2019
795     2019
796     2019
797     2019
798     2019
799     2019
800     2019
801     2019
802     2019
803     2019
804     2019
805     2019
806     2019
807     2019
808     2019
809     2019
810     2019
811     2019
812     2019
813     2019
814     2019
815     2019
816     2019
817     2019
818     2019
819     2019
820     2019
821     2019
822     2019
823     2019
824     2019
825     2019
826     2019
827     2019
828     2019
829     2019
830     2019
831     2019
832     2019
833     2019
834     2019
835     2019
836     2020
837     2020
838     2020
839     2020
840     2020
841     2020
842     2020
843     2020
844     2020
845     2020
846     2020
847     2020
848     2020
849     2020
850     2020
851     2020
852     2020
853     2020
854     2020
855     2020
856     2020
857     2020
858     2020
859     2020
860     2020
861     2020
862     2020
863     2020
864     2020
865     2020
866     2020
867     2020
868     2020
869     2020
870     2020
871     2020
872     2020
873     2020
874     2020
875     2020
876     2020
877     2020
878     2020
879     2020
880     2021
881     2021
882     2021
883     2021
884     2021
885     2021
886     2021
887     2021
888     2021
889     2021
890     2021
891     2021
892     2021
893     2021
894     2021
895     2021
896     2021
897     2021
898     2021
899     2021
900     2021
901     2021
902     2021
903     2021
904     2021
905     2021
906     2021
907     2021
908     2021
909     2021
910     2021
911     2021
912     2021
913     2021
914     2021
915     2021
916     2021
917     2021
918     2021
919     2021
920     2021
921     2021
922     2021
923     2021
924     2022
925     2022
926     2022
927     2022
928     2022
929     2022
930     2022
931     2022
932     2022
933     2022
934     2022
935     2018
936     2018
937     2018
938     2018
939     2018
940     2018
941     2018
942     2018
943     2018
944     2018
945     2018
946     2018
947     2018
948     2018
949     2018
950     2018
951     2018
952     2018
953     2018
954     2018
955     2018
956     2018
957     2018
958     2018
959     2018
960     2018
961     2018
962     2018
963     2018
964     2018
965     2018
966     2018
967     2018
968     2018
969     2018
970     2018
971     2018
972     2018
973     2018
974     2018
975     2018
976     2018
977     2018
978     2018
979     2019
980     2019
981     2019
982     2019
983     2019
984     2019
985     2019
986     2019
987     2019
988     2019
989     2019
990     2019
991     2019
992     2019
993     2019
994     2019
995     2019
996     2019
997     2019
998     2019
999     2019
1000    2019
1001    2019
1002    2019
1003    2019
1004    2019
1005    2019
1006    2019
1007    2019
1008    2019
1009    2019
1010    2019
1011    2019
1012    2019
1013    2019
1014    2019
1015    2019
1016    2019
1017    2019
1018    2019
1019    2019
1020    2019
1021    2019
1022    2019
1023    2020
1024    2020
1025    2020
1026    2020
1027    2020
1028    2020
1029    2020
1030    2020
1031    2020
1032    2020
1033    2020
1034    2020
1035    2020
1036    2020
1037    2020
1038    2020
1039    2020
1040    2020
1041    2020
1042    2020
1043    2020
1044    2020
1045    2020
1046    2020
1047    2020
1048    2020
1049    2020
1050    2020
1051    2020
1052    2020
1053    2020
1054    2020
1055    2020
1056    2020
1057    2020
1058    2020
1059    2020
1060    2020
1061    2020
1062    2020
1063    2020
1064    2020
1065    2020
1066    2020
1067    2021
1068    2021
1069    2021
1070    2021
1071    2021
1072    2021
1073    2021
1074    2021
1075    2021
1076    2021
1077    2021
1078    2021
1079    2021
1080    2021
1081    2021
1082    2021
1083    2021
1084    2021
1085    2021
1086    2021
1087    2021
1088    2021
1089    2021
1090    2021
1091    2021
1092    2021
1093    2021
1094    2021
1095    2021
1096    2021
1097    2021
1098    2021
1099    2021
1100    2021
1101    2021
1102    2021
1103    2021
1104    2021
1105    2021
1106    2021
1107    2021
1108    2021
1109    2021
1110    2021
1111    2022
1112    2022
1113    2022
1114    2022
1115    2022
1116    2022
1117    2022
1118    2022
1119    2022
1120    2022
1121    2022
1122    2018
1123    2018
1124    2018
1125    2018
1126    2018
1127    2018
1128    2018
1129    2018
1130    2018
1131    2018
1132    2018
1133    2018
1134    2018
1135    2018
1136    2018
1137    2018
1138    2018
1139    2018
1140    2018
1141    2018
1142    2018
1143    2018
1144    2018
1145    2018
1146    2018
1147    2018
1148    2018
1149    2018
1150    2018
1151    2018
1152    2018
1153    2018
1154    2018
1155    2018
1156    2018
1157    2018
1158    2018
1159    2018
1160    2018
1161    2018
1162    2018
1163    2018
1164    2018
1165    2018
1166    2019
1167    2019
1168    2019
1169    2019
1170    2019
1171    2019
1172    2019
1173    2019
1174    2019
1175    2019
1176    2019
1177    2019
1178    2019
1179    2019
1180    2019
1181    2019
1182    2019
1183    2019
1184    2019
1185    2019
1186    2019
1187    2019
1188    2019
1189    2019
1190    2019
1191    2019
1192    2019
1193    2019
1194    2019
1195    2019
1196    2019
1197    2019
1198    2019
1199    2019
1200    2019
1201    2019
1202    2019
1203    2019
1204    2019
1205    2019
1206    2019
1207    2019
1208    2019
1209    2019
1210    2020
1211    2020
1212    2020
1213    2020
1214    2020
1215    2020
1216    2020
1217    2020
1218    2020
1219    2020
1220    2020
1221    2020
1222    2020
1223    2020
1224    2020
1225    2020
1226    2020
1227    2020
1228    2020
1229    2020
1230    2020
1231    2020
1232    2020
1233    2020
1234    2020
1235    2020
1236    2020
1237    2020
1238    2020
1239    2020
1240    2020
1241    2020
1242    2020
1243    2020
1244    2020
1245    2020
1246    2020
1247    2020
1248    2020
1249    2020
1250    2020
1251    2020
1252    2020
1253    2020
1254    2021
1255    2021
1256    2021
1257    2021
1258    2021
1259    2021
1260    2021
1261    2021
1262    2021
1263    2021
1264    2021
1265    2021
1266    2021
1267    2021
1268    2021
1269    2021
1270    2021
1271    2021
1272    2021
1273    2021
1274    2021
1275    2021
1276    2021
1277    2021
1278    2021
1279    2021
1280    2021
1281    2021
1282    2021
1283    2021
1284    2021
1285    2021
1286    2021
1287    2021
1288    2021
1289    2021
1290    2021
1291    2021
1292    2021
1293    2021
1294    2021
1295    2021
1296    2021
1297    2021
1298    2022
1299    2022
1300    2022
1301    2022
1302    2022
1303    2022
1304    2022
1305    2022
1306    2022
1307    2022
1308    2022
1309    2018
1310    2018
1311    2018
1312    2018
1313    2018
1314    2018
1315    2018
1316    2018
1317    2018
1318    2018
1319    2018
1320    2018
1321    2018
1322    2018
1323    2018
1324    2018
1325    2018
1326    2018
1327    2018
1328    2018
1329    2018
1330    2018
1331    2018
1332    2018
1333    2018
1334    2018
1335    2018
1336    2018
1337    2018
1338    2018
1339    2018
1340    2018
1341    2018
1342    2018
1343    2018
1344    2018
1345    2018
1346    2018
1347    2018
1348    2018
1349    2018
1350    2018
1351    2018
1352    2018
1353    2019
1354    2019
1355    2019
1356    2019
1357    2019
1358    2019
1359    2019
1360    2019
1361    2019
1362    2019
1363    2019
1364    2019
1365    2019
1366    2019
1367    2019
1368    2019
1369    2019
1370    2019
1371    2019
1372    2019
1373    2019
1374    2019
1375    2019
1376    2019
1377    2019
1378    2019
1379    2019
1380    2019
1381    2019
1382    2019
1383    2019
1384    2019
1385    2019
1386    2019
1387    2019
1388    2019
1389    2019
1390    2019
1391    2019
1392    2019
1393    2019
1394    2019
1395    2019
1396    2019
1397    2020
1398    2020
1399    2020
1400    2020
1401    2020
1402    2020
1403    2020
1404    2020
1405    2020
1406    2020
1407    2020
1408    2020
1409    2020
1410    2020
1411    2020
1412    2020
1413    2020
1414    2020
1415    2020
1416    2020
1417    2020
1418    2020
1419    2020
1420    2020
1421    2020
1422    2020
1423    2020
1424    2020
1425    2020
1426    2020
1427    2020
1428    2020
1429    2020
1430    2020
1431    2020
1432    2020
1433    2020
1434    2020
1435    2020
1436    2020
1437    2020
1438    2020
1439    2020
1440    2020
1441    2021
1442    2021
1443    2021
1444    2021
1445    2021
1446    2021
1447    2021
1448    2021
1449    2021
1450    2021
1451    2021
1452    2021
1453    2021
1454    2021
1455    2021
1456    2021
1457    2021
1458    2021
1459    2021
1460    2021
1461    2021
1462    2021
1463    2021
1464    2021
1465    2021
1466    2021
1467    2021
1468    2021
1469    2021
1470    2021
1471    2021
1472    2021
1473    2021
1474    2021
1475    2021
1476    2021
1477    2021
1478    2021
1479    2021
1480    2021
1481    2021
1482    2021
1483    2021
1484    2021
1485    2022
1486    2022
1487    2022
1488    2022
1489    2022
1490    2022
1491    2022
1492    2022
1493    2022
1494    2022
1495    2022
1496    2018
1497    2018
1498    2018
1499    2018
1500    2018
1501    2018
1502    2018
1503    2018
1504    2018
1505    2018
1506    2018
1507    2018
1508    2018
1509    2018
1510    2018
1511    2018
1512    2018
1513    2018
1514    2018
1515    2018
1516    2018
1517    2018
1518    2018
1519    2018
1520    2018
1521    2018
1522    2018
1523    2018
1524    2018
1525    2018
1526    2018
1527    2018
1528    2018
1529    2018
1530    2018
1531    2018
1532    2018
1533    2018
1534    2018
1535    2018
1536    2018
1537    2018

In [242]:
# Most users are from which state
most_users = agg_user.groupby('State')['User_count'].sum().reset_index()
most_users.sort_values(by='User_count', ascending=False)

                                       State  User_count
20                               Maharashtra   452075011
33                             Uttar Pradesh   355969633
15                                 Karnataka   291372780
1                             Andhra Pradesh   225414835
28                                 Rajasthan   215645588
31                                 Telangana   211907753
35                               West Bengal   206129775
30                                Tamil Nadu   193665028
10                                   Gujarat   180731308
19                            Madhya Pradesh   180662446
4                                      Bihar   167266170
8                                      Delhi   133679039
11                                   Haryana   121872882
25                                    Odisha   114580607
16                                    Kerala    76662576
27                                    Punjab    66429452
14                                 Jharkhand    64541996
6                               Chhattisgarh    54136914
3                                      Assam    39481411
34                               Uttarakhand    34161100
12                          Himachal Pradesh    19411836
13                           Jammu & Kashmir    14122428
9                                        Goa     6844584
5                                 Chandigarh     5335570
32                                   Tripura     5299920
26                                Puducherry     4052989
7   Dadra and Nagar Haveli and Daman and Diu     3896519
21                                   Manipur     3479129
2                          Arunachal Pradesh     2805570
24                                  Nagaland     2218657
22                                 Meghalaya     2155644
29                                    Sikkim     1870915
23                                   Mizoram      929959
17                                    Ladakh      840584
0                          Andaman & Nicobar      623446
18                               Lakshadweep       51138

In [243]:
usr_trnd = agg_user.groupby(['Year','Quarter'])['User_count'].sum().reset_index()
usr_trnd

    Year  Quarter  User_count
0   2018        1    46877653
1   2018        2    63648009
2   2018        3    80010589
3   2018        4   102261621
4   2019        1   123432188
5   2019        2   141807654
6   2019        3   159293319
7   2019        4   178278417
8   2020        1   197574459
9   2020        2   218995596
10  2020        3   241168896
11  2020        4   264270434
12  2021        1   284984511
13  2021        2   305257101
14  2021        3   328353856
15  2021        4   351160262
16  2022        1   372950627

In [244]:
# import pandas as pd
# import json
# import os

# df = df_grp_agg_user

# fig = px.choropleth(
#     df,
#     geojson="https://gist.githubusercontent.com/jbrobst/56c13bbbf9d97d187fea01ca62ea5112/raw/e388c4cae20aa53cb5090210a42ebb9b765c0a36/india_states.geojson",
#     featureidkey='properties.ST_NM',
#     locations='State',
#     color='User_count',
#     color_continuous_scale='Oranges'
# )

# fig.update_geos(fitbounds="locations", visible=False)
# fig.update_layout(title_text='Agg Users by State in India')

# fig.show()

In [245]:
import os
path = "D:/Movies/Guvi_2/PhonePe/phonepe-pulse/data/map/transaction/hover/country/india/state/"


map_tran_list = os.listdir(path)
map_tran_list

#<------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------>#

#This is to extract the data's to create a dataframe

clm={'State':[], 'Year':[],'Quater':[],'Transaction_type':[], 'Transaction_count':[], 'Transaction_amount':[]}

for i in map_tran_list:
    p_i=path+i+"/"
    map_yr=os.listdir(p_i)
    for j in map_yr:
        p_j=p_i+j+"/"
        map_yr_list=os.listdir(p_j)
        for k in map_yr_list:
            p_k=p_j+k
            Data=open(p_k,'r')
            D=json.load(Data)
            for z in D['data']['hoverDataList']:
              Name=z['name']
              count=z['metric'][0]['count']
              amount=z['metric'][0]['amount']
              clm['Transaction_type'].append(Name)
              clm['Transaction_count'].append(count)
              clm['Transaction_amount'].append(amount)
              clm['State'].append(i)
              clm['Year'].append(j)
              clm['Quater'].append(int(k.strip('.json')))
#Succesfully created a dataframe
map_trans=pd.DataFrame(clm)

In [246]:
map_trans.head(15)

,State,Year,Quater,Transaction_type,Transaction_count,Transaction_amount
0,andaman-&-nicobar-islands,2018,1,north and middle andaman district,442,9.316631e+05
1,andaman-&-nicobar-islands,2018,1,south andaman district,5688,1.256025e+07
2,andaman-&-nicobar-islands,2018,1,nicobars district,528,1.139849e+06
3,andaman-&-nicobar-islands,2018,2,north and middle andaman district,825,1.317863e+06
4,andaman-&-nicobar-islands,2018,2,south andaman district,9395,2.394824e+07
5,andaman-&-nicobar-islands,2018,2,nicobars district,1120,3.072437e+06
6,andaman-&-nicobar-islands,2018,3,north and middle andaman district,1283,4.901530e+06
7,andaman-&-nicobar-islands,2018,3,south andaman district,13511,4.426811e+07
8,andaman-&-nicobar-islands,2018,3,nicobars district,1471,6.387829e+06
9,andaman-&-nicobar-islands,2018,4,north and middle andaman district,2137,7.955636e+06
10,andaman-&-nicobar-islands,2018,4,south andaman district,20136,7.541184e+07
11,andaman-&-nicobar-islands,2018,4,nicobars district,1485,7.180859e+06
12,andaman-&-nicobar-islands,2019,1,north and middle andaman district,3264,9.561709e+06
13,andaman-&-nicobar-islands,2019,1,south andaman district,25683,8.550197e+07
14,andaman-&-nicobar-islands,2019,1,nicobars district,1539,7.236060e+06

In [247]:
import re
def modify(s):
    s = s.replace('-', ' ')
    return ' '.join(word.capitalize() for word in s.split())

map_trans['State'] = map_trans['State'].apply(modify)
map_trans['Transaction_type'] = map_trans['Transaction_type'].apply(modify)

update_cat = {
    "Andaman & Nicobar Islands": "Andaman & Nicobar",
    "Dadra & Nagar Haveli & Daman & Diu": "Dadra and Nagar Haveli and Daman and Diu"
}

map_trans['State'] = map_trans['State'].replace(update_cat)

In [248]:
map_trans.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20604 entries, 0 to 20603
Data columns (total 6 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   State               20604 non-null  object
 1   Year                20604 non-null  object
 2   Quater              20604 non-null  int64
 3   Transaction_type    20604 non-null  object
 4   Transaction_count   20604 non-null  int64
 5   Transaction_amount  20604 non-null  float64
dtypes: float64(1), int64(2), object(3)
memory usage: 965.9+ KB

In [249]:
map_trans['Year'] = pd.to_datetime(map_trans['Year']).dt.year

map_trans['Year'].info()
map_trans['Year']

<class 'pandas.core.series.Series'>
RangeIndex: 20604 entries, 0 to 20603
Series name: Year
Non-Null Count  Dtype
--------------  -----
20604 non-null  int32
dtypes: int32(1)
memory usage: 80.6 KB

0        2018
1        2018
2        2018
3        2018
4        2018
5        2018
6        2018
7        2018
8        2018
9        2018
10       2018
11       2018
12       2019
13       2019
14       2019
15       2019
16       2019
17       2019
18       2019
19       2019
20       2019
21       2019
22       2019
23       2019
24       2020
25       2020
26       2020
27       2020
28       2020
29       2020
30       2020
31       2020
32       2020
33       2020
34       2020
35       2020
36       2021
37       2021
38       2021
39       2021
40       2021
41       2021
42       2021
43       2021
44       2021
45       2021
46       2021
47       2021
48       2022
49       2022
50       2022
51       2022
52       2022
53       2022
54       2022
55       2022
56       2022
57       2022
58       2022
59       2022
60       2023
61       2023
62       2023
63       2023
64       2023
65       2023
66       2023
67       2023
68       2023
69       2023
70       2023
71       2023
72       2024
73       2024
74       2024
75       2024
76       2024
77       2024
78       2024
79       2024
80       2024
81       2024
82       2024
83       2024
84       2018
85       2018
86       2018
87       2018
88       2018
89       2018
90       2018
91       2018
92       2018
93       2018
94       2018
95       2018
96       2018
97       2018
98       2018
99       2018
100      2018
101      2018
102      2018
103      2018
104      2018
105      2018
106      2018
107      2018
108      2018
109      2018
110      2018
111      2018
112      2018
113      2018
114      2018
115      2018
116      2018
117      2018
118      2018
119      2018
120      2018
121      2018
122      2018
123      2018
124      2018
125      2018
126      2018
127      2018
128      2018
129      2018
130      2018
131      2018
132      2018
133      2018
134      2018
135      2018
136      2019
137      2019
138      2019
139      2019
140      2019
141      2019
142      2019
143      2019
144      2019
145      2019
146      2019
147      2019
148      2019
149      2019
150      2019
151      2019
152      2019
153      2019
154      2019
155      2019
156      2019
157      2019
158      2019
159      2019
160      2019
161      2019
162      2019
163      2019
164      2019
165      2019
166      2019
167      2019
168      2019
169      2019
170      2019
171      2019
172      2019
173      2019
174      2019
175      2019
176      2019
177      2019
178      2019
179      2019
180      2019
181      2019
182      2019
183      2019
184      2019
185      2019
186      2019
187      2019
188      2020
189      2020
190      2020
191      2020
192      2020
193      2020
194      2020
195      2020
196      2020
197      2020
198      2020
199      2020
200      2020
201      2020
202      2020
203      2020
204      2020
205      2020
206      2020
207      2020
208      2020
209      2020
210      2020
211      2020
212      2020
213      2020
214      2020
215      2020
216      2020
217      2020
218      2020
219      2020
220      2020
221      2020
222      2020
223      2020
224      2020
225      2020
226      2020
227      2020
228      2020
229      2020
230      2020
231      2020
232      2020
233      2020
234      2020
235      2020
236      2020
237      2020
238      2020
239      2020
240      2021
241      2021
242      2021
243      2021
244      2021
245      2021
246      2021
247      2021
248      2021
249      2021
250      2021
251      2021
252      2021
253      2021
254      2021
255      2021
256      2021
257      2021
258      2021
259      2021
260      2021
261      2021
262      2021
263      2021
264      2021
265      2021
266      2021
267      2021
268      2021
269      2021
270      2021
271      2021
272      2021
273      2021
274      2021
275      2021
276      2021
277      2021
278      2021
279      2021
280      2021
281      2021
282      2021
283      2021
284      2021
285      2021
286      2021
287      2021
288      2021
289      2021
290      2021
291      2021
292      2022
293      2022
294      2022
295      2022
296      2022
297      2022
298      2022
299      2022
300      2022
301      2022
302      2022
303      2022
304      2022
305      2022
306      2022
307      2022
308      2022
309      2022
310      2022
311      2022
312      2022
313      2022
314      2022
315      2022
316      2022
317      2022
318      2022
319      2022
320      2022
321      2022
322      2022
323      2022
324      2022
325      2022
326      2022
327      2022
328      2022
329      2022
330      2022
331      2022
332      2022
333      2022
334      2022
335      2022
336      2022
337      2022
338      2022
339      2022
340      2022
341      2022
342      2022
343      2022
344      2023
345      2023
346      2023
347      2023
348      2023
349      2023
350      2023
351      2023
352      2023
353      2023
354      2023
355      2023
356      2023
357      2023
358      2023
359      2023
360      2023
361      2023
362      2023
363      2023
364      2023
365      2023
366      2023
367      2023
368      2023
369      2023
370      2023
371      2023
372      2023
373      2023
374      2023
375      2023
376      2023
377      2023
378      2023
379      2023
380      2023
381      2023
382      2023
383      2023
384      2023
385      2023
386      2023
387      2023
388      2023
389      2023
390      2023
391      2023
392      2023
393      2023
394      2023
395      2023
396      2024
397      2024
398      2024
399      2024
400      2024
401      2024
402      2024
403      2024
404      2024
405      2024
406      2024
407      2024
408      2024
409      2024
410      2024
411      2024
412      2024
413      2024
414      2024
415      2024
416      2024
417      2024
418      2024
419      2024
420      2024
421      2024
422      2024
423      2024
424      2024
425      2024
426      2024
427      2024
428      2024
429      2024
430      2024
431      2024
432      2024
433      2024
434      2024
435      2024
436      2024
437      2024
438      2024
439      2024
440      2024
441      2024
442      2024
443      2024
444      2024
445      2024
446      2024
447      2024
448      2024
449      2024
450      2024
451      2024
452      2024
453      2024
454      2024
455      2024
456      2024
457      2024
458      2024
459      2024
460      2024
461      2024
462      2024
463      2024
464      2024
465      2024
466      2024
467      2024
468      2024
469      2024
470      2024
471      2024
472      2024
473      2024
474      2018
475      2018
476      2018
477      2018
478      2018
479      2018
480      2018
481      2018
482      2018
483      2018
484      2018
485      2018
486      2018
487      2018
488      2018
489      2018
490      2018
491      2018
492      2018
493      2018
494      2018
495      2018
496      2018
497      2018
498      2018
499      2018
500      2018
501      2018
502      2018
503      2018
504      2018
505      2018
506      2018
507      2018
508      2018
509      2018
510      2018
511      2018
512      2018
513      2018
514      2018
515      2018
516      2018
517      2018
518      2018
519      2018
520      2018
521      2018
522      2018
523      2018
524      2018
525      2018
526      2018
527      2018
528      2018
529      2018
530      2018
531      2018
532      2018
533      2018
534      2018
535      2018
536      2018
537      2018
538      2018
539      2018
540      2018
541      2018
542      2018
543      2018
544      2018
545      2018
546      2018
547      2018
548      2018
549      2018
550      2018
551      2018
552      2018
553      2018
554      2018
555      2018
556      2018
557      2018
558      2018
559      2018
560      2018
561      2018
562      2018
563      2018
564      2018
565      2018
566      2018
567      2018
568      2018
569      2018
570      2019
571      2019
572      2019
573      2019
574      2019
575      2019
576      2019
577      2019
578      2019
579      2019
580      2019
581      2019
582      2019
583      2019
584      2019
585      2019
586      2019
587      2019
588      2019
589      2019
590      2019
591      2019
592      2019
593      2019
594      2019
595      2019
596      2019
597      2019
598      2019
599      2019
600      2019
601      2019
602      2019
603      2019
604      2019
605      2019
606      2019
607      2019
608      2019
609      2019
610      2019
611      2019
612      2019
613      2019
614      2019
615      2019
616      2019
617      2019
618      2019
619      2019
620      2019
621      2019
622      2019
623      2019
624      2019
625      2019
626      2019
627      2019
628      2019
629      2019
630      2019
631      2019
632      2019
633      2019
634      2019
635      2019
636      2019
637      2019
638      2019
639      2019
640      2019
641      2019
642      2019
643      2019
644      2019
645      2019
646      2019
647      2019
648      2019
649      2019
650      2019
651      2019
652      2019
653      2019
654      2019
655      2019
656      2019
657      2019
658      2019
659      2019
660      2019
661      2019
662      2019
663      2019
664      2019
665      2019
666      2019
667      2019
668      2019
669      2019
670      2020
671      2020
672      2020
673      2020
674      2020
675      2020
676      2020
677      2020
678      2020
679      2020
680      2020
681      2020
682      2020
683      2020
684      2020
685      2020
686      2020
687      2020
688      2020
689      2020
690      2020
691      2020
692      2020
693      2020
694      2020
695      2020
696      2020
697      2020
698      2020
699      2020
700      2020
701      2020
702      2020
703      2020
704      2020
705      2020
706      2020
707      2020
708      2020
709      2020
710      2020
711      2020
712      2020
713      2020
714      2020
715      2020
716      2020
717      2020
718      2020
719      2020
720      2020
721      2020
722      2020
723      2020
724      2020
725      2020
726      2020
727      2020
728      2020
729      2020
730      2020
731      2020
732      2020
733      2020
734      2020
735      2020
736      2020
737      2020
738      2020
739      2020
740      2020
741      2020
742      2020
743      2020
744      2020
745      2020
746      2020
747      2020
748      2020
749      2020
750      2020
751      2020
752      2020
753      2020
754      2020
755      2020
756      2020
757      2020
758      2020
759      2020
760      2020
761      2020
762      2020
763      2020
764      2020
765      2020
766      2020
767      2020
768      2020
769      2020
770      2021
771      2021
772      2021
773      2021
774      2021
775      2021
776      2021
777      2021
778      2021
779      2021
780      2021
781      2021
782      2021
783      2021
784      2021
785      2021
786      2021
787      2021
788      2021
789      2021
790      2021
791      2021
792      2021
793      2021
794      2021
795      2021
796      2021
797      2021
798      2021
799      2021
800      2021
801      2021
802      2021
803      2021
804      2021
805      2021
806      2021
807      2021
808      2021
809      2021
810      2021
811      2021
812      2021
813      2021
814      2021
815      2021
816      2021
817      2021
818      2021
819      2021
820      2021
821      2021
822      2021
823      2021
824      2021
825      2021
826      2021
827      2021
828      2021
829      2021
830      2021
831      2021
832      2021
833      2021
834      2021
835      2021
836      2021
837      2021
838      2021
839      2021
840      2021
841      2021
842      2021
843      2021
844      2021
845      2021
846      2021
847      2021
848      2021
849      2021
850      2021
851      2021
852      2021
853      2021
854      2021
855      2021
856      2021
857      2021
858      2021
859      2021
860      2021
861      2021
862      2021
863      2021
864      2021
865      2021
866      2021
867      2021
868      2021
869      2021
870      2022
871      2022
872      2022
873      2022
874      2022
875      2022
876      2022
877      2022
878      2022
879      2022
880      2022
881      2022
882      2022
883      2022
884      2022
885      2022
886      2022
887      2022
888      2022
889      2022
890      2022
891      2022
892      2022
893      2022
894      2022
895      2022
896      2022
897      2022
898      2022
899      2022
900      2022
901      2022
902      2022
903      2022
904      2022
905      2022
906      2022
907      2022
908      2022
909      2022
910      2022
911      2022
912      2022
913      2022
914      2022
915      2022
916      2022
917      2022
918      2022
919      2022
920      2022
921      2022
922      2022
923      2022
924      2022
925      2022
926      2022
927      2022
928      2022
929      2022
930      2022
931      2022
932      2022
933      2022
934      2022
935      2022
936      2022
937      2022
938      2022
939      2022
940      2022
941      2022
942      2022
943      2022
944      2022
945      2022
946      2022
947      2022
948      2022
949      2022
950      2022
951      2022
952      2022
953      2022
954      2022
955      2022
956      2022
957      2022
958      2022
959      2022
960      2022
961      2022
962      2022
963      2022
964      2022
965      2022
966      2022
967      2022
968      2022
969      2022
970      2023
971      2023
972      2023
973      2023
974      2023
975      2023
976      2023
977      2023
978      2023
979      2023
980      2023
981      2023
982      2023
983      2023
984      2023
985      2023
986      2023
987      2023
988      2023
989      2023
990      2023
991      2023
992      2023
993      2023
994      2023
995      2023
996      2023
997      2023
998      2023
999      2023
1000     2023
1001     2023
1002     2023
1003     2023
1004     2023
1005     2023
1006     2023
1007     2023
1008     2023
1009     2023
1010     2023
1011     2023
1012     2023
1013     2023
1014     2023
1015     2023
1016     2023
1017     2023
1018     2023
1019     2023
1020     2023
1021     2023
1022     2023
1023     2023
1024     2023
1025     2023
1026     2023
1027     2023
1028     2023
1029     2023
1030     2023
1031     2023
1032     2023
1033     2023
1034     2023
1035     2023
1036     2023
1037     2023
1038     2023
1039     2023
1040     2023
1041     2023
1042     2023
1043     2023
1044     2023
1045     2023
1046     2023
1047     2023
1048     2023
1049     2023
1050     2023
1051     2023
1052     2023
1053     2023
1054     2023
1055     2023
1056     2023
1057     2023
1058     2023
1059     2023
1060     2023
1061     2023
1062     2023
1063     2023
1064     2023
1065     2023
1066     2023
1067     2023
1068     2023
1069     2023
1070     2024
1071     2024
1072     2024
1073     2024
1074     2024
1075     2024
1076     2024
1077     2024
1078     2024
1079     2024
1080     2024
1081     2024
1082     2024
1083     2024
1084     2024
1085     2024
1086     2024
1087     2024
1088     2024
1089     2024
1090     2024
1091     2024
1092     2024
1093     2024
1094     2024
1095     2024
1096     2024
1097     2024
1098     2024
1099     2024
1100     2024
1101     2024
1102     2024
1103     2024
1104     2024
1105     2024
1106     2024
1107     2024
1108     2024
1109     2024
1110     2024
1111     2024
1112     2024
1113     2024
1114     2024
1115     2024
1116     2024
1117     2024
1118     2024
1119     2024
1120     2024
1121     2024
1122     2024
1123     2024
1124     2024
1125     2024
1126     2024
1127     2024
1128     2024
1129     2024
1130     2024
1131     2024
1132     2024
1133     2024
1134     2024
1135     2024
1136     2024
1137     2024
1138     2024
1139     2024
1140     2024
1141     2024
1142     2024
1143     2024
1144     2024
1145     2024
1146     2024
1147     2024
1148     2024
1149     2024
1150     2024
1151     2024
1152     2024
1153     2024
1154     2024
1155     2024
1156     2024
1157     2024
1158     2024
1159     2024
1160     2024
1161     2024
1162     2024
1163     2024
1164     2024
1165     2024
1166     2024
1167     2024
1168     2024
1169     2024
1170     2024
1171     2024
1172     2018
1173     2018
1174     2018
1175     2018
1176     2018
1177     2018
1178     2018
1179     2018
1180     2018
1181     2018
1182     2018
1183     2018
1184     2018
1185     2018
1186     2018
1187     2018
1188     2018
1189     2018
1190     2018
1191     2018
1192     2018
1193     2018
1194     2018
1195     2018
1196     2018
1197     2018
1198     2018
1199     2018
1200     2018
1201     2018
1202     2018
1203     2018
1204     2018
1205     2018
1206     2018
1207     2018
1208     2018
1209     2018
1210     2018
1211     2018
1212     2018
1213     2018
1214     2018
1215     2018
1216     2018
1217     2018
1218     2018
1219     2018
1220     2018
1221     2018
1222     2018
1223     2018
1224     2018
1225     2018
1226     2018
1227     2018
1228     2018
1229     2018
1230     2018
1231     2018
1232     2018
1233     2018
1234     2018
1235     2018
1236     2018
1237     2018
1238     2018
1239     2018
1240     2018
1241     2018
1242     2018
1243     2018
1244     2018
1245     2018
1246     2018
1247     2018
1248     2018
1249     2018
1250     2018
1251     2018
1252     2018
1253     2018
1254     2018
1255     2018
1256     2018
1257     2018
1258     2018
1259     2018
1260     2018
1261     2018
1262     2018
1263     2018
1264     2018
1265     2018
1266     2018
1267     2018
1268     2018
1269     2018
1270     2018
1271     2018
1272     2018
1273     2018
1274     2018
1275     2018
1276     2018
1277     2018
1278     2018
1279     2018
1280     2018
1281     2018
1282     2018
1283     2018
1284     2018
1285     2018
1286     2018
1287     2018
1288     2018
1289     2018
1290     2018
1291     2018
1292     2018
1293     2018
1294     2018
1295     2018
1296     2018
1297     2018
1298     2018
1299     2018
1300     2018
1301     2018
1302     2018
1303     2018
1304     2019
1305     2019
1306     2019
1307     2019
1308     2019
1309     2019
1310     2019
1311     2019
1312     2019
1313     2019
1314     2019
1315     2019
1316     2019
1317     2019
1318     2019
1319     2019
1320     2019
1321     2019
1322     2019
1323     2019
1324     2019
1325     2019
1326     2019
1327     2019
1328     2019
1329     2019
1330     2019
1331     2019
1332     2019
1333     2019
1334     2019
1335     2019
1336     2019
1337     2019
1338     2019
1339     2019
1340     2019
1341     2019
1342     2019
1343     2019
1344     2019
1345     2019
1346     2019
1347     2019
1348     2019
1349     2019
1350     2019
1351     2019
1352     2019
1353     2019
1354     2019
1355     2019
1356     2019
1357     2019
1358     2019
1359     2019
1360     2019
1361     2019
1362     2019
1363     2019
1364     2019
1365     2019
1366     2019
1367     2019
1368     2019
1369     2019
1370     2019
1371     2019
1372     2019
1373     2019
1374     2019
1375     2019
1376     2019
1377     2019
1378     2019
1379     2019
1380     2019
1381     2019
1382     2019
1383     2019
1384     2019
1385     2019
1386     2019
1387     2019
1388     2019
1389     2019
1390     2019
1391     2019
1392     2019
1393     2019
1394     2019
1395     2019
1396     2019
1397     2019
1398     2019
1399     2019
1400     2019
1401     2019
1402     2019
1403     2019
1404     2019
1405     2019
1406     2019
1407     2019
1408     2019
1409     2019
1410     2019
1411     2019
1412     2019
1413     2019
1414     2019
1415     2019
1416     2019
1417     2019
1418     2019
1419     2019
1420     2019
1421     2019
1422     2019
1423     2019
1424     2019
1425     2019
1426     2019
1427     2019

In [250]:
df_grp_map_trans= map_trans.groupby('State')['Transaction_count'].sum().reset_index()
df_grp_map_trans.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 36 entries, 0 to 35
Data columns (total 2 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   State              36 non-null     object
 1   Transaction_count  36 non-null     int64
dtypes: int64(1), object(1)
memory usage: 708.0+ bytes

In [251]:
import pandas as pd
import json
import os

df = df_grp_map_trans

fig = px.choropleth(
    df,
    geojson="https://gist.githubusercontent.com/jbrobst/56c13bbbf9d97d187fea01ca62ea5112/raw/e388c4cae20aa53cb5090210a42ebb9b765c0a36/india_states.geojson",
    featureidkey='properties.ST_NM',
    locations='State',
    color='Transaction_count',
    color_continuous_scale='Burg'
)

fig.update_geos(fitbounds="locations", visible=False)
fig.update_layout(title_text='Insurance Transactions by State in India')

fig.show()

In [252]:
#MAP INsURANCE

In [253]:
import os
path = "D:/Movies/Guvi_2/PhonePe/phonepe-pulse/data/map/insurance/hover/country/india/state/"

map_ins_list=os.listdir(path)
map_ins_list
#Agg_state_list--> to get the list of states in India

#<------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------>#

#This is to extract the data's to create a dataframe

clm={'State':[], 'Year':[],'Quater':[],'District':[], 'Transaction_count':[]}

for i in map_ins_list:
    p_i=path+i+"/"
    map_yr=os.listdir(p_i)
    for j in map_yr:
        p_j=p_i+j+"/"
        map_yr_list=os.listdir(p_j)
        for k in map_yr_list:
            p_k=p_j+k
            Data=open(p_k,'r')
            D=json.load(Data)
            for z in D['data']['hoverDataList']:
              Name=z['name']
              count=z['metric'][0]['count']
              clm['District'].append(Name)
              clm['Transaction_count'].append(count)
              clm['State'].append(i)
              clm['Year'].append(j)
              clm['Quater'].append(int(k.strip('.json')))
#Succesfully created a dataframe
map_ins=pd.DataFrame(clm)

In [254]:
map_ins.head()

,State,Year,Quater,District,Transaction_count
0,andaman-&-nicobar-islands,2020,2,south andaman district,3
1,andaman-&-nicobar-islands,2020,2,nicobars district,3
2,andaman-&-nicobar-islands,2020,3,north and middle andaman district,1
3,andaman-&-nicobar-islands,2020,3,south andaman district,35
4,andaman-&-nicobar-islands,2020,3,nicobars district,5

In [255]:
import re
def modify(s):
    s = s.replace('-', ' ')
    return ' '.join(word.capitalize() for word in s.split())

map_ins['State'] = map_ins['State'].apply(modify)
map_ins['District'] = map_ins['District'].apply(modify)

update_cat = {
    "Andaman & Nicobar Islands": "Andaman & Nicobar",
    "Dadra & Nagar Haveli & Daman & Diu": "Dadra and Nagar Haveli and Daman and Diu"
}

map_ins['State'] = map_ins['State'].replace(update_cat)

In [256]:
map_trans.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20604 entries, 0 to 20603
Data columns (total 6 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   State               20604 non-null  object
 1   Year                20604 non-null  int32
 2   Quater              20604 non-null  int64
 3   Transaction_type    20604 non-null  object
 4   Transaction_count   20604 non-null  int64
 5   Transaction_amount  20604 non-null  float64
dtypes: float64(1), int32(1), int64(2), object(2)
memory usage: 885.5+ KB

In [257]:
df_grp_map_ins = map_ins.groupby('State')['Transaction_count'].sum().reset_index()
df_grp_map_ins.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 36 entries, 0 to 35
Data columns (total 2 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   State              36 non-null     object
 1   Transaction_count  36 non-null     int64
dtypes: int64(1), object(1)
memory usage: 708.0+ bytes

In [258]:
import pandas as pd
import json
import os

df = df_grp_map_ins

fig = px.choropleth(
    df,
    geojson="https://gist.githubusercontent.com/jbrobst/56c13bbbf9d97d187fea01ca62ea5112/raw/e388c4cae20aa53cb5090210a42ebb9b765c0a36/india_states.geojson",
    featureidkey='properties.ST_NM',
    locations='State',
    color='Transaction_count',
    color_continuous_scale='Aggrnyl'
)

fig.update_geos(fitbounds="locations", visible=False)
fig.update_layout(title_text='Map Insurance Transactions by State in India')

fig.show()

In [259]:
#

In [260]:
import os
import json
import pandas as pd

path = "D:/Movies/Guvi_2/PhonePe/phonepe-pulse/data/map/user/hover/country/india/state/"


map_user_list = os.listdir(path)
map_user_list

# <------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------> #
# This is to extract the data's to create a dataframe

clm = {
    'State': [],
    'Year': [],
    'Quarter': [],
    'District': [],
    'Registered_users': [],
    'App_opens': []
}

for i in map_user_list:                
    p_i = path + i + "/"
    user_yr = os.listdir(p_i)
    
    for j in user_yr:                  
        p_j = p_i + j + "/"
        user_yr_list = os.listdir(p_j)
        
        for k in user_yr_list:         
            p_k = p_j + k
            
            with open(p_k, 'r') as Data:
                D = json.load(Data)

                # 🔒 SAFE ACCESS
                hover_data = D['data'].get('hoverData')

                # Skip if data is missing
                if hover_data is None:
                    continue

                for district, metrics in hover_data.items():
                    users = metrics['registeredUsers']
                    opens = metrics['appOpens']

                    clm['District'].append(district)
                    clm['Registered_users'].append(users)
                    clm['App_opens'].append(opens)
                    clm['State'].append(i)
                    clm['Year'].append(j)
                    clm['Quarter'].append(int(k.strip('.json')))

map_user_list = pd.DataFrame(clm)

map_user_list.head()

,State,Year,Quarter,District,Registered_users,App_opens
0,andaman-&-nicobar-islands,2018,1,north and middle andaman district,632,0
1,andaman-&-nicobar-islands,2018,1,south andaman district,5846,0
2,andaman-&-nicobar-islands,2018,1,nicobars district,262,0
3,andaman-&-nicobar-islands,2018,2,north and middle andaman district,911,0
4,andaman-&-nicobar-islands,2018,2,south andaman district,8143,0

In [261]:
import re
def modify(s):
    s = s.replace('-', ' ')
    return ' '.join(word.capitalize() for word in s.split())

map_user_list['State'] = map_user_list['State'].apply(modify)
map_user_list['District'] = map_user_list['District'].apply(modify)


update_cat = {
    "Andaman & Nicobar Islands": "Andaman & Nicobar",
    "Dadra & Nagar Haveli & Daman & Diu": "Dadra and Nagar Haveli and Daman and Diu"
}

map_user_list['State'] = map_user_list['State'].replace(update_cat)

In [262]:
map_user_list.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20608 entries, 0 to 20607
Data columns (total 6 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   State             20608 non-null  object
 1   Year              20608 non-null  object
 2   Quarter           20608 non-null  int64
 3   District          20608 non-null  object
 4   Registered_users  20608 non-null  int64
 5   App_opens         20608 non-null  int64
dtypes: int64(3), object(3)
memory usage: 966.1+ KB

In [263]:
map_user_list['Year'] = pd.to_datetime(map_user_list['Year']).dt.year

map_user_list['Year'].info()
map_user_list['Year']

<class 'pandas.core.series.Series'>
RangeIndex: 20608 entries, 0 to 20607
Series name: Year
Non-Null Count  Dtype
--------------  -----
20608 non-null  int32
dtypes: int32(1)
memory usage: 80.6 KB

0        2018
1        2018
2        2018
3        2018
4        2018
5        2018
6        2018
7        2018
8        2018
9        2018
10       2018
11       2018
12       2019
13       2019
14       2019
15       2019
16       2019
17       2019
18       2019
19       2019
20       2019
21       2019
22       2019
23       2019
24       2020
25       2020
26       2020
27       2020
28       2020
29       2020
30       2020
31       2020
32       2020
33       2020
34       2020
35       2020
36       2021
37       2021
38       2021
39       2021
40       2021
41       2021
42       2021
43       2021
44       2021
45       2021
46       2021
47       2021
48       2022
49       2022
50       2022
51       2022
52       2022
53       2022
54       2022
55       2022
56       2022
57       2022
58       2022
59       2022
60       2023
61       2023
62       2023
63       2023
64       2023
65       2023
66       2023
67       2023
68       2023
69       2023
70       2023
71       2023
72       2024
73       2024
74       2024
75       2024
76       2024
77       2024
78       2024
79       2024
80       2024
81       2024
82       2024
83       2024
84       2018
85       2018
86       2018
87       2018
88       2018
89       2018
90       2018
91       2018
92       2018
93       2018
94       2018
95       2018
96       2018
97       2018
98       2018
99       2018
100      2018
101      2018
102      2018
103      2018
104      2018
105      2018
106      2018
107      2018
108      2018
109      2018
110      2018
111      2018
112      2018
113      2018
114      2018
115      2018
116      2018
117      2018
118      2018
119      2018
120      2018
121      2018
122      2018
123      2018
124      2018
125      2018
126      2018
127      2018
128      2018
129      2018
130      2018
131      2018
132      2018
133      2018
134      2018
135      2018
136      2019
137      2019
138      2019
139      2019
140      2019
141      2019
142      2019
143      2019
144      2019
145      2019
146      2019
147      2019
148      2019
149      2019
150      2019
151      2019
152      2019
153      2019
154      2019
155      2019
156      2019
157      2019
158      2019
159      2019
160      2019
161      2019
162      2019
163      2019
164      2019
165      2019
166      2019
167      2019
168      2019
169      2019
170      2019
171      2019
172      2019
173      2019
174      2019
175      2019
176      2019
177      2019
178      2019
179      2019
180      2019
181      2019
182      2019
183      2019
184      2019
185      2019
186      2019
187      2019
188      2020
189      2020
190      2020
191      2020
192      2020
193      2020
194      2020
195      2020
196      2020
197      2020
198      2020
199      2020
200      2020
201      2020
202      2020
203      2020
204      2020
205      2020
206      2020
207      2020
208      2020
209      2020
210      2020
211      2020
212      2020
213      2020
214      2020
215      2020
216      2020
217      2020
218      2020
219      2020
220      2020
221      2020
222      2020
223      2020
224      2020
225      2020
226      2020
227      2020
228      2020
229      2020
230      2020
231      2020
232      2020
233      2020
234      2020
235      2020
236      2020
237      2020
238      2020
239      2020
240      2021
241      2021
242      2021
243      2021
244      2021
245      2021
246      2021
247      2021
248      2021
249      2021
250      2021
251      2021
252      2021
253      2021
254      2021
255      2021
256      2021
257      2021
258      2021
259      2021
260      2021
261      2021
262      2021
263      2021
264      2021
265      2021
266      2021
267      2021
268      2021
269      2021
270      2021
271      2021
272      2021
273      2021
274      2021
275      2021
276      2021
277      2021
278      2021
279      2021
280      2021
281      2021
282      2021
283      2021
284      2021
285      2021
286      2021
287      2021
288      2021
289      2021
290      2021
291      2021
292      2022
293      2022
294      2022
295      2022
296      2022
297      2022
298      2022
299      2022
300      2022
301      2022
302      2022
303      2022
304      2022
305      2022
306      2022
307      2022
308      2022
309      2022
310      2022
311      2022
312      2022
313      2022
314      2022
315      2022
316      2022
317      2022
318      2022
319      2022
320      2022
321      2022
322      2022
323      2022
324      2022
325      2022
326      2022
327      2022
328      2022
329      2022
330      2022
331      2022
332      2022
333      2022
334      2022
335      2022
336      2022
337      2022
338      2022
339      2022
340      2022
341      2022
342      2022
343      2022
344      2023
345      2023
346      2023
347      2023
348      2023
349      2023
350      2023
351      2023
352      2023
353      2023
354      2023
355      2023
356      2023
357      2023
358      2023
359      2023
360      2023
361      2023
362      2023
363      2023
364      2023
365      2023
366      2023
367      2023
368      2023
369      2023
370      2023
371      2023
372      2023
373      2023
374      2023
375      2023
376      2023
377      2023
378      2023
379      2023
380      2023
381      2023
382      2023
383      2023
384      2023
385      2023
386      2023
387      2023
388      2023
389      2023
390      2023
391      2023
392      2023
393      2023
394      2023
395      2023
396      2024
397      2024
398      2024
399      2024
400      2024
401      2024
402      2024
403      2024
404      2024
405      2024
406      2024
407      2024
408      2024
409      2024
410      2024
411      2024
412      2024
413      2024
414      2024
415      2024
416      2024
417      2024
418      2024
419      2024
420      2024
421      2024
422      2024
423      2024
424      2024
425      2024
426      2024
427      2024
428      2024
429      2024
430      2024
431      2024
432      2024
433      2024
434      2024
435      2024
436      2024
437      2024
438      2024
439      2024
440      2024
441      2024
442      2024
443      2024
444      2024
445      2024
446      2024
447      2024
448      2024
449      2024
450      2024
451      2024
452      2024
453      2024
454      2024
455      2024
456      2024
457      2024
458      2024
459      2024
460      2024
461      2024
462      2024
463      2024
464      2024
465      2024
466      2024
467      2024
468      2024
469      2024
470      2024
471      2024
472      2024
473      2024
474      2018
475      2018
476      2018
477      2018
478      2018
479      2018
480      2018
481      2018
482      2018
483      2018
484      2018
485      2018
486      2018
487      2018
488      2018
489      2018
490      2018
491      2018
492      2018
493      2018
494      2018
495      2018
496      2018
497      2018
498      2018
499      2018
500      2018
501      2018
502      2018
503      2018
504      2018
505      2018
506      2018
507      2018
508      2018
509      2018
510      2018
511      2018
512      2018
513      2018
514      2018
515      2018
516      2018
517      2018
518      2018
519      2018
520      2018
521      2018
522      2018
523      2018
524      2018
525      2018
526      2018
527      2018
528      2018
529      2018
530      2018
531      2018
532      2018
533      2018
534      2018
535      2018
536      2018
537      2018
538      2018
539      2018
540      2018
541      2018
542      2018
543      2018
544      2018
545      2018
546      2018
547      2018
548      2018
549      2018
550      2018
551      2018
552      2018
553      2018
554      2018
555      2018
556      2018
557      2018
558      2018
559      2018
560      2018
561      2018
562      2018
563      2018
564      2018
565      2018
566      2018
567      2018
568      2018
569      2018
570      2018
571      2018
572      2018
573      2018
574      2019
575      2019
576      2019
577      2019
578      2019
579      2019
580      2019
581      2019
582      2019
583      2019
584      2019
585      2019
586      2019
587      2019
588      2019
589      2019
590      2019
591      2019
592      2019
593      2019
594      2019
595      2019
596      2019
597      2019
598      2019
599      2019
600      2019
601      2019
602      2019
603      2019
604      2019
605      2019
606      2019
607      2019
608      2019
609      2019
610      2019
611      2019
612      2019
613      2019
614      2019
615      2019
616      2019
617      2019
618      2019
619      2019
620      2019
621      2019
622      2019
623      2019
624      2019
625      2019
626      2019
627      2019
628      2019
629      2019
630      2019
631      2019
632      2019
633      2019
634      2019
635      2019
636      2019
637      2019
638      2019
639      2019
640      2019
641      2019
642      2019
643      2019
644      2019
645      2019
646      2019
647      2019
648      2019
649      2019
650      2019
651      2019
652      2019
653      2019
654      2019
655      2019
656      2019
657      2019
658      2019
659      2019
660      2019
661      2019
662      2019
663      2019
664      2019
665      2019
666      2019
667      2019
668      2019
669      2019
670      2019
671      2019
672      2019
673      2019
674      2020
675      2020
676      2020
677      2020
678      2020
679      2020
680      2020
681      2020
682      2020
683      2020
684      2020
685      2020
686      2020
687      2020
688      2020
689      2020
690      2020
691      2020
692      2020
693      2020
694      2020
695      2020
696      2020
697      2020
698      2020
699      2020
700      2020
701      2020
702      2020
703      2020
704      2020
705      2020
706      2020
707      2020
708      2020
709      2020
710      2020
711      2020
712      2020
713      2020
714      2020
715      2020
716      2020
717      2020
718      2020
719      2020
720      2020
721      2020
722      2020
723      2020
724      2020
725      2020
726      2020
727      2020
728      2020
729      2020
730      2020
731      2020
732      2020
733      2020
734      2020
735      2020
736      2020
737      2020
738      2020
739      2020
740      2020
741      2020
742      2020
743      2020
744      2020
745      2020
746      2020
747      2020
748      2020
749      2020
750      2020
751      2020
752      2020
753      2020
754      2020
755      2020
756      2020
757      2020
758      2020
759      2020
760      2020
761      2020
762      2020
763      2020
764      2020
765      2020
766      2020
767      2020
768      2020
769      2020
770      2020
771      2020
772      2020
773      2020
774      2021
775      2021
776      2021
777      2021
778      2021
779      2021
780      2021
781      2021
782      2021
783      2021
784      2021
785      2021
786      2021
787      2021
788      2021
789      2021
790      2021
791      2021
792      2021
793      2021
794      2021
795      2021
796      2021
797      2021
798      2021
799      2021
800      2021
801      2021
802      2021
803      2021
804      2021
805      2021
806      2021
807      2021
808      2021
809      2021
810      2021
811      2021
812      2021
813      2021
814      2021
815      2021
816      2021
817      2021
818      2021
819      2021
820      2021
821      2021
822      2021
823      2021
824      2021
825      2021
826      2021
827      2021
828      2021
829      2021
830      2021
831      2021
832      2021
833      2021
834      2021
835      2021
836      2021
837      2021
838      2021
839      2021
840      2021
841      2021
842      2021
843      2021
844      2021
845      2021
846      2021
847      2021
848      2021
849      2021
850      2021
851      2021
852      2021
853      2021
854      2021
855      2021
856      2021
857      2021
858      2021
859      2021
860      2021
861      2021
862      2021
863      2021
864      2021
865      2021
866      2021
867      2021
868      2021
869      2021
870      2021
871      2021
872      2021
873      2021
874      2022
875      2022
876      2022
877      2022
878      2022
879      2022
880      2022
881      2022
882      2022
883      2022
884      2022
885      2022
886      2022
887      2022
888      2022
889      2022
890      2022
891      2022
892      2022
893      2022
894      2022
895      2022
896      2022
897      2022
898      2022
899      2022
900      2022
901      2022
902      2022
903      2022
904      2022
905      2022
906      2022
907      2022
908      2022
909      2022
910      2022
911      2022
912      2022
913      2022
914      2022
915      2022
916      2022
917      2022
918      2022
919      2022
920      2022
921      2022
922      2022
923      2022
924      2022
925      2022
926      2022
927      2022
928      2022
929      2022
930      2022
931      2022
932      2022
933      2022
934      2022
935      2022
936      2022
937      2022
938      2022
939      2022
940      2022
941      2022
942      2022
943      2022
944      2022
945      2022
946      2022
947      2022
948      2022
949      2022
950      2022
951      2022
952      2022
953      2022
954      2022
955      2022
956      2022
957      2022
958      2022
959      2022
960      2022
961      2022
962      2022
963      2022
964      2022
965      2022
966      2022
967      2022
968      2022
969      2022
970      2022
971      2022
972      2022
973      2022
974      2023
975      2023
976      2023
977      2023
978      2023
979      2023
980      2023
981      2023
982      2023
983      2023
984      2023
985      2023
986      2023
987      2023
988      2023
989      2023
990      2023
991      2023
992      2023
993      2023
994      2023
995      2023
996      2023
997      2023
998      2023
999      2023
1000     2023
1001     2023
1002     2023
1003     2023
1004     2023
1005     2023
1006     2023
1007     2023
1008     2023
1009     2023
1010     2023
1011     2023
1012     2023
1013     2023
1014     2023
1015     2023
1016     2023
1017     2023
1018     2023
1019     2023
1020     2023
1021     2023
1022     2023
1023     2023
1024     2023
1025     2023
1026     2023
1027     2023
1028     2023
1029     2023
1030     2023
1031     2023
1032     2023
1033     2023
1034     2023
1035     2023
1036     2023
1037     2023
1038     2023
1039     2023
1040     2023
1041     2023
1042     2023
1043     2023
1044     2023
1045     2023
1046     2023
1047     2023
1048     2023
1049     2023
1050     2023
1051     2023
1052     2023
1053     2023
1054     2023
1055     2023
1056     2023
1057     2023
1058     2023
1059     2023
1060     2023
1061     2023
1062     2023
1063     2023
1064     2023
1065     2023
1066     2023
1067     2023
1068     2023
1069     2023
1070     2023
1071     2023
1072     2023
1073     2023
1074     2024
1075     2024
1076     2024
1077     2024
1078     2024
1079     2024
1080     2024
1081     2024
1082     2024
1083     2024
1084     2024
1085     2024
1086     2024
1087     2024
1088     2024
1089     2024
1090     2024
1091     2024
1092     2024
1093     2024
1094     2024
1095     2024
1096     2024
1097     2024
1098     2024
1099     2024
1100     2024
1101     2024
1102     2024
1103     2024
1104     2024
1105     2024
1106     2024
1107     2024
1108     2024
1109     2024
1110     2024
1111     2024
1112     2024
1113     2024
1114     2024
1115     2024
1116     2024
1117     2024
1118     2024
1119     2024
1120     2024
1121     2024
1122     2024
1123     2024
1124     2024
1125     2024
1126     2024
1127     2024
1128     2024
1129     2024
1130     2024
1131     2024
1132     2024
1133     2024
1134     2024
1135     2024
1136     2024
1137     2024
1138     2024
1139     2024
1140     2024
1141     2024
1142     2024
1143     2024
1144     2024
1145     2024
1146     2024
1147     2024
1148     2024
1149     2024
1150     2024
1151     2024
1152     2024
1153     2024
1154     2024
1155     2024
1156     2024
1157     2024
1158     2024
1159     2024
1160     2024
1161     2024
1162     2024
1163     2024
1164     2024
1165     2024
1166     2024
1167     2024
1168     2024
1169     2024
1170     2024
1171     2024
1172     2024
1173     2024
1174     2024
1175     2024
1176     2018
1177     2018
1178     2018
1179     2018
1180     2018
1181     2018
1182     2018
1183     2018
1184     2018
1185     2018
1186     2018
1187     2018
1188     2018
1189     2018
1190     2018
1191     2018
1192     2018
1193     2018
1194     2018
1195     2018
1196     2018
1197     2018
1198     2018
1199     2018
1200     2018
1201     2018
1202     2018
1203     2018
1204     2018
1205     2018
1206     2018
1207     2018
1208     2018
1209     2018
1210     2018
1211     2018
1212     2018
1213     2018
1214     2018
1215     2018
1216     2018
1217     2018
1218     2018
1219     2018
1220     2018
1221     2018
1222     2018
1223     2018
1224     2018
1225     2018
1226     2018
1227     2018
1228     2018
1229     2018
1230     2018
1231     2018
1232     2018
1233     2018
1234     2018
1235     2018
1236     2018
1237     2018
1238     2018
1239     2018
1240     2018
1241     2018
1242     2018
1243     2018
1244     2018
1245     2018
1246     2018
1247     2018
1248     2018
1249     2018
1250     2018
1251     2018
1252     2018
1253     2018
1254     2018
1255     2018
1256     2018
1257     2018
1258     2018
1259     2018
1260     2018
1261     2018
1262     2018
1263     2018
1264     2018
1265     2018
1266     2018
1267     2018
1268     2018
1269     2018
1270     2018
1271     2018
1272     2018
1273     2018
1274     2018
1275     2018
1276     2018
1277     2018
1278     2018
1279     2018
1280     2018
1281     2018
1282     2018
1283     2018
1284     2018
1285     2018
1286     2018
1287     2018
1288     2018
1289     2018
1290     2018
1291     2018
1292     2018
1293     2018
1294     2018
1295     2018
1296     2018
1297     2018
1298     2018
1299     2018
1300     2018
1301     2018
1302     2018
1303     2018
1304     2018
1305     2018
1306     2018
1307     2018
1308     2019
1309     2019
1310     2019
1311     2019
1312     2019
1313     2019
1314     2019
1315     2019
1316     2019
1317     2019
1318     2019
1319     2019
1320     2019
1321     2019
1322     2019
1323     2019
1324     2019
1325     2019
1326     2019
1327     2019
1328     2019
1329     2019
1330     2019
1331     2019
1332     2019
1333     2019
1334     2019
1335     2019
1336     2019
1337     2019
1338     2019
1339     2019
1340     2019
1341     2019
1342     2019
1343     2019
1344     2019
1345     2019
1346     2019
1347     2019
1348     2019
1349     2019
1350     2019
1351     2019
1352     2019
1353     2019
1354     2019
1355     2019
1356     2019
1357     2019
1358     2019
1359     2019
1360     2019
1361     2019
1362     2019
1363     2019
1364     2019
1365     2019
1366     2019
1367     2019
1368     2019
1369     2019
1370     2019
1371     2019
1372     2019
1373     2019
1374     2019
1375     2019
1376     2019
1377     2019
1378     2019
1379     2019
1380     2019
1381     2019
1382     2019
1383     2019
1384     2019
1385     2019
1386     2019
1387     2019
1388     2019
1389     2019
1390     2019
1391     2019
1392     2019
1393     2019
1394     2019
1395     2019
1396     2019
1397     2019
1398     2019
1399     2019
1400     2019
1401     2019
1402     2019
1403     2019
1404     2019
1405     2019
1406     2019
1407     2019
1408     2019
1409     2019
1410     2019
1411     2019
1412     2019
1413     2019
1414     2019
1415     2019
1416     2019
1417     2019
1418     2019
1419     2019
1420     2019
1421     2019
1422     2019
1423     2019
1424     2019
1425     2019
1426     2019
1427     2019

In [264]:
df_grp_map_user= map_user_list.groupby('State')['Registered_users'].sum().reset_index()
df_grp_map_user.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 36 entries, 0 to 35
Data columns (total 2 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   State             36 non-null     object
 1   Registered_users  36 non-null     int64
dtypes: int64(1), object(1)
memory usage: 708.0+ bytes

In [265]:
import pandas as pd
import json
import os

df = df_grp_map_user

fig = px.choropleth(
    df,
    geojson="https://gist.githubusercontent.com/jbrobst/56c13bbbf9d97d187fea01ca62ea5112/raw/e388c4cae20aa53cb5090210a42ebb9b765c0a36/india_states.geojson",
    featureidkey='properties.ST_NM',
    locations='State',
    color='Registered_users',
    color_continuous_scale='Burg'
)

fig.update_geos(fitbounds="locations", visible=False)
fig.update_layout(title_text='Insurance Transactions by State in India')

fig.show()

In [266]:
# TOP Transaction

In [267]:
import os
path = "D:/Movies/Guvi_2/PhonePe/phonepe-pulse/data/top/transaction/country/india/state/"

top_tran_list = os.listdir(path)
top_tran_list

#<------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------>#

#This is to extract the data's to create a dataframe
clm = {
    'State': [],
    'Year': [],
    'Quarter': [],
    'District': [],
    'Transaction_count': [],
    'Transaction_amount': []
}

for i in map_tran_list:                
    p_i = path + i + "/"
    map_yr = os.listdir(p_i)
    for j in map_yr:                    
        p_j = p_i + j + "/"
        map_yr_list = os.listdir(p_j)
        for k in map_yr_list:           
            p_k = p_j + k
            with open(p_k, 'r') as Data:
                D = json.load(Data)
                for z in D['data']['districts']:
                    district = z['entityName']
                    count = z['metric']['count']
                    amount = z['metric']['amount']
                    clm['District'].append(district)
                    clm['Transaction_count'].append(count)
                    clm['Transaction_amount'].append(amount)
                    clm['State'].append(i)
                    clm['Year'].append(j)
                    clm['Quarter'].append(int(k.strip('.json')))
top_trans=pd.DataFrame(clm)

In [268]:
top_trans.head()

,State,Year,Quarter,District,Transaction_count,Transaction_amount
0,andaman-&-nicobar-islands,2018,1,south andaman,5688,1.256025e+07
1,andaman-&-nicobar-islands,2018,1,nicobars,528,1.139849e+06
2,andaman-&-nicobar-islands,2018,1,north and middle andaman,442,9.316631e+05
3,andaman-&-nicobar-islands,2018,2,south andaman,9395,2.394824e+07
4,andaman-&-nicobar-islands,2018,2,nicobars,1120,3.072437e+06

In [269]:
import re
def modify(s):
    s = s.replace('-', ' ')
    return ' '.join(word.capitalize() for word in s.split())

top_trans['State'] = top_trans['State'].apply(modify)
top_trans['District'] = top_trans['District'].apply(modify)


update_cat = {
    "Andaman & Nicobar Islands": "Andaman & Nicobar",
    "Dadra & Nagar Haveli & Daman & Diu": "Dadra and Nagar Haveli and Daman and Diu"
}

top_trans['State'] = top_trans['State'].replace(update_cat)

In [270]:
top_trans.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8296 entries, 0 to 8295
Data columns (total 6 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   State               8296 non-null   object
 1   Year                8296 non-null   object
 2   Quarter             8296 non-null   int64
 3   District            8296 non-null   object
 4   Transaction_count   8296 non-null   int64
 5   Transaction_amount  8296 non-null   float64
dtypes: float64(1), int64(2), object(3)
memory usage: 389.0+ KB

In [271]:
top_trans['Year'] = pd.to_datetime(top_trans['Year']).dt.year

top_trans['Year'].info()
top_trans['Year']

<class 'pandas.core.series.Series'>
RangeIndex: 8296 entries, 0 to 8295
Series name: Year
Non-Null Count  Dtype
--------------  -----
8296 non-null   int32
dtypes: int32(1)
memory usage: 32.5 KB

0       2018
1       2018
2       2018
3       2018
4       2018
5       2018
6       2018
7       2018
8       2018
9       2018
10      2018
11      2018
12      2019
13      2019
14      2019
15      2019
16      2019
17      2019
18      2019
19      2019
20      2019
21      2019
22      2019
23      2019
24      2020
25      2020
26      2020
27      2020
28      2020
29      2020
30      2020
31      2020
32      2020
33      2020
34      2020
35      2020
36      2021
37      2021
38      2021
39      2021
40      2021
41      2021
42      2021
43      2021
44      2021
45      2021
46      2021
47      2021
48      2022
49      2022
50      2022
51      2022
52      2022
53      2022
54      2022
55      2022
56      2022
57      2022
58      2022
59      2022
60      2023
61      2023
62      2023
63      2023
64      2023
65      2023
66      2023
67      2023
68      2023
69      2023
70      2023
71      2023
72      2024
73      2024
74      2024
75      2024
76      2024
77      2024
78      2024
79      2024
80      2024
81      2024
82      2024
83      2024
84      2018
85      2018
86      2018
87      2018
88      2018
89      2018
90      2018
91      2018
92      2018
93      2018
94      2018
95      2018
96      2018
97      2018
98      2018
99      2018
100     2018
101     2018
102     2018
103     2018
104     2018
105     2018
106     2018
107     2018
108     2018
109     2018
110     2018
111     2018
112     2018
113     2018
114     2018
115     2018
116     2018
117     2018
118     2018
119     2018
120     2018
121     2018
122     2018
123     2018
124     2019
125     2019
126     2019
127     2019
128     2019
129     2019
130     2019
131     2019
132     2019
133     2019
134     2019
135     2019
136     2019
137     2019
138     2019
139     2019
140     2019
141     2019
142     2019
143     2019
144     2019
145     2019
146     2019
147     2019
148     2019
149     2019
150     2019
151     2019
152     2019
153     2019
154     2019
155     2019
156     2019
157     2019
158     2019
159     2019
160     2019
161     2019
162     2019
163     2019
164     2020
165     2020
166     2020
167     2020
168     2020
169     2020
170     2020
171     2020
172     2020
173     2020
174     2020
175     2020
176     2020
177     2020
178     2020
179     2020
180     2020
181     2020
182     2020
183     2020
184     2020
185     2020
186     2020
187     2020
188     2020
189     2020
190     2020
191     2020
192     2020
193     2020
194     2020
195     2020
196     2020
197     2020
198     2020
199     2020
200     2020
201     2020
202     2020
203     2020
204     2021
205     2021
206     2021
207     2021
208     2021
209     2021
210     2021
211     2021
212     2021
213     2021
214     2021
215     2021
216     2021
217     2021
218     2021
219     2021
220     2021
221     2021
222     2021
223     2021
224     2021
225     2021
226     2021
227     2021
228     2021
229     2021
230     2021
231     2021
232     2021
233     2021
234     2021
235     2021
236     2021
237     2021
238     2021
239     2021
240     2021
241     2021
242     2021
243     2021
244     2022
245     2022
246     2022
247     2022
248     2022
249     2022
250     2022
251     2022
252     2022
253     2022
254     2022
255     2022
256     2022
257     2022
258     2022
259     2022
260     2022
261     2022
262     2022
263     2022
264     2022
265     2022
266     2022
267     2022
268     2022
269     2022
270     2022
271     2022
272     2022
273     2022
274     2022
275     2022
276     2022
277     2022
278     2022
279     2022
280     2022
281     2022
282     2022
283     2022
284     2023
285     2023
286     2023
287     2023
288     2023
289     2023
290     2023
291     2023
292     2023
293     2023
294     2023
295     2023
296     2023
297     2023
298     2023
299     2023
300     2023
301     2023
302     2023
303     2023
304     2023
305     2023
306     2023
307     2023
308     2023
309     2023
310     2023
311     2023
312     2023
313     2023
314     2023
315     2023
316     2023
317     2023
318     2023
319     2023
320     2023
321     2023
322     2023
323     2023
324     2024
325     2024
326     2024
327     2024
328     2024
329     2024
330     2024
331     2024
332     2024
333     2024
334     2024
335     2024
336     2024
337     2024
338     2024
339     2024
340     2024
341     2024
342     2024
343     2024
344     2024
345     2024
346     2024
347     2024
348     2024
349     2024
350     2024
351     2024
352     2024
353     2024
354     2024
355     2024
356     2024
357     2024
358     2024
359     2024
360     2024
361     2024
362     2024
363     2024
364     2018
365     2018
366     2018
367     2018
368     2018
369     2018
370     2018
371     2018
372     2018
373     2018
374     2018
375     2018
376     2018
377     2018
378     2018
379     2018
380     2018
381     2018
382     2018
383     2018
384     2018
385     2018
386     2018
387     2018
388     2018
389     2018
390     2018
391     2018
392     2018
393     2018
394     2018
395     2018
396     2018
397     2018
398     2018
399     2018
400     2018
401     2018
402     2018
403     2018
404     2019
405     2019
406     2019
407     2019
408     2019
409     2019
410     2019
411     2019
412     2019
413     2019
414     2019
415     2019
416     2019
417     2019
418     2019
419     2019
420     2019
421     2019
422     2019
423     2019
424     2019
425     2019
426     2019
427     2019
428     2019
429     2019
430     2019
431     2019
432     2019
433     2019
434     2019
435     2019
436     2019
437     2019
438     2019
439     2019
440     2019
441     2019
442     2019
443     2019
444     2020
445     2020
446     2020
447     2020
448     2020
449     2020
450     2020
451     2020
452     2020
453     2020
454     2020
455     2020
456     2020
457     2020
458     2020
459     2020
460     2020
461     2020
462     2020
463     2020
464     2020
465     2020
466     2020
467     2020
468     2020
469     2020
470     2020
471     2020
472     2020
473     2020
474     2020
475     2020
476     2020
477     2020
478     2020
479     2020
480     2020
481     2020
482     2020
483     2020
484     2021
485     2021
486     2021
487     2021
488     2021
489     2021
490     2021
491     2021
492     2021
493     2021
494     2021
495     2021
496     2021
497     2021
498     2021
499     2021
500     2021
501     2021
502     2021
503     2021
504     2021
505     2021
506     2021
507     2021
508     2021
509     2021
510     2021
511     2021
512     2021
513     2021
514     2021
515     2021
516     2021
517     2021
518     2021
519     2021
520     2021
521     2021
522     2021
523     2021
524     2022
525     2022
526     2022
527     2022
528     2022
529     2022
530     2022
531     2022
532     2022
533     2022
534     2022
535     2022
536     2022
537     2022
538     2022
539     2022
540     2022
541     2022
542     2022
543     2022
544     2022
545     2022
546     2022
547     2022
548     2022
549     2022
550     2022
551     2022
552     2022
553     2022
554     2022
555     2022
556     2022
557     2022
558     2022
559     2022
560     2022
561     2022
562     2022
563     2022
564     2023
565     2023
566     2023
567     2023
568     2023
569     2023
570     2023
571     2023
572     2023
573     2023
574     2023
575     2023
576     2023
577     2023
578     2023
579     2023
580     2023
581     2023
582     2023
583     2023
584     2023
585     2023
586     2023
587     2023
588     2023
589     2023
590     2023
591     2023
592     2023
593     2023
594     2023
595     2023
596     2023
597     2023
598     2023
599     2023
600     2023
601     2023
602     2023
603     2023
604     2024
605     2024
606     2024
607     2024
608     2024
609     2024
610     2024
611     2024
612     2024
613     2024
614     2024
615     2024
616     2024
617     2024
618     2024
619     2024
620     2024
621     2024
622     2024
623     2024
624     2024
625     2024
626     2024
627     2024
628     2024
629     2024
630     2024
631     2024
632     2024
633     2024
634     2024
635     2024
636     2024
637     2024
638     2024
639     2024
640     2024
641     2024
642     2024
643     2024
644     2018
645     2018
646     2018
647     2018
648     2018
649     2018
650     2018
651     2018
652     2018
653     2018
654     2018
655     2018
656     2018
657     2018
658     2018
659     2018
660     2018
661     2018
662     2018
663     2018
664     2018
665     2018
666     2018
667     2018
668     2018
669     2018
670     2018
671     2018
672     2018
673     2018
674     2018
675     2018
676     2018
677     2018
678     2018
679     2018
680     2018
681     2018
682     2018
683     2018
684     2019
685     2019
686     2019
687     2019
688     2019
689     2019
690     2019
691     2019
692     2019
693     2019
694     2019
695     2019
696     2019
697     2019
698     2019
699     2019
700     2019
701     2019
702     2019
703     2019
704     2019
705     2019
706     2019
707     2019
708     2019
709     2019
710     2019
711     2019
712     2019
713     2019
714     2019
715     2019
716     2019
717     2019
718     2019
719     2019
720     2019
721     2019
722     2019
723     2019
724     2020
725     2020
726     2020
727     2020
728     2020
729     2020
730     2020
731     2020
732     2020
733     2020
734     2020
735     2020
736     2020
737     2020
738     2020
739     2020
740     2020
741     2020
742     2020
743     2020
744     2020
745     2020
746     2020
747     2020
748     2020
749     2020
750     2020
751     2020
752     2020
753     2020
754     2020
755     2020
756     2020
757     2020
758     2020
759     2020
760     2020
761     2020
762     2020
763     2020
764     2021
765     2021
766     2021
767     2021
768     2021
769     2021
770     2021
771     2021
772     2021
773     2021
774     2021
775     2021
776     2021
777     2021
778     2021
779     2021
780     2021
781     2021
782     2021
783     2021
784     2021
785     2021
786     2021
787     2021
788     2021
789     2021
790     2021
791     2021
792     2021
793     2021
794     2021
795     2021
796     2021
797     2021
798     2021
799     2021
800     2021
801     2021
802     2021
803     2021
804     2022
805     2022
806     2022
807     2022
808     2022
809     2022
810     2022
811     2022
812     2022
813     2022
814     2022
815     2022
816     2022
817     2022
818     2022
819     2022
820     2022
821     2022
822     2022
823     2022
824     2022
825     2022
826     2022
827     2022
828     2022
829     2022
830     2022
831     2022
832     2022
833     2022
834     2022
835     2022
836     2022
837     2022
838     2022
839     2022
840     2022
841     2022
842     2022
843     2022
844     2023
845     2023
846     2023
847     2023
848     2023
849     2023
850     2023
851     2023
852     2023
853     2023
854     2023
855     2023
856     2023
857     2023
858     2023
859     2023
860     2023
861     2023
862     2023
863     2023
864     2023
865     2023
866     2023
867     2023
868     2023
869     2023
870     2023
871     2023
872     2023
873     2023
874     2023
875     2023
876     2023
877     2023
878     2023
879     2023
880     2023
881     2023
882     2023
883     2023
884     2024
885     2024
886     2024
887     2024
888     2024
889     2024
890     2024
891     2024
892     2024
893     2024
894     2024
895     2024
896     2024
897     2024
898     2024
899     2024
900     2024
901     2024
902     2024
903     2024
904     2024
905     2024
906     2024
907     2024
908     2024
909     2024
910     2024
911     2024
912     2024
913     2024
914     2024
915     2024
916     2024
917     2024
918     2024
919     2024
920     2024
921     2024
922     2024
923     2024
924     2018
925     2018
926     2018
927     2018
928     2018
929     2018
930     2018
931     2018
932     2018
933     2018
934     2018
935     2018
936     2018
937     2018
938     2018
939     2018
940     2018
941     2018
942     2018
943     2018
944     2018
945     2018
946     2018
947     2018
948     2018
949     2018
950     2018
951     2018
952     2018
953     2018
954     2018
955     2018
956     2018
957     2018
958     2018
959     2018
960     2018
961     2018
962     2018
963     2018
964     2019
965     2019
966     2019
967     2019
968     2019
969     2019
970     2019
971     2019
972     2019
973     2019
974     2019
975     2019
976     2019
977     2019
978     2019
979     2019
980     2019
981     2019
982     2019
983     2019
984     2019
985     2019
986     2019
987     2019
988     2019
989     2019
990     2019
991     2019
992     2019
993     2019
994     2019
995     2019
996     2019
997     2019
998     2019
999     2019
1000    2019
1001    2019
1002    2019
1003    2019
1004    2020
1005    2020
1006    2020
1007    2020
1008    2020
1009    2020
1010    2020
1011    2020
1012    2020
1013    2020
1014    2020
1015    2020
1016    2020
1017    2020
1018    2020
1019    2020
1020    2020
1021    2020
1022    2020
1023    2020
1024    2020
1025    2020
1026    2020
1027    2020
1028    2020
1029    2020
1030    2020
1031    2020
1032    2020
1033    2020
1034    2020
1035    2020
1036    2020
1037    2020
1038    2020
1039    2020
1040    2020
1041    2020
1042    2020
1043    2020
1044    2021
1045    2021
1046    2021
1047    2021
1048    2021
1049    2021
1050    2021
1051    2021
1052    2021
1053    2021
1054    2021
1055    2021
1056    2021
1057    2021
1058    2021
1059    2021
1060    2021
1061    2021
1062    2021
1063    2021
1064    2021
1065    2021
1066    2021
1067    2021
1068    2021
1069    2021
1070    2021
1071    2021
1072    2021
1073    2021
1074    2021
1075    2021
1076    2021
1077    2021
1078    2021
1079    2021
1080    2021
1081    2021
1082    2021
1083    2021
1084    2022
1085    2022
1086    2022
1087    2022
1088    2022
1089    2022
1090    2022
1091    2022
1092    2022
1093    2022
1094    2022
1095    2022
1096    2022
1097    2022
1098    2022
1099    2022
1100    2022
1101    2022
1102    2022
1103    2022
1104    2022
1105    2022
1106    2022
1107    2022
1108    2022
1109    2022
1110    2022
1111    2022
1112    2022
1113    2022
1114    2022
1115    2022
1116    2022
1117    2022
1118    2022
1119    2022
1120    2022
1121    2022
1122    2022
1123    2022
1124    2023
1125    2023
1126    2023
1127    2023
1128    2023
1129    2023
1130    2023
1131    2023
1132    2023
1133    2023
1134    2023
1135    2023
1136    2023
1137    2023
1138    2023
1139    2023
1140    2023
1141    2023
1142    2023
1143    2023
1144    2023
1145    2023
1146    2023
1147    2023
1148    2023
1149    2023
1150    2023
1151    2023
1152    2023
1153    2023
1154    2023
1155    2023
1156    2023
1157    2023
1158    2023
1159    2023
1160    2023
1161    2023
1162    2023
1163    2023
1164    2024
1165    2024
1166    2024
1167    2024
1168    2024
1169    2024
1170    2024
1171    2024
1172    2024
1173    2024
1174    2024
1175    2024
1176    2024
1177    2024
1178    2024
1179    2024
1180    2024
1181    2024
1182    2024
1183    2024
1184    2024
1185    2024
1186    2024
1187    2024
1188    2024
1189    2024
1190    2024
1191    2024
1192    2024
1193    2024
1194    2024
1195    2024
1196    2024
1197    2024
1198    2024
1199    2024
1200    2024
1201    2024
1202    2024
1203    2024
1204    2018
1205    2018
1206    2018
1207    2018
1208    2019
1209    2019
1210    2019
1211    2019
1212    2020
1213    2020
1214    2020
1215    2020
1216    2021
1217    2021
1218    2021
1219    2021
1220    2022
1221    2022
1222    2022
1223    2022
1224    2023
1225    2023
1226    2023
1227    2023
1228    2024
1229    2024
1230    2024
1231    2024
1232    2018
1233    2018
1234    2018
1235    2018
1236    2018
1237    2018
1238    2018
1239    2018
1240    2018
1241    2018
1242    2018
1243    2018
1244    2018
1245    2018
1246    2018
1247    2018
1248    2018
1249    2018
1250    2018
1251    2018
1252    2018
1253    2018
1254    2018
1255    2018
1256    2018
1257    2018
1258    2018
1259    2018
1260    2018
1261    2018
1262    2018
1263    2018
1264    2018
1265    2018
1266    2018
1267    2018
1268    2018
1269    2018
1270    2018
1271    2018
1272    2019
1273    2019
1274    2019
1275    2019
1276    2019
1277    2019
1278    2019
1279    2019
1280    2019
1281    2019
1282    2019
1283    2019
1284    2019
1285    2019
1286    2019
1287    2019
1288    2019
1289    2019
1290    2019
1291    2019
1292    2019
1293    2019
1294    2019
1295    2019
1296    2019
1297    2019
1298    2019
1299    2019
1300    2019
1301    2019
1302    2019
1303    2019
1304    2019
1305    2019
1306    2019
1307    2019
1308    2019
1309    2019
1310    2019
1311    2019
1312    2020
1313    2020
1314    2020
1315    2020
1316    2020
1317    2020
1318    2020
1319    2020
1320    2020
1321    2020
1322    2020
1323    2020
1324    2020
1325    2020
1326    2020
1327    2020
1328    2020
1329    2020
1330    2020
1331    2020
1332    2020
1333    2020
1334    2020
1335    2020
1336    2020
1337    2020
1338    2020
1339    2020
1340    2020
1341    2020
1342    2020
1343    2020
1344    2020
1345    2020
1346    2020
1347    2020
1348    2020
1349    2020
1350    2020
1351    2020
1352    2021
1353    2021
1354    2021
1355    2021
1356    2021
1357    2021
1358    2021
1359    2021
1360    2021
1361    2021
1362    2021
1363    2021
1364    2021
1365    2021
1366    2021
1367    2021
1368    2021
1369    2021
1370    2021
1371    2021
1372    2021
1373    2021
1374    2021
1375    2021
1376    2021
1377    2021
1378    2021
1379    2021
1380    2021
1381    2021
1382    2021
1383    2021
1384    2021
1385    2021
1386    2021
1387    2021
1388    2021
1389    2021
1390    2021
1391    2021
1392    2022
1393    2022
1394    2022
1395    2022
1396    2022
1397    2022
1398    2022
1399    2022
1400    2022
1401    2022
1402    2022
1403    2022
1404    2022
1405    2022
1406    2022
1407    2022
1408    2022
1409    2022
1410    2022
1411    2022
1412    2022
1413    2022
1414    2022
1415    2022
1416    2022
1417    2022
1418    2022
1419    2022
1420    2022
1421    2022
1422    2022
1423    2022
1424    2022
1425    2022
1426    2022
1427    2022
1428    2022
1429    2022
1430    2022
1431    2022
1432    2023
1433    2023
1434    2023
1435    2023
1436    2023
1437    2023
1438    2023
1439    2023
1440    2023
1441    2023
1442    2023
1443    2023
1444    2023
1445    2023
1446    2023
1447    2023
1448    2023
1449    2023
1450    2023
1451    2023
1452    2023
1453    2023
1454    2023
1455    2023
1456    2023
1457    2023
1458    2023
1459    2023
1460    2023
1461    2023
1462    2023
1463    2023
1464    2023
1465    2023
1466    2023
1467    2023
1468    2023
1469    2023
1470    2023
1471    2023
1472    2024
1473    2024
1474    2024
1475    2024
1476    2024
1477    2024
1478    2024
1479    2024
1480    2024
1481    2024
1482    2024
1483    2024
1484    2024
1485    2024
1486    2024
1487    2024
1488    2024
1489    2024
1490    2024
1491    2024
1492    2024
1493    2024
1494    2024
1495    2024
1496    2024
1497    2024
1498    2024
1499    2024
1500    2024
1501    2024
1502    2024
1503    2024
1504    2024
1505    2024
1506    2024
1507    2024
1508    2024
1509    2024
1510    2024
1511    2024
1512    2018
1513    2018
1514    2018
1515    2018
1516    2018
1517    2018
1518    2018
1519    2018
1520    2018
1521    2018
1522    2018
1523    2018
1524    2019
1525    2019
1526    2019
1527    2019
1528    2019
1529    2019
1530    2019
1531    2019
1532    2019
1533    2019
1534    2019
1535    2019
1536    2020
1537    2020

In [272]:
df_grp_top_trans = top_trans.groupby('State')['Transaction_count'].sum().reset_index()
df_grp_top_trans.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 36 entries, 0 to 35
Data columns (total 2 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   State              36 non-null     object
 1   Transaction_count  36 non-null     int64
dtypes: int64(1), object(1)
memory usage: 708.0+ bytes

In [273]:
import pandas as pd
import json
import os

df = df_grp_top_trans

fig = px.choropleth(
    df,
    geojson="https://gist.githubusercontent.com/jbrobst/56c13bbbf9d97d187fea01ca62ea5112/raw/e388c4cae20aa53cb5090210a42ebb9b765c0a36/india_states.geojson",
    featureidkey='properties.ST_NM',
    locations='State',
    color='Transaction_count',
    color_continuous_scale='Teal'
)

fig.update_geos(fitbounds="locations", visible=False)
fig.update_layout(title_text='Insurance Transactions by State in India')

fig.show()

In [274]:
# TOP USERs

In [275]:
import os

path = "D:/Movies/Guvi_2/PhonePe/phonepe-pulse/data/top/user/country/india/state/"


top_user_list = os.listdir(path)
top_user_list

# <------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------> #
# This is to extract the data's to create a dataframe

clm = {
    'State': [],
    'Year': [],
    'Quarter': [],
    'District': [],
    'Registered_users': []
}

for i in top_user_list:                 # state
    p_i = path + i + "/"
    user_yr = os.listdir(p_i)

    for j in user_yr:                   # year
        p_j = p_i + j + "/"
        user_yr_list = os.listdir(p_j)

        for k in user_yr_list:          # quarter json
            p_k = p_j + k

            with open(p_k, 'r') as Data:
                D = json.load(Data)

                # SAFE ACCESS
                districts = D['data'].get('districts')

                # Skip if data is missing
                if districts is None:
                    continue

                for z in districts:
                    district = z['name']
                    users = z['registeredUsers']

                    clm['District'].append(district)
                    clm['Registered_users'].append(users)
                    clm['State'].append(i)
                    clm['Year'].append(j)
                    clm['Quarter'].append(int(k.strip('.json')))

# Successfully created dataframe
top_user_list = pd.DataFrame(clm)

top_user_list.head()

,State,Year,Quarter,District,Registered_users
0,andaman-&-nicobar-islands,2018,1,south andaman,5846
1,andaman-&-nicobar-islands,2018,1,north and middle andaman,632
2,andaman-&-nicobar-islands,2018,1,nicobars,262
3,andaman-&-nicobar-islands,2018,2,south andaman,8143
4,andaman-&-nicobar-islands,2018,2,north and middle andaman,911

In [276]:
import re
def modify(s):
    s = s.replace('-', ' ')
    return ' '.join(word.capitalize() for word in s.split())

top_user_list['State'] = top_user_list['State'].apply(modify)
top_user_list['District'] = top_user_list['District'].apply(modify)

update_cat = {
    "Andaman & Nicobar Islands": "Andaman & Nicobar",
    "Dadra & Nagar Haveli & Daman & Diu": "Dadra and Nagar Haveli and Daman and Diu"
}

top_user_list['State'] = top_user_list['State'].replace(update_cat)

In [277]:
top_user_list.info()
top_user_list.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8296 entries, 0 to 8295
Data columns (total 5 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   State             8296 non-null   object
 1   Year              8296 non-null   object
 2   Quarter           8296 non-null   int64
 3   District          8296 non-null   object
 4   Registered_users  8296 non-null   int64
dtypes: int64(2), object(3)
memory usage: 324.2+ KB

,State,Year,Quarter,District,Registered_users
0,Andaman & Nicobar,2018,1,South Andaman,5846
1,Andaman & Nicobar,2018,1,North And Middle Andaman,632
2,Andaman & Nicobar,2018,1,Nicobars,262
3,Andaman & Nicobar,2018,2,South Andaman,8143
4,Andaman & Nicobar,2018,2,North And Middle Andaman,911

In [278]:
top_user_list['Year'] = pd.to_datetime(top_user_list['Year']).dt.year

top_user_list['Year'].info()
top_user_list['Year']

<class 'pandas.core.series.Series'>
RangeIndex: 8296 entries, 0 to 8295
Series name: Year
Non-Null Count  Dtype
--------------  -----
8296 non-null   int32
dtypes: int32(1)
memory usage: 32.5 KB

0       2018
1       2018
2       2018
3       2018
4       2018
5       2018
6       2018
7       2018
8       2018
9       2018
10      2018
11      2018
12      2019
13      2019
14      2019
15      2019
16      2019
17      2019
18      2019
19      2019
20      2019
21      2019
22      2019
23      2019
24      2020
25      2020
26      2020
27      2020
28      2020
29      2020
30      2020
31      2020
32      2020
33      2020
34      2020
35      2020
36      2021
37      2021
38      2021
39      2021
40      2021
41      2021
42      2021
43      2021
44      2021
45      2021
46      2021
47      2021
48      2022
49      2022
50      2022
51      2022
52      2022
53      2022
54      2022
55      2022
56      2022
57      2022
58      2022
59      2022
60      2023
61      2023
62      2023
63      2023
64      2023
65      2023
66      2023
67      2023
68      2023
69      2023
70      2023
71      2023
72      2024
73      2024
74      2024
75      2024
76      2024
77      2024
78      2024
79      2024
80      2024
81      2024
82      2024
83      2024
84      2018
85      2018
86      2018
87      2018
88      2018
89      2018
90      2018
91      2018
92      2018
93      2018
94      2018
95      2018
96      2018
97      2018
98      2018
99      2018
100     2018
101     2018
102     2018
103     2018
104     2018
105     2018
106     2018
107     2018
108     2018
109     2018
110     2018
111     2018
112     2018
113     2018
114     2018
115     2018
116     2018
117     2018
118     2018
119     2018
120     2018
121     2018
122     2018
123     2018
124     2019
125     2019
126     2019
127     2019
128     2019
129     2019
130     2019
131     2019
132     2019
133     2019
134     2019
135     2019
136     2019
137     2019
138     2019
139     2019
140     2019
141     2019
142     2019
143     2019
144     2019
145     2019
146     2019
147     2019
148     2019
149     2019
150     2019
151     2019
152     2019
153     2019
154     2019
155     2019
156     2019
157     2019
158     2019
159     2019
160     2019
161     2019
162     2019
163     2019
164     2020
165     2020
166     2020
167     2020
168     2020
169     2020
170     2020
171     2020
172     2020
173     2020
174     2020
175     2020
176     2020
177     2020
178     2020
179     2020
180     2020
181     2020
182     2020
183     2020
184     2020
185     2020
186     2020
187     2020
188     2020
189     2020
190     2020
191     2020
192     2020
193     2020
194     2020
195     2020
196     2020
197     2020
198     2020
199     2020
200     2020
201     2020
202     2020
203     2020
204     2021
205     2021
206     2021
207     2021
208     2021
209     2021
210     2021
211     2021
212     2021
213     2021
214     2021
215     2021
216     2021
217     2021
218     2021
219     2021
220     2021
221     2021
222     2021
223     2021
224     2021
225     2021
226     2021
227     2021
228     2021
229     2021
230     2021
231     2021
232     2021
233     2021
234     2021
235     2021
236     2021
237     2021
238     2021
239     2021
240     2021
241     2021
242     2021
243     2021
244     2022
245     2022
246     2022
247     2022
248     2022
249     2022
250     2022
251     2022
252     2022
253     2022
254     2022
255     2022
256     2022
257     2022
258     2022
259     2022
260     2022
261     2022
262     2022
263     2022
264     2022
265     2022
266     2022
267     2022
268     2022
269     2022
270     2022
271     2022
272     2022
273     2022
274     2022
275     2022
276     2022
277     2022
278     2022
279     2022
280     2022
281     2022
282     2022
283     2022
284     2023
285     2023
286     2023
287     2023
288     2023
289     2023
290     2023
291     2023
292     2023
293     2023
294     2023
295     2023
296     2023
297     2023
298     2023
299     2023
300     2023
301     2023
302     2023
303     2023
304     2023
305     2023
306     2023
307     2023
308     2023
309     2023
310     2023
311     2023
312     2023
313     2023
314     2023
315     2023
316     2023
317     2023
318     2023
319     2023
320     2023
321     2023
322     2023
323     2023
324     2024
325     2024
326     2024
327     2024
328     2024
329     2024
330     2024
331     2024
332     2024
333     2024
334     2024
335     2024
336     2024
337     2024
338     2024
339     2024
340     2024
341     2024
342     2024
343     2024
344     2024
345     2024
346     2024
347     2024
348     2024
349     2024
350     2024
351     2024
352     2024
353     2024
354     2024
355     2024
356     2024
357     2024
358     2024
359     2024
360     2024
361     2024
362     2024
363     2024
364     2018
365     2018
366     2018
367     2018
368     2018
369     2018
370     2018
371     2018
372     2018
373     2018
374     2018
375     2018
376     2018
377     2018
378     2018
379     2018
380     2018
381     2018
382     2018
383     2018
384     2018
385     2018
386     2018
387     2018
388     2018
389     2018
390     2018
391     2018
392     2018
393     2018
394     2018
395     2018
396     2018
397     2018
398     2018
399     2018
400     2018
401     2018
402     2018
403     2018
404     2019
405     2019
406     2019
407     2019
408     2019
409     2019
410     2019
411     2019
412     2019
413     2019
414     2019
415     2019
416     2019
417     2019
418     2019
419     2019
420     2019
421     2019
422     2019
423     2019
424     2019
425     2019
426     2019
427     2019
428     2019
429     2019
430     2019
431     2019
432     2019
433     2019
434     2019
435     2019
436     2019
437     2019
438     2019
439     2019
440     2019
441     2019
442     2019
443     2019
444     2020
445     2020
446     2020
447     2020
448     2020
449     2020
450     2020
451     2020
452     2020
453     2020
454     2020
455     2020
456     2020
457     2020
458     2020
459     2020
460     2020
461     2020
462     2020
463     2020
464     2020
465     2020
466     2020
467     2020
468     2020
469     2020
470     2020
471     2020
472     2020
473     2020
474     2020
475     2020
476     2020
477     2020
478     2020
479     2020
480     2020
481     2020
482     2020
483     2020
484     2021
485     2021
486     2021
487     2021
488     2021
489     2021
490     2021
491     2021
492     2021
493     2021
494     2021
495     2021
496     2021
497     2021
498     2021
499     2021
500     2021
501     2021
502     2021
503     2021
504     2021
505     2021
506     2021
507     2021
508     2021
509     2021
510     2021
511     2021
512     2021
513     2021
514     2021
515     2021
516     2021
517     2021
518     2021
519     2021
520     2021
521     2021
522     2021
523     2021
524     2022
525     2022
526     2022
527     2022
528     2022
529     2022
530     2022
531     2022
532     2022
533     2022
534     2022
535     2022
536     2022
537     2022
538     2022
539     2022
540     2022
541     2022
542     2022
543     2022
544     2022
545     2022
546     2022
547     2022
548     2022
549     2022
550     2022
551     2022
552     2022
553     2022
554     2022
555     2022
556     2022
557     2022
558     2022
559     2022
560     2022
561     2022
562     2022
563     2022
564     2023
565     2023
566     2023
567     2023
568     2023
569     2023
570     2023
571     2023
572     2023
573     2023
574     2023
575     2023
576     2023
577     2023
578     2023
579     2023
580     2023
581     2023
582     2023
583     2023
584     2023
585     2023
586     2023
587     2023
588     2023
589     2023
590     2023
591     2023
592     2023
593     2023
594     2023
595     2023
596     2023
597     2023
598     2023
599     2023
600     2023
601     2023
602     2023
603     2023
604     2024
605     2024
606     2024
607     2024
608     2024
609     2024
610     2024
611     2024
612     2024
613     2024
614     2024
615     2024
616     2024
617     2024
618     2024
619     2024
620     2024
621     2024
622     2024
623     2024
624     2024
625     2024
626     2024
627     2024
628     2024
629     2024
630     2024
631     2024
632     2024
633     2024
634     2024
635     2024
636     2024
637     2024
638     2024
639     2024
640     2024
641     2024
642     2024
643     2024
644     2018
645     2018
646     2018
647     2018
648     2018
649     2018
650     2018
651     2018
652     2018
653     2018
654     2018
655     2018
656     2018
657     2018
658     2018
659     2018
660     2018
661     2018
662     2018
663     2018
664     2018
665     2018
666     2018
667     2018
668     2018
669     2018
670     2018
671     2018
672     2018
673     2018
674     2018
675     2018
676     2018
677     2018
678     2018
679     2018
680     2018
681     2018
682     2018
683     2018
684     2019
685     2019
686     2019
687     2019
688     2019
689     2019
690     2019
691     2019
692     2019
693     2019
694     2019
695     2019
696     2019
697     2019
698     2019
699     2019
700     2019
701     2019
702     2019
703     2019
704     2019
705     2019
706     2019
707     2019
708     2019
709     2019
710     2019
711     2019
712     2019
713     2019
714     2019
715     2019
716     2019
717     2019
718     2019
719     2019
720     2019
721     2019
722     2019
723     2019
724     2020
725     2020
726     2020
727     2020
728     2020
729     2020
730     2020
731     2020
732     2020
733     2020
734     2020
735     2020
736     2020
737     2020
738     2020
739     2020
740     2020
741     2020
742     2020
743     2020
744     2020
745     2020
746     2020
747     2020
748     2020
749     2020
750     2020
751     2020
752     2020
753     2020
754     2020
755     2020
756     2020
757     2020
758     2020
759     2020
760     2020
761     2020
762     2020
763     2020
764     2021
765     2021
766     2021
767     2021
768     2021
769     2021
770     2021
771     2021
772     2021
773     2021
774     2021
775     2021
776     2021
777     2021
778     2021
779     2021
780     2021
781     2021
782     2021
783     2021
784     2021
785     2021
786     2021
787     2021
788     2021
789     2021
790     2021
791     2021
792     2021
793     2021
794     2021
795     2021
796     2021
797     2021
798     2021
799     2021
800     2021
801     2021
802     2021
803     2021
804     2022
805     2022
806     2022
807     2022
808     2022
809     2022
810     2022
811     2022
812     2022
813     2022
814     2022
815     2022
816     2022
817     2022
818     2022
819     2022
820     2022
821     2022
822     2022
823     2022
824     2022
825     2022
826     2022
827     2022
828     2022
829     2022
830     2022
831     2022
832     2022
833     2022
834     2022
835     2022
836     2022
837     2022
838     2022
839     2022
840     2022
841     2022
842     2022
843     2022
844     2023
845     2023
846     2023
847     2023
848     2023
849     2023
850     2023
851     2023
852     2023
853     2023
854     2023
855     2023
856     2023
857     2023
858     2023
859     2023
860     2023
861     2023
862     2023
863     2023
864     2023
865     2023
866     2023
867     2023
868     2023
869     2023
870     2023
871     2023
872     2023
873     2023
874     2023
875     2023
876     2023
877     2023
878     2023
879     2023
880     2023
881     2023
882     2023
883     2023
884     2024
885     2024
886     2024
887     2024
888     2024
889     2024
890     2024
891     2024
892     2024
893     2024
894     2024
895     2024
896     2024
897     2024
898     2024
899     2024
900     2024
901     2024
902     2024
903     2024
904     2024
905     2024
906     2024
907     2024
908     2024
909     2024
910     2024
911     2024
912     2024
913     2024
914     2024
915     2024
916     2024
917     2024
918     2024
919     2024
920     2024
921     2024
922     2024
923     2024
924     2018
925     2018
926     2018
927     2018
928     2018
929     2018
930     2018
931     2018
932     2018
933     2018
934     2018
935     2018
936     2018
937     2018
938     2018
939     2018
940     2018
941     2018
942     2018
943     2018
944     2018
945     2018
946     2018
947     2018
948     2018
949     2018
950     2018
951     2018
952     2018
953     2018
954     2018
955     2018
956     2018
957     2018
958     2018
959     2018
960     2018
961     2018
962     2018
963     2018
964     2019
965     2019
966     2019
967     2019
968     2019
969     2019
970     2019
971     2019
972     2019
973     2019
974     2019
975     2019
976     2019
977     2019
978     2019
979     2019
980     2019
981     2019
982     2019
983     2019
984     2019
985     2019
986     2019
987     2019
988     2019
989     2019
990     2019
991     2019
992     2019
993     2019
994     2019
995     2019
996     2019
997     2019
998     2019
999     2019
1000    2019
1001    2019
1002    2019
1003    2019
1004    2020
1005    2020
1006    2020
1007    2020
1008    2020
1009    2020
1010    2020
1011    2020
1012    2020
1013    2020
1014    2020
1015    2020
1016    2020
1017    2020
1018    2020
1019    2020
1020    2020
1021    2020
1022    2020
1023    2020
1024    2020
1025    2020
1026    2020
1027    2020
1028    2020
1029    2020
1030    2020
1031    2020
1032    2020
1033    2020
1034    2020
1035    2020
1036    2020
1037    2020
1038    2020
1039    2020
1040    2020
1041    2020
1042    2020
1043    2020
1044    2021
1045    2021
1046    2021
1047    2021
1048    2021
1049    2021
1050    2021
1051    2021
1052    2021
1053    2021
1054    2021
1055    2021
1056    2021
1057    2021
1058    2021
1059    2021
1060    2021
1061    2021
1062    2021
1063    2021
1064    2021
1065    2021
1066    2021
1067    2021
1068    2021
1069    2021
1070    2021
1071    2021
1072    2021
1073    2021
1074    2021
1075    2021
1076    2021
1077    2021
1078    2021
1079    2021
1080    2021
1081    2021
1082    2021
1083    2021
1084    2022
1085    2022
1086    2022
1087    2022
1088    2022
1089    2022
1090    2022
1091    2022
1092    2022
1093    2022
1094    2022
1095    2022
1096    2022
1097    2022
1098    2022
1099    2022
1100    2022
1101    2022
1102    2022
1103    2022
1104    2022
1105    2022
1106    2022
1107    2022
1108    2022
1109    2022
1110    2022
1111    2022
1112    2022
1113    2022
1114    2022
1115    2022
1116    2022
1117    2022
1118    2022
1119    2022
1120    2022
1121    2022
1122    2022
1123    2022
1124    2023
1125    2023
1126    2023
1127    2023
1128    2023
1129    2023
1130    2023
1131    2023
1132    2023
1133    2023
1134    2023
1135    2023
1136    2023
1137    2023
1138    2023
1139    2023
1140    2023
1141    2023
1142    2023
1143    2023
1144    2023
1145    2023
1146    2023
1147    2023
1148    2023
1149    2023
1150    2023
1151    2023
1152    2023
1153    2023
1154    2023
1155    2023
1156    2023
1157    2023
1158    2023
1159    2023
1160    2023
1161    2023
1162    2023
1163    2023
1164    2024
1165    2024
1166    2024
1167    2024
1168    2024
1169    2024
1170    2024
1171    2024
1172    2024
1173    2024
1174    2024
1175    2024
1176    2024
1177    2024
1178    2024
1179    2024
1180    2024
1181    2024
1182    2024
1183    2024
1184    2024
1185    2024
1186    2024
1187    2024
1188    2024
1189    2024
1190    2024
1191    2024
1192    2024
1193    2024
1194    2024
1195    2024
1196    2024
1197    2024
1198    2024
1199    2024
1200    2024
1201    2024
1202    2024
1203    2024
1204    2018
1205    2018
1206    2018
1207    2018
1208    2019
1209    2019
1210    2019
1211    2019
1212    2020
1213    2020
1214    2020
1215    2020
1216    2021
1217    2021
1218    2021
1219    2021
1220    2022
1221    2022
1222    2022
1223    2022
1224    2023
1225    2023
1226    2023
1227    2023
1228    2024
1229    2024
1230    2024
1231    2024
1232    2018
1233    2018
1234    2018
1235    2018
1236    2018
1237    2018
1238    2018
1239    2018
1240    2018
1241    2018
1242    2018
1243    2018
1244    2018
1245    2018
1246    2018
1247    2018
1248    2018
1249    2018
1250    2018
1251    2018
1252    2018
1253    2018
1254    2018
1255    2018
1256    2018
1257    2018
1258    2018
1259    2018
1260    2018
1261    2018
1262    2018
1263    2018
1264    2018
1265    2018
1266    2018
1267    2018
1268    2018
1269    2018
1270    2018
1271    2018
1272    2019
1273    2019
1274    2019
1275    2019
1276    2019
1277    2019
1278    2019
1279    2019
1280    2019
1281    2019
1282    2019
1283    2019
1284    2019
1285    2019
1286    2019
1287    2019
1288    2019
1289    2019
1290    2019
1291    2019
1292    2019
1293    2019
1294    2019
1295    2019
1296    2019
1297    2019
1298    2019
1299    2019
1300    2019
1301    2019
1302    2019
1303    2019
1304    2019
1305    2019
1306    2019
1307    2019
1308    2019
1309    2019
1310    2019
1311    2019
1312    2020
1313    2020
1314    2020
1315    2020
1316    2020
1317    2020
1318    2020
1319    2020
1320    2020
1321    2020
1322    2020
1323    2020
1324    2020
1325    2020
1326    2020
1327    2020
1328    2020
1329    2020
1330    2020
1331    2020
1332    2020
1333    2020
1334    2020
1335    2020
1336    2020
1337    2020
1338    2020
1339    2020
1340    2020
1341    2020
1342    2020
1343    2020
1344    2020
1345    2020
1346    2020
1347    2020
1348    2020
1349    2020
1350    2020
1351    2020
1352    2021
1353    2021
1354    2021
1355    2021
1356    2021
1357    2021
1358    2021
1359    2021
1360    2021
1361    2021
1362    2021
1363    2021
1364    2021
1365    2021
1366    2021
1367    2021
1368    2021
1369    2021
1370    2021
1371    2021
1372    2021
1373    2021
1374    2021
1375    2021
1376    2021
1377    2021
1378    2021
1379    2021
1380    2021
1381    2021
1382    2021
1383    2021
1384    2021
1385    2021
1386    2021
1387    2021
1388    2021
1389    2021
1390    2021
1391    2021
1392    2022
1393    2022
1394    2022
1395    2022
1396    2022
1397    2022
1398    2022
1399    2022
1400    2022
1401    2022
1402    2022
1403    2022
1404    2022
1405    2022
1406    2022
1407    2022
1408    2022
1409    2022
1410    2022
1411    2022
1412    2022
1413    2022
1414    2022
1415    2022
1416    2022
1417    2022
1418    2022
1419    2022
1420    2022
1421    2022
1422    2022
1423    2022
1424    2022
1425    2022
1426    2022
1427    2022
1428    2022
1429    2022
1430    2022
1431    2022
1432    2023
1433    2023
1434    2023
1435    2023
1436    2023
1437    2023
1438    2023
1439    2023
1440    2023
1441    2023
1442    2023
1443    2023
1444    2023
1445    2023
1446    2023
1447    2023
1448    2023
1449    2023
1450    2023
1451    2023
1452    2023
1453    2023
1454    2023
1455    2023
1456    2023
1457    2023
1458    2023
1459    2023
1460    2023
1461    2023
1462    2023
1463    2023
1464    2023
1465    2023
1466    2023
1467    2023
1468    2023
1469    2023
1470    2023
1471    2023
1472    2024
1473    2024
1474    2024
1475    2024
1476    2024
1477    2024
1478    2024
1479    2024
1480    2024
1481    2024
1482    2024
1483    2024
1484    2024
1485    2024
1486    2024
1487    2024
1488    2024
1489    2024
1490    2024
1491    2024
1492    2024
1493    2024
1494    2024
1495    2024
1496    2024
1497    2024
1498    2024
1499    2024
1500    2024
1501    2024
1502    2024
1503    2024
1504    2024
1505    2024
1506    2024
1507    2024
1508    2024
1509    2024
1510    2024
1511    2024
1512    2018
1513    2018
1514    2018
1515    2018
1516    2018
1517    2018
1518    2018
1519    2018
1520    2018
1521    2018
1522    2018
1523    2018
1524    2019
1525    2019
1526    2019
1527    2019
1528    2019
1529    2019
1530    2019
1531    2019
1532    2019
1533    2019
1534    2019
1535    2019
1536    2020
1537    2020

In [279]:
# import pandas as pd
# import json
# import os

# df = df_grp_top_user

# fig = px.choropleth(
#     df,
#     geojson="https://gist.githubusercontent.com/jbrobst/56c13bbbf9d97d187fea01ca62ea5112/raw/e388c4cae20aa53cb5090210a42ebb9b765c0a36/india_states.geojson",
#     featureidkey='properties.ST_NM',
#     locations='State',
#     color='Registered_users',
#     color_continuous_scale='Turbo'
# )

# fig.update_geos(fitbounds="locations", visible=False)
# fig.update_layout(title_text='Agg Users by State in India')

# fig.show()

In [280]:
# TOP Insurance

In [281]:
import os

path = "D:/Movies/Guvi_2/PhonePe/phonepe-pulse/data/top/insurance/country/india/state/"

top_ins_list=os.listdir(path)
top_ins_list
#Agg_state_list--> to get the list of states in India

#<------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------>#

#This is to extract the data's to create a dataframe

clm = {
    'State': [],
    'Year': [],
    'Quarter': [],
    'District': [],
    'Transaction_count': [],
    'Transaction_amount': []
}

for i in top_ins_list:                
    p_i = path + i + "/"
    map_yr = os.listdir(p_i)
    for j in map_yr:                    
        p_j = p_i + j + "/"
        map_yr_list = os.listdir(p_j)
        for k in map_yr_list:           
            p_k = p_j + k
            with open(p_k, 'r') as Data:
                D = json.load(Data)
                for z in D['data']['districts']:
                    district = z['entityName']
                    count = z['metric']['count']
                    amount = z['metric']['amount']
                    clm['District'].append(district)
                    clm['Transaction_count'].append(count)
                    clm['Transaction_amount'].append(amount)
                    clm['State'].append(i)
                    clm['Year'].append(j)
                    clm['Quarter'].append(int(k.strip('.json')))
top_ins=pd.DataFrame(clm)

In [282]:
top_ins.head()

,State,Year,Quarter,District,Transaction_count,Transaction_amount
0,andaman-&-nicobar-islands,2020,2,nicobars,3,565.0
1,andaman-&-nicobar-islands,2020,2,south andaman,3,795.0
2,andaman-&-nicobar-islands,2020,3,south andaman,35,13651.0
3,andaman-&-nicobar-islands,2020,3,nicobars,5,1448.0
4,andaman-&-nicobar-islands,2020,3,north and middle andaman,1,281.0

In [283]:
import re
def modify(s):
    s = s.replace('-', ' ')
    return ' '.join(word.capitalize() for word in s.split())

top_ins['State'] = top_ins['State'].apply(modify)
top_ins['District'] = top_ins['District'].apply(modify)

update_cat = {
    "Andaman & Nicobar Islands": "Andaman & Nicobar",
    "Dadra & Nagar Haveli & Daman & Diu": "Dadra and Nagar Haveli and Daman and Diu"
}

top_ins['State'] = top_ins['State'].replace(update_cat)

In [284]:
top_ins.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5608 entries, 0 to 5607
Data columns (total 6 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   State               5608 non-null   object
 1   Year                5608 non-null   object
 2   Quarter             5608 non-null   int64
 3   District            5608 non-null   object
 4   Transaction_count   5608 non-null   int64
 5   Transaction_amount  5608 non-null   float64
dtypes: float64(1), int64(2), object(3)
memory usage: 263.0+ KB

In [285]:
top_ins['Year'] = pd.to_datetime(top_ins['Year']).dt.year

top_ins['Year'].info()
top_ins['Year']

<class 'pandas.core.series.Series'>
RangeIndex: 5608 entries, 0 to 5607
Series name: Year
Non-Null Count  Dtype
--------------  -----
5608 non-null   int32
dtypes: int32(1)
memory usage: 22.0 KB

0       2020
1       2020
2       2020
3       2020
4       2020
5       2020
6       2020
7       2020
8       2021
9       2021
10      2021
11      2021
12      2021
13      2021
14      2021
15      2021
16      2021
17      2021
18      2021
19      2021
20      2022
21      2022
22      2022
23      2022
24      2022
25      2022
26      2022
27      2022
28      2022
29      2022
30      2022
31      2022
32      2023
33      2023
34      2023
35      2023
36      2023
37      2023
38      2023
39      2023
40      2023
41      2023
42      2023
43      2023
44      2024
45      2024
46      2024
47      2024
48      2024
49      2024
50      2024
51      2024
52      2024
53      2024
54      2024
55      2024
56      2024
57      2020
58      2020
59      2020
60      2020
61      2020
62      2020
63      2020
64      2020
65      2020
66      2020
67      2020
68      2020
69      2020
70      2020
71      2020
72      2020
73      2020
74      2020
75      2020
76      2020
77      2020
78      2020
79      2020
80      2020
81      2020
82      2020
83      2020
84      2020
85      2020
86      2020
87      2021
88      2021
89      2021
90      2021
91      2021
92      2021
93      2021
94      2021
95      2021
96      2021
97      2021
98      2021
99      2021
100     2021
101     2021
102     2021
103     2021
104     2021
105     2021
106     2021
107     2021
108     2021
109     2021
110     2021
111     2021
112     2021
113     2021
114     2021
115     2021
116     2021
117     2021
118     2021
119     2021
120     2021
121     2021
122     2021
123     2021
124     2021
125     2021
126     2021
127     2022
128     2022
129     2022
130     2022
131     2022
132     2022
133     2022
134     2022
135     2022
136     2022
137     2022
138     2022
139     2022
140     2022
141     2022
142     2022
143     2022
144     2022
145     2022
146     2022
147     2022
148     2022
149     2022
150     2022
151     2022
152     2022
153     2022
154     2022
155     2022
156     2022
157     2022
158     2022
159     2022
160     2022
161     2022
162     2022
163     2022
164     2022
165     2022
166     2022
167     2023
168     2023
169     2023
170     2023
171     2023
172     2023
173     2023
174     2023
175     2023
176     2023
177     2023
178     2023
179     2023
180     2023
181     2023
182     2023
183     2023
184     2023
185     2023
186     2023
187     2023
188     2023
189     2023
190     2023
191     2023
192     2023
193     2023
194     2023
195     2023
196     2023
197     2023
198     2023
199     2023
200     2023
201     2023
202     2023
203     2023
204     2023
205     2023
206     2023
207     2024
208     2024
209     2024
210     2024
211     2024
212     2024
213     2024
214     2024
215     2024
216     2024
217     2024
218     2024
219     2024
220     2024
221     2024
222     2024
223     2024
224     2024
225     2024
226     2024
227     2024
228     2024
229     2024
230     2024
231     2024
232     2024
233     2024
234     2024
235     2024
236     2024
237     2024
238     2024
239     2024
240     2024
241     2024
242     2024
243     2024
244     2024
245     2024
246     2024
247     2020
248     2020
249     2020
250     2020
251     2020
252     2020
253     2020
254     2020
255     2020
256     2020
257     2020
258     2020
259     2020
260     2020
261     2020
262     2020
263     2020
264     2020
265     2020
266     2020
267     2020
268     2020
269     2020
270     2020
271     2020
272     2020
273     2020
274     2020
275     2020
276     2020
277     2021
278     2021
279     2021
280     2021
281     2021
282     2021
283     2021
284     2021
285     2021
286     2021
287     2021
288     2021
289     2021
290     2021
291     2021
292     2021
293     2021
294     2021
295     2021
296     2021
297     2021
298     2021
299     2021
300     2021
301     2021
302     2021
303     2021
304     2021
305     2021
306     2021
307     2021
308     2021
309     2021
310     2021
311     2021
312     2021
313     2021
314     2021
315     2021
316     2021
317     2022
318     2022
319     2022
320     2022
321     2022
322     2022
323     2022
324     2022
325     2022
326     2022
327     2022
328     2022
329     2022
330     2022
331     2022
332     2022
333     2022
334     2022
335     2022
336     2022
337     2022
338     2022
339     2022
340     2022
341     2022
342     2022
343     2022
344     2022
345     2022
346     2022
347     2022
348     2022
349     2022
350     2022
351     2022
352     2022
353     2022
354     2022
355     2022
356     2022
357     2023
358     2023
359     2023
360     2023
361     2023
362     2023
363     2023
364     2023
365     2023
366     2023
367     2023
368     2023
369     2023
370     2023
371     2023
372     2023
373     2023
374     2023
375     2023
376     2023
377     2023
378     2023
379     2023
380     2023
381     2023
382     2023
383     2023
384     2023
385     2023
386     2023
387     2023
388     2023
389     2023
390     2023
391     2023
392     2023
393     2023
394     2023
395     2023
396     2023
397     2024
398     2024
399     2024
400     2024
401     2024
402     2024
403     2024
404     2024
405     2024
406     2024
407     2024
408     2024
409     2024
410     2024
411     2024
412     2024
413     2024
414     2024
415     2024
416     2024
417     2024
418     2024
419     2024
420     2024
421     2024
422     2024
423     2024
424     2024
425     2024
426     2024
427     2024
428     2024
429     2024
430     2024
431     2024
432     2024
433     2024
434     2024
435     2024
436     2024
437     2020
438     2020
439     2020
440     2020
441     2020
442     2020
443     2020
444     2020
445     2020
446     2020
447     2020
448     2020
449     2020
450     2020
451     2020
452     2020
453     2020
454     2020
455     2020
456     2020
457     2020
458     2020
459     2020
460     2020
461     2020
462     2020
463     2020
464     2020
465     2020
466     2020
467     2021
468     2021
469     2021
470     2021
471     2021
472     2021
473     2021
474     2021
475     2021
476     2021
477     2021
478     2021
479     2021
480     2021
481     2021
482     2021
483     2021
484     2021
485     2021
486     2021
487     2021
488     2021
489     2021
490     2021
491     2021
492     2021
493     2021
494     2021
495     2021
496     2021
497     2021
498     2021
499     2021
500     2021
501     2021
502     2021
503     2021
504     2021
505     2021
506     2021
507     2022
508     2022
509     2022
510     2022
511     2022
512     2022
513     2022
514     2022
515     2022
516     2022
517     2022
518     2022
519     2022
520     2022
521     2022
522     2022
523     2022
524     2022
525     2022
526     2022
527     2022
528     2022
529     2022
530     2022
531     2022
532     2022
533     2022
534     2022
535     2022
536     2022
537     2022
538     2022
539     2022
540     2022
541     2022
542     2022
543     2022
544     2022
545     2022
546     2022
547     2023
548     2023
549     2023
550     2023
551     2023
552     2023
553     2023
554     2023
555     2023
556     2023
557     2023
558     2023
559     2023
560     2023
561     2023
562     2023
563     2023
564     2023
565     2023
566     2023
567     2023
568     2023
569     2023
570     2023
571     2023
572     2023
573     2023
574     2023
575     2023
576     2023
577     2023
578     2023
579     2023
580     2023
581     2023
582     2023
583     2023
584     2023
585     2023
586     2023
587     2024
588     2024
589     2024
590     2024
591     2024
592     2024
593     2024
594     2024
595     2024
596     2024
597     2024
598     2024
599     2024
600     2024
601     2024
602     2024
603     2024
604     2024
605     2024
606     2024
607     2024
608     2024
609     2024
610     2024
611     2024
612     2024
613     2024
614     2024
615     2024
616     2024
617     2024
618     2024
619     2024
620     2024
621     2024
622     2024
623     2024
624     2024
625     2024
626     2024
627     2020
628     2020
629     2020
630     2020
631     2020
632     2020
633     2020
634     2020
635     2020
636     2020
637     2020
638     2020
639     2020
640     2020
641     2020
642     2020
643     2020
644     2020
645     2020
646     2020
647     2020
648     2020
649     2020
650     2020
651     2020
652     2020
653     2020
654     2020
655     2020
656     2020
657     2021
658     2021
659     2021
660     2021
661     2021
662     2021
663     2021
664     2021
665     2021
666     2021
667     2021
668     2021
669     2021
670     2021
671     2021
672     2021
673     2021
674     2021
675     2021
676     2021
677     2021
678     2021
679     2021
680     2021
681     2021
682     2021
683     2021
684     2021
685     2021
686     2021
687     2021
688     2021
689     2021
690     2021
691     2021
692     2021
693     2021
694     2021
695     2021
696     2021
697     2022
698     2022
699     2022
700     2022
701     2022
702     2022
703     2022
704     2022
705     2022
706     2022
707     2022
708     2022
709     2022
710     2022
711     2022
712     2022
713     2022
714     2022
715     2022
716     2022
717     2022
718     2022
719     2022
720     2022
721     2022
722     2022
723     2022
724     2022
725     2022
726     2022
727     2022
728     2022
729     2022
730     2022
731     2022
732     2022
733     2022
734     2022
735     2022
736     2022
737     2023
738     2023
739     2023
740     2023
741     2023
742     2023
743     2023
744     2023
745     2023
746     2023
747     2023
748     2023
749     2023
750     2023
751     2023
752     2023
753     2023
754     2023
755     2023
756     2023
757     2023
758     2023
759     2023
760     2023
761     2023
762     2023
763     2023
764     2023
765     2023
766     2023
767     2023
768     2023
769     2023
770     2023
771     2023
772     2023
773     2023
774     2023
775     2023
776     2023
777     2024
778     2024
779     2024
780     2024
781     2024
782     2024
783     2024
784     2024
785     2024
786     2024
787     2024
788     2024
789     2024
790     2024
791     2024
792     2024
793     2024
794     2024
795     2024
796     2024
797     2024
798     2024
799     2024
800     2024
801     2024
802     2024
803     2024
804     2024
805     2024
806     2024
807     2024
808     2024
809     2024
810     2024
811     2024
812     2024
813     2024
814     2024
815     2024
816     2024
817     2020
818     2020
819     2020
820     2021
821     2021
822     2021
823     2021
824     2022
825     2022
826     2022
827     2022
828     2023
829     2023
830     2023
831     2023
832     2024
833     2024
834     2024
835     2024
836     2020
837     2020
838     2020
839     2020
840     2020
841     2020
842     2020
843     2020
844     2020
845     2020
846     2020
847     2020
848     2020
849     2020
850     2020
851     2020
852     2020
853     2020
854     2020
855     2020
856     2020
857     2020
858     2020
859     2020
860     2020
861     2020
862     2020
863     2020
864     2020
865     2020
866     2021
867     2021
868     2021
869     2021
870     2021
871     2021
872     2021
873     2021
874     2021
875     2021
876     2021
877     2021
878     2021
879     2021
880     2021
881     2021
882     2021
883     2021
884     2021
885     2021
886     2021
887     2021
888     2021
889     2021
890     2021
891     2021
892     2021
893     2021
894     2021
895     2021
896     2021
897     2021
898     2021
899     2021
900     2021
901     2021
902     2021
903     2021
904     2021
905     2021
906     2022
907     2022
908     2022
909     2022
910     2022
911     2022
912     2022
913     2022
914     2022
915     2022
916     2022
917     2022
918     2022
919     2022
920     2022
921     2022
922     2022
923     2022
924     2022
925     2022
926     2022
927     2022
928     2022
929     2022
930     2022
931     2022
932     2022
933     2022
934     2022
935     2022
936     2022
937     2022
938     2022
939     2022
940     2022
941     2022
942     2022
943     2022
944     2022
945     2022
946     2023
947     2023
948     2023
949     2023
950     2023
951     2023
952     2023
953     2023
954     2023
955     2023
956     2023
957     2023
958     2023
959     2023
960     2023
961     2023
962     2023
963     2023
964     2023
965     2023
966     2023
967     2023
968     2023
969     2023
970     2023
971     2023
972     2023
973     2023
974     2023
975     2023
976     2023
977     2023
978     2023
979     2023
980     2023
981     2023
982     2023
983     2023
984     2023
985     2023
986     2024
987     2024
988     2024
989     2024
990     2024
991     2024
992     2024
993     2024
994     2024
995     2024
996     2024
997     2024
998     2024
999     2024
1000    2024
1001    2024
1002    2024
1003    2024
1004    2024
1005    2024
1006    2024
1007    2024
1008    2024
1009    2024
1010    2024
1011    2024
1012    2024
1013    2024
1014    2024
1015    2024
1016    2024
1017    2024
1018    2024
1019    2024
1020    2024
1021    2024
1022    2024
1023    2024
1024    2024
1025    2024
1026    2020
1027    2020
1028    2020
1029    2020
1030    2020
1031    2020
1032    2020
1033    2020
1034    2020
1035    2021
1036    2021
1037    2021
1038    2021
1039    2021
1040    2021
1041    2021
1042    2021
1043    2021
1044    2021
1045    2021
1046    2021
1047    2022
1048    2022
1049    2022
1050    2022
1051    2022
1052    2022
1053    2022
1054    2022
1055    2022
1056    2022
1057    2022
1058    2022
1059    2023
1060    2023
1061    2023
1062    2023
1063    2023
1064    2023
1065    2023
1066    2023
1067    2023
1068    2023
1069    2023
1070    2023
1071    2024
1072    2024
1073    2024
1074    2024
1075    2024
1076    2024
1077    2024
1078    2024
1079    2024
1080    2024
1081    2024
1082    2024
1083    2020
1084    2020
1085    2020
1086    2020
1087    2020
1088    2020
1089    2020
1090    2020
1091    2020
1092    2020
1093    2020
1094    2020
1095    2020
1096    2020
1097    2020
1098    2020
1099    2020
1100    2020
1101    2020
1102    2020
1103    2020
1104    2020
1105    2020
1106    2020
1107    2020
1108    2020
1109    2020
1110    2020
1111    2020
1112    2020
1113    2021
1114    2021
1115    2021
1116    2021
1117    2021
1118    2021
1119    2021
1120    2021
1121    2021
1122    2021
1123    2021
1124    2021
1125    2021
1126    2021
1127    2021
1128    2021
1129    2021
1130    2021
1131    2021
1132    2021
1133    2021
1134    2021
1135    2021
1136    2021
1137    2021
1138    2021
1139    2021
1140    2021
1141    2021
1142    2021
1143    2021
1144    2021
1145    2021
1146    2021
1147    2021
1148    2021
1149    2021
1150    2021
1151    2021
1152    2021
1153    2022
1154    2022
1155    2022
1156    2022
1157    2022
1158    2022
1159    2022
1160    2022
1161    2022
1162    2022
1163    2022
1164    2022
1165    2022
1166    2022
1167    2022
1168    2022
1169    2022
1170    2022
1171    2022
1172    2022
1173    2022
1174    2022
1175    2022
1176    2022
1177    2022
1178    2022
1179    2022
1180    2022
1181    2022
1182    2022
1183    2022
1184    2022
1185    2022
1186    2022
1187    2022
1188    2022
1189    2022
1190    2022
1191    2022
1192    2022
1193    2023
1194    2023
1195    2023
1196    2023
1197    2023
1198    2023
1199    2023
1200    2023
1201    2023
1202    2023
1203    2023
1204    2023
1205    2023
1206    2023
1207    2023
1208    2023
1209    2023
1210    2023
1211    2023
1212    2023
1213    2023
1214    2023
1215    2023
1216    2023
1217    2023
1218    2023
1219    2023
1220    2023
1221    2023
1222    2023
1223    2023
1224    2023
1225    2023
1226    2023
1227    2023
1228    2023
1229    2023
1230    2023
1231    2023
1232    2023
1233    2024
1234    2024
1235    2024
1236    2024
1237    2024
1238    2024
1239    2024
1240    2024
1241    2024
1242    2024
1243    2024
1244    2024
1245    2024
1246    2024
1247    2024
1248    2024
1249    2024
1250    2024
1251    2024
1252    2024
1253    2024
1254    2024
1255    2024
1256    2024
1257    2024
1258    2024
1259    2024
1260    2024
1261    2024
1262    2024
1263    2024
1264    2024
1265    2024
1266    2024
1267    2024
1268    2024
1269    2024
1270    2024
1271    2024
1272    2024
1273    2020
1274    2020
1275    2020
1276    2020
1277    2020
1278    2020
1279    2021
1280    2021
1281    2021
1282    2021
1283    2021
1284    2021
1285    2021
1286    2021
1287    2022
1288    2022
1289    2022
1290    2022
1291    2022
1292    2022
1293    2022
1294    2022
1295    2023
1296    2023
1297    2023
1298    2023
1299    2023
1300    2023
1301    2023
1302    2023
1303    2024
1304    2024
1305    2024
1306    2024
1307    2024
1308    2024
1309    2024
1310    2024
1311    2020
1312    2020
1313    2020
1314    2020
1315    2020
1316    2020
1317    2020
1318    2020
1319    2020
1320    2020
1321    2020
1322    2020
1323    2020
1324    2020
1325    2020
1326    2020
1327    2020
1328    2020
1329    2020
1330    2020
1331    2020
1332    2020
1333    2020
1334    2020
1335    2020
1336    2020
1337    2020
1338    2020
1339    2020
1340    2020
1341    2021
1342    2021
1343    2021
1344    2021
1345    2021
1346    2021
1347    2021
1348    2021
1349    2021
1350    2021
1351    2021
1352    2021
1353    2021
1354    2021
1355    2021
1356    2021
1357    2021
1358    2021
1359    2021
1360    2021
1361    2021
1362    2021
1363    2021
1364    2021
1365    2021
1366    2021
1367    2021
1368    2021
1369    2021
1370    2021
1371    2021
1372    2021
1373    2021
1374    2021
1375    2021
1376    2021
1377    2021
1378    2021
1379    2021
1380    2021
1381    2022
1382    2022
1383    2022
1384    2022
1385    2022
1386    2022
1387    2022
1388    2022
1389    2022
1390    2022
1391    2022
1392    2022
1393    2022
1394    2022
1395    2022
1396    2022
1397    2022
1398    2022
1399    2022
1400    2022
1401    2022
1402    2022
1403    2022
1404    2022
1405    2022
1406    2022
1407    2022
1408    2022
1409    2022
1410    2022
1411    2022
1412    2022
1413    2022
1414    2022
1415    2022
1416    2022
1417    2022
1418    2022
1419    2022
1420    2022
1421    2023
1422    2023
1423    2023
1424    2023
1425    2023
1426    2023
1427    2023
1428    2023
1429    2023
1430    2023
1431    2023
1432    2023
1433    2023
1434    2023
1435    2023
1436    2023
1437    2023
1438    2023
1439    2023
1440    2023
1441    2023
1442    2023
1443    2023
1444    2023
1445    2023
1446    2023
1447    2023
1448    2023
1449    2023
1450    2023
1451    2023
1452    2023
1453    2023
1454    2023
1455    2023
1456    2023
1457    2023
1458    2023
1459    2023
1460    2023
1461    2024
1462    2024
1463    2024
1464    2024
1465    2024
1466    2024
1467    2024
1468    2024
1469    2024
1470    2024
1471    2024
1472    2024
1473    2024
1474    2024
1475    2024
1476    2024
1477    2024
1478    2024
1479    2024
1480    2024
1481    2024
1482    2024
1483    2024
1484    2024
1485    2024
1486    2024
1487    2024
1488    2024
1489    2024
1490    2024
1491    2024
1492    2024
1493    2024
1494    2024
1495    2024
1496    2024
1497    2024
1498    2024
1499    2024
1500    2024
1501    2020
1502    2020
1503    2020
1504    2020
1505    2020
1506    2020
1507    2020
1508    2020
1509    2020
1510    2020
1511    2020
1512    2020
1513    2020
1514    2020
1515    2020
1516    2020
1517    2020
1518    2020
1519    2020
1520    2020
1521    2020
1522    2020
1523    2020
1524    2020
1525    2020
1526    2020
1527    2020
1528    2020
1529    2020
1530    2020
1531    2021
1532    2021
1533    2021
1534    2021
1535    2021
1536    2021
1537    2021

In [286]:
df_grp_top_ins = top_ins.groupby('State')['Transaction_count'].sum().reset_index()
df_grp_top_ins.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 36 entries, 0 to 35
Data columns (total 2 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   State              36 non-null     object
 1   Transaction_count  36 non-null     int64
dtypes: int64(1), object(1)
memory usage: 708.0+ bytes

In [287]:
import pandas as pd
import json
import os

df = df_grp_top_ins

fig = px.choropleth(
    df,
    geojson="https://gist.githubusercontent.com/jbrobst/56c13bbbf9d97d187fea01ca62ea5112/raw/e388c4cae20aa53cb5090210a42ebb9b765c0a36/india_states.geojson",
    featureidkey='properties.ST_NM',
    locations='State',
    color='Transaction_count',
    color_continuous_scale='Oranges'
)

fig.update_geos(fitbounds="locations", visible=False)
fig.update_layout(title_text='Map Insurance Transactions by State in India')

fig.show()

In [288]:

# connecting with postgreSQL
!pip install psycopg;
!pip install sqlalchemy psycopg pandas;

Requirement already satisfied: psycopg in c:\users\farooque\anaconda3\lib\site-packages (3.2.9)
Requirement already satisfied: typing-extensions>=4.6 in c:\users\farooque\anaconda3\lib\site-packages (from psycopg) (4.11.0)
Requirement already satisfied: tzdata in c:\users\farooque\anaconda3\lib\site-packages (from psycopg) (2023.3)
Requirement already satisfied: sqlalchemy in c:\users\farooque\anaconda3\lib\site-packages (2.0.34)
Requirement already satisfied: psycopg in c:\users\farooque\anaconda3\lib\site-packages (3.2.9)
Requirement already satisfied: pandas in c:\users\farooque\anaconda3\lib\site-packages (2.2.2)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\farooque\anaconda3\lib\site-packages (from sqlalchemy) (4.11.0)
Requirement already satisfied: greenlet!=0.4.17 in c:\users\farooque\anaconda3\lib\site-packages (from sqlalchemy) (3.0.1)
Requirement already satisfied: tzdata in c:\users\farooque\anaconda3\lib\site-packages (from psycopg) (2023.3)
Requirement already satisfied: numpy>=1.26.0 in c:\users\farooque\anaconda3\lib\site-packages (from pandas) (1.26.4)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\farooque\anaconda3\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\farooque\anaconda3\lib\site-packages (from pandas) (2024.1)
Requirement already satisfied: six>=1.5 in c:\users\farooque\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)

In [289]:
import psycopg

In [290]:
connect = psycopg.connect(
    dbname = "postgres",
    host = "localhost",
    user = "postgres",
    password = "Greybentley@123",
    port= 5432

)
cursor = connect.cursor()

In [291]:
connect.autocommit = True

In [292]:
from sqlalchemy import create_engine,text

engine = create_engine(
    "postgresql+psycopg://postgres:Greybentley%40123@127.0.0.1:5432/phonepe_data"
)

In [293]:
try:
    with engine.connect() as conn:
        print("✅ SQL Alchemy connected to PostgreSQL")
except Exception as e:
    print("❌ Connection failed:", e)

✅ SQL Alchemy connected to PostgreSQL

In [294]:
# AGG tables 

agg_trans.to_sql(
    name="agg_trans",
    con=engine,
    if_exists="append",
    index=False
)


agg_ins.to_sql(
    name="agg_ins",
    con=engine,
    if_exists="append",
    index=False
)

agg_user.to_sql(
    name="agg_user",
    con=engine,
    if_exists="append",
    index=False
)


# MAP tables

map_trans.to_sql(
    name="map_trans",
    con=engine,
    if_exists="append",
    index=False
)

map_ins.to_sql(
    name="map_ins",
    con=engine,
    if_exists="append",
    index=False
)

map_user_list.to_sql(
    name="map_user_list",
    con=engine,
    if_exists="append",
    index=False
)

#TOP TABLE 

top_trans.to_sql(
    name="top_trans",
    con=engine,
    if_exists="append",
    index=False
)


top_ins.to_sql(
    name="top_ins",
    con=engine,
    if_exists="append",
    index=False
)

top_user_list.to_sql(
    name="top_user_list",
    con=engine,
    if_exists="append",
    index=False
)

-1

In [295]:
# try:
#     with engine.connect() as conn:
#         print("✅ SQLAlchemy connected to PostgreSQL")
# except Exception as e:
#     print("❌ Connection failed:", e)

In [296]:
# # DELETE TABLES

# tables = [
    
#     "agg_trans",
#     "agg_ins",
#     "agg_user",
#     "map_trans",
#     "map_ins",
#     "map_user_list",
#     "top_trans",
#     "top_ins",
#     "top_user_list"
# ]
# 6     
# with engine.connect() as conn:
#     for table in tables:
#         conn.execute(text(f"DROP TABLE IF EXISTS {table} CASCADE;"))
#     conn.commit()
#     print("✅  table deleted successfully")

In [297]:
query = """
SELECT table_name
FROM information_schema.tables
WHERE table_schema = 'public';
"""

df = pd.read_sql_query(query, engine)
print(df)

      table_name
0      agg_trans
1        agg_ins
2       agg_user
3      map_trans
4        map_ins
5  map_user_list
6      top_trans
7        top_ins
8  top_user_list

In [298]:
query = """
SELECT column_name, data_type
FROM information_schema.columns
WHERE table_schema = 'public'
  AND table_name = 'map_trans';
"""

df = pd.read_sql_query(query, engine)
df

          column_name         data_type
0               State              text
1                Year           integer
2              Quater            bigint
3    Transaction_type              text
4   Transaction_count            bigint
5  Transaction_amount  double precision

In [299]:
# Scenario - 1

# 1. Decoding Transaction Dynamics on PhonePe

# PhonePe, a leading digital payments platform, 
# has recently identified significant variations in transaction behavior across states, quarters, 
# and payment categories.
# While some regions and transaction types demonstrate consistent growth,
# thers show stagnation or decline.
# The leadership team seeks a deeper understanding of these patterns to drive targeted business strategies.

In [300]:
# States with higher digital adoption contribute significantly to overall transaction volume.

state_trn = agg_trans.groupby('State')[['Transaction_count','Transaction_amount']] \
                     .sum().reset_index()
state_trn.sort_values(by='Transaction_count', ascending=False).head(10)

             State  Transaction_count  Transaction_amount
20     Maharashtra        31985208732        4.037420e+13
15       Karnataka        30970946279        4.067872e+13
31       Telangana        26174684592        4.165596e+13
1   Andhra Pradesh        18918696723        3.466908e+13
33   Uttar Pradesh        18523603727        2.688521e+13
28       Rajasthan        17108537898        2.634324e+13
19  Madhya Pradesh        14072176059        1.912528e+13
4            Bihar        10941026824        1.790135e+13
35     West Bengal         9191499687        1.558416e+13
25          Odisha         8918527452        1.226398e+13

In [301]:
# SQL

query = """
                SELECT 
                "State",
                SUM("Transaction_count") AS total_transaction_count
                FROM agg_trans
                GROUP BY "State"
                ORDER BY total_transaction_count DESC
                LIMIT 10;
                
                """

top_states = pd.read_sql_query(query, engine)
top_states

            State  total_transaction_count
0     Maharashtra             3.198521e+10
1       Karnataka             3.097095e+10
2       Telangana             2.617468e+10
3  Andhra Pradesh             1.891870e+10
4   Uttar Pradesh             1.852360e+10
5       Rajasthan             1.710854e+10
6  Madhya Pradesh             1.407218e+10
7           Bihar             1.094103e+10
8     West Bengal             9.191500e+09
9          Odisha             8.918527e+09

In [302]:
# Map Fig


import pandas as pd
import json
import os

df = df_grp # from agg_transactions

fig = px.choropleth(
    df,
    geojson="https://gist.githubusercontent.com/jbrobst/56c13bbbf9d97d187fea01ca62ea5112/raw/e388c4cae20aa53cb5090210a42ebb9b765c0a36/india_states.geojson",
    featureidkey='properties.ST_NM',
    locations='State',
    color='Transaction_count',
    color_continuous_scale='Reds'
)

fig.update_geos(fitbounds="locations", visible=False)

fig.show()

In [303]:
agg_ins.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 682 entries, 0 to 681
Data columns (total 6 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   State               682 non-null    object
 1   Year                682 non-null    int32
 2   Quater              682 non-null    int64
 3   Transaction_type    682 non-null    object
 4   Transaction_count   682 non-null    int64
 5   Transaction_amount  682 non-null    int32
dtypes: int32(2), int64(2), object(2)
memory usage: 26.8+ KB

In [304]:
# Scenario 
# 3. Insurance Penetration and Growth Potential Analysis
#Scenario
#PhonePe has ventured into the insurance domain, providing users with options to secure various policies. 
# With increasing transactions in this segment, the company seeks to analyze its growth trajectory and identify untapped opportunities for insurance adoption at the state level. 
# This data will help prioritize regions for marketing efforts and partnerships with insurers.

In [305]:
high_ins_state = agg_ins.groupby('State')['Transaction_count'].sum().reset_index()
high_ins_state.sort_values(by='Transaction_count', ascending=False).head(10)

             State  Transaction_count
15       Karnataka            1957404
20     Maharashtra            1815539
30      Tamil Nadu            1215269
33   Uttar Pradesh            1139153
31       Telangana             894342
35     West Bengal             839715
16          Kerala             824235
1   Andhra Pradesh             697769
8            Delhi             652514
28       Rajasthan             639684

In [306]:
# I performed state‑wise aggregation of insurance transaction counts using Pandas and 
# validated the same logic using SQL to identify states with the highest insurance adoption

In [307]:
# SQL

query = """
                SELECT 
                "State",
                SUM("Transaction_count") AS total_transaction_count
                FROM agg_ins
                GROUP BY "State"
                ORDER BY total_transaction_count DESC
                LIMIT 10;
                
                """

top_states = pd.read_sql_query(query, engine)
top_states

            State  total_transaction_count
0       Karnataka                1957404.0
1     Maharashtra                1815539.0
2      Tamil Nadu                1215269.0
3   Uttar Pradesh                1139153.0
4       Telangana                 894342.0
5     West Bengal                 839715.0
6          Kerala                 824235.0
7  Andhra Pradesh                 697769.0
8           Delhi                 652514.0
9       Rajasthan                 639684.0

In [308]:
agg_user.head()

,State,Year,Quarter,Registered_users,App_opens,Brand,User_count,User_percentage
0,Andaman & Nicobar,2018,1,6740,0,Xiaomi,1665,0.247033
1,Andaman & Nicobar,2018,1,6740,0,Samsung,1445,0.214392
2,Andaman & Nicobar,2018,1,6740,0,Vivo,982,0.145697
3,Andaman & Nicobar,2018,1,6740,0,Oppo,501,0.074332
4,Andaman & Nicobar,2018,1,6740,0,OnePlus,332,0.049258

In [309]:
# 5. User Engagement and Growth Strategy
# PhonePe seeks to enhance its market position by analyzing user engagement across different states and districts. With a significant number of registered users and app opens, 
# understanding user behavior can provide valuable insights for strategic decision-making and growth opportunities.

In [310]:
# Analyzing state-wise registered users to identify regions with the highest user base.
num_reg_user = agg_user.groupby('State')['Registered_users'].sum().reset_index()
num_reg_user.sort_values(by='Registered_users', ascending=False)

                                       State  Registered_users
20                               Maharashtra        4972825121
33                             Uttar Pradesh        3915665963
15                                 Karnataka        3205100580
1                             Andhra Pradesh        2479563185
28                                 Rajasthan        2372101468
31                                 Telangana        2330985283
35                               West Bengal        2267427525
30                                Tamil Nadu        2130315308
10                                   Gujarat        1988044388
19                            Madhya Pradesh        1987286906
4                                      Bihar        1839927870
8                                      Delhi        1470469429
11                                   Haryana        1340601702
25                                    Odisha        1260386677
16                                    Kerala         843288336
27                                    Punjab         730723972
14                                 Jharkhand         709961956
6                               Chhattisgarh         595506054
3                                      Assam         434295521
34                               Uttarakhand         375772100
12                          Himachal Pradesh         213530196
13                           Jammu & Kashmir         155346708
9                                        Goa          75290424
5                                 Chandigarh          58691270
32                                   Tripura          58299120
26                                Puducherry          44582879
7   Dadra and Nagar Haveli and Daman and Diu          42861709
21                                   Manipur          38270419
2                          Arunachal Pradesh          30861270
24                                  Nagaland          24405227
22                                 Meghalaya          23712084
29                                    Sikkim          20580065
23                                   Mizoram          10229549
17                                    Ladakh           9246424
0                          Andaman & Nicobar           6857906
18                               Lakshadweep            562518

In [311]:
# Analyzing state-wise registered users to identify regions with the highest user base.

# SQL

query = """
                SELECT 
                "State",
                SUM("Registered_users") AS total_reg_user
                FROM agg_user
                GROUP BY "State"
                ORDER BY total_reg_user DESC
                LIMIT 10;
                
                """

reg_usr = pd.read_sql_query(query, engine)
reg_usr

            State  total_reg_user
0     Maharashtra    4.972825e+09
1   Uttar Pradesh    3.915666e+09
2       Karnataka    3.205101e+09
3  Andhra Pradesh    2.479563e+09
4       Rajasthan    2.372101e+09
5       Telangana    2.330985e+09
6     West Bengal    2.267428e+09
7      Tamil Nadu    2.130315e+09
8         Gujarat    1.988044e+09
9  Madhya Pradesh    1.987287e+09

In [312]:
# Analyzing brand popularity based on app opens.

st_op_ap = agg_user.groupby('State')['App_opens'].sum().reset_index()
st_op_ap.sort_values(by='App_opens', ascending=False)

                                       State     App_opens
20                               Maharashtra  130902916881
15                                 Karnataka  121505737078
1                             Andhra Pradesh  102445420418
28                                 Rajasthan  100093362160
31                                 Telangana   92639879035
33                             Uttar Pradesh   72178186487
19                            Madhya Pradesh   71524173336
30                                Tamil Nadu   39578469623
25                                    Odisha   38536362216
4                                      Bihar   37722567135
35                               West Bengal   34139202185
10                                   Gujarat   32833356204
11                                   Haryana   27171892935
8                                      Delhi   24283682984
6                               Chhattisgarh   19289157437
14                                 Jharkhand   18582919839
16                                    Kerala   10436263288
3                                      Assam   10221542419
27                                    Punjab    9517363669
34                               Uttarakhand    7395508890
12                          Himachal Pradesh    3776042127
13                           Jammu & Kashmir    2701659246
9                                        Goa    1470646166
2                          Arunachal Pradesh    1172571323
32                                   Tripura     946642158
21                                   Manipur     741405544
7   Dadra and Nagar Haveli and Daman and Diu     720764308
5                                 Chandigarh     701611790
22                                 Meghalaya     684106731
26                                Puducherry     682759682
24                                  Nagaland     677649346
29                                    Sikkim     467816008
23                                   Mizoram     353093059
17                                    Ladakh     317989606
0                          Andaman & Nicobar     161003601
18                               Lakshadweep       4524025

In [313]:
# SQL

query = """
                SELECT 
                "State",
                SUM("App_opens") AS open_app_count
                FROM agg_user
                GROUP BY "State"
                ORDER BY open_app_count DESC;
                
                
                """

st_open_app = pd.read_sql_query(query, engine)
st_open_app

                                       State  open_app_count
0                                Maharashtra    1.309029e+11
1                                  Karnataka    1.215057e+11
2                             Andhra Pradesh    1.024454e+11
3                                  Rajasthan    1.000934e+11
4                                  Telangana    9.263988e+10
5                              Uttar Pradesh    7.217819e+10
6                             Madhya Pradesh    7.152417e+10
7                                 Tamil Nadu    3.957847e+10
8                                     Odisha    3.853636e+10
9                                      Bihar    3.772257e+10
10                               West Bengal    3.413920e+10
11                                   Gujarat    3.283336e+10
12                                   Haryana    2.717189e+10
13                                     Delhi    2.428368e+10
14                              Chhattisgarh    1.928916e+10
15                                 Jharkhand    1.858292e+10
16                                    Kerala    1.043626e+10
17                                     Assam    1.022154e+10
18                                    Punjab    9.517364e+09
19                               Uttarakhand    7.395509e+09
20                          Himachal Pradesh    3.776042e+09
21                           Jammu & Kashmir    2.701659e+09
22                                       Goa    1.470646e+09
23                         Arunachal Pradesh    1.172571e+09
24                                   Tripura    9.466422e+08
25                                   Manipur    7.414055e+08
26  Dadra and Nagar Haveli and Daman and Diu    7.207643e+08
27                                Chandigarh    7.016118e+08
28                                 Meghalaya    6.841067e+08
29                                Puducherry    6.827597e+08
30                                  Nagaland    6.776493e+08
31                                    Sikkim    4.678160e+08
32                                   Mizoram    3.530931e+08
33                                    Ladakh    3.179896e+08
34                         Andaman & Nicobar    1.610036e+08
35                               Lakshadweep    4.524025e+06

In [314]:
# States with low engagement ratios despite high registrations represent growth opportunities 
# where PhonePe can improve user activity through targeted strategies.

In [315]:
# SQL

query = """
        SELECT
            "State",
            SUM("Registered_users") AS total_registered_users,
            SUM("App_opens") AS total_app_opens,
            SUM("App_opens") * 1.0 / SUM("Registered_users") AS engagement_ratio
        FROM agg_user
        GROUP BY "State"
        ORDER BY engagement_ratio ASC
        LIMIT 10;
        """

low_engagement_states = pd.read_sql_query(query, engine)
low_engagement_states

,State,total_registered_users,total_app_opens,engagement_ratio
0,Lakshadweep,5.625180e+05,4.524025e+06,8.042454
1,Chandigarh,5.869127e+07,7.016118e+08,11.954279
2,Kerala,8.432883e+08,1.043626e+10,12.375676
3,Punjab,7.307240e+08,9.517364e+09,13.024567
4,West Bengal,2.267428e+09,3.413920e+10,15.056359
5,Puducherry,4.458288e+07,6.827597e+08,15.314392
6,Tripura,5.829912e+07,9.466422e+08,16.237675
7,Delhi,1.470469e+09,2.428368e+10,16.514239
8,Gujarat,1.988044e+09,3.283336e+10,16.515404
9,Dadra and Nagar Haveli and Daman and Diu,4.286171e+07,7.207643e+08,16.816042

In [316]:
#6. Insurance Engagement Analysis
#Scenario
# PhonePe aims to analyze insurance transactions across various states and districts to understand the uptake of insurance services among users. 
# This analysis will provide insights into user behavior, market demand, and potential areas for growth in insurance offerings.

In [317]:
agg_ins.head(2)

,State,Year,Quater,Transaction_type,Transaction_count,Transaction_amount
0,Andaman & Nicobar,2020,2,Insurance,6,1360
1,Andaman & Nicobar,2020,3,Insurance,41,15380

In [318]:
# state with highest insurance counts

# SQL

query = """
                SELECT 
                "State",
                SUM("Transaction_count") AS insurance_counts
                FROM agg_ins
                GROUP BY "State"
                ORDER BY insurance_counts DESC;
                
                
                """

st_high_ins = pd.read_sql_query(query, engine)
st_high_ins

                                       State  insurance_counts
0                                  Karnataka         1957404.0
1                                Maharashtra         1815539.0
2                                 Tamil Nadu         1215269.0
3                              Uttar Pradesh         1139153.0
4                                  Telangana          894342.0
5                                West Bengal          839715.0
6                                     Kerala          824235.0
7                             Andhra Pradesh          697769.0
8                                      Delhi          652514.0
9                                  Rajasthan          639684.0
10                                   Haryana          573738.0
11                                   Gujarat          562595.0
12                                     Bihar          536592.0
13                            Madhya Pradesh          487180.0
14                                    Odisha          318769.0
15                                     Assam          262818.0
16                                 Jharkhand          260827.0
17                              Chhattisgarh          189517.0
18                                    Punjab          180011.0
19                               Uttarakhand          124374.0
20                           Jammu & Kashmir           78375.0
21                          Himachal Pradesh           61790.0
22                                       Goa           59872.0
23                                Puducherry           27940.0
24                                   Tripura           25192.0
25                                Chandigarh           22079.0
26  Dadra and Nagar Haveli and Daman and Diu           13792.0
27                         Andaman & Nicobar           12997.0
28                                 Meghalaya           10461.0
29                         Arunachal Pradesh           10214.0
30                                    Sikkim            4896.0
31                                  Nagaland            4745.0
32                                   Manipur            3731.0
33                                   Mizoram            3724.0
34                                    Ladakh            3338.0
35                               Lakshadweep             496.0

In [319]:
# insurance adoption changed over time?

# SQL

query = """
                SELECT 
                "Year","Quater",
                SUM("Transaction_count") AS Num_insurance_adoption
                FROM agg_ins
                GROUP BY "Year","Quater"
                ORDER BY Num_insurance_adoption DESC;
                
                
                """

ins_adop = pd.read_sql_query(query, engine)
ins_adop

    Year  Quater  num_insurance_adoption
0   2024       4               1475429.0
1   2024       1               1273761.0
2   2024       3               1213629.0
3   2023       4               1159039.0
4   2024       2               1105025.0
5   2022       4               1035343.0
6   2023       3               1010192.0
7   2023       1                923147.0
8   2023       2                893809.0
9   2022       3                806454.0
10  2022       2                630744.0
11  2022       1                617575.0
12  2021       4                526319.0
13  2021       3                374860.0
14  2021       2                363988.0
15  2020       3                354284.0
16  2021       1                318115.0
17  2020       4                248626.0
18  2020       2                185348.0

In [320]:
# Districts with low insurance adoption (growth potential)

query = """
        SELECT
            "State",
            "District",
            SUM("Transaction_count") AS Low_insurance_adoption
        FROM map_ins
        GROUP BY "State", "District"
        ORDER BY Low_insurance_adoption ASC
        LIMIT 10;
        """

low_ins_adop = pd.read_sql_query(query, engine)
low_ins_adop

       State                           District  low_insurance_adoption
0    Mizoram                 Hnahthial District                     2.0
1   Nagaland                  Shamator District                     2.0
2   Nagaland                  Tseminyu District                     3.0
3    Mizoram                  Khawzawl District                     3.0
4    Manipur                  Pherzawl District                     3.0
5   Nagaland                    Noklak District                     5.0
6    Mizoram                   Saitual District                     9.0
7  Meghalaya  Eastern West Khasi Hills District                    12.0
8    Manipur                   Kamjong District                    15.0
9    Mizoram                     Siaha District                    21.0

In [321]:
# 8. User Registration Analysis

# Scenario

# PhonePe aims to conduct an analysis of user registration data to identify the top states, 
# districts, and pin codes from which the most users registered during a specific year-quarter combination.
#  This analysis will provide insights into user engagement patterns and highlight potential growth areas.

In [322]:
top_user_list.head()

,State,Year,Quarter,District,Registered_users
0,Andaman & Nicobar,2018,1,South Andaman,5846
1,Andaman & Nicobar,2018,1,North And Middle Andaman,632
2,Andaman & Nicobar,2018,1,Nicobars,262
3,Andaman & Nicobar,2018,2,South Andaman,8143
4,Andaman & Nicobar,2018,2,North And Middle Andaman,911

In [323]:
top_user_list.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8296 entries, 0 to 8295
Data columns (total 5 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   State             8296 non-null   object
 1   Year              8296 non-null   int32
 2   Quarter           8296 non-null   int64
 3   District          8296 non-null   object
 4   Registered_users  8296 non-null   int64
dtypes: int32(1), int64(2), object(2)
memory usage: 291.8+ KB

In [324]:
# highest registered users by state
# SQL

query = """
                SELECT 
                "State",
                SUM("Registered_users") AS reg_user
                FROM top_user_list
                GROUP BY "State"
                ORDER BY reg_user DESC
                LIMIT 10;
                
                """

high_reg_users = pd.read_sql_query(query, engine)
high_reg_users

            State     reg_user
0     Maharashtra  762148724.0
1       Karnataka  512981935.0
2  Andhra Pradesh  461355136.0
3   Uttar Pradesh  384928232.0
4       Telangana  380761595.0
5     West Bengal  372244332.0
6       Rajasthan  328838825.0
7         Gujarat  327003497.0
8           Delhi  307002677.0
9      Tamil Nadu  306477729.0

In [325]:
#districts with highest registered users

query = """
                SELECT
                "State",
                "District",
                SUM("Registered_users") AS reg_user
                FROM top_user_list
                GROUP BY "State", "District"
                ORDER BY reg_user DESC
                LIMIT 10;
                
                """

high_reg_districts = pd.read_sql_query(query, engine)
high_reg_districts

         State                    District     reg_user
0    Karnataka             Bengaluru Urban  303663088.0
1  Maharashtra                        Pune  199346186.0
2  Maharashtra                       Thane  122501643.0
3    Rajasthan                      Jaipur  119739290.0
4  Maharashtra             Mumbai Suburban  119012886.0
5    Telangana                   Hyderabad  101824322.0
6    Telangana                  Rangareddy   90261099.0
7      Gujarat                   Ahmadabad   81767310.0
8      Gujarat                       Surat   77469508.0
9  West Bengal  North Twenty Four Parganas   77396295.0

In [326]:
map_user_list.head()

,State,Year,Quarter,District,Registered_users,App_opens
0,Andaman & Nicobar,2018,1,North And Middle Andaman District,632,0
1,Andaman & Nicobar,2018,1,South Andaman District,5846,0
2,Andaman & Nicobar,2018,1,Nicobars District,262,0
3,Andaman & Nicobar,2018,2,North And Middle Andaman District,911,0
4,Andaman & Nicobar,2018,2,South Andaman District,8143,0

In [327]:
# Top districts by registered users 

query = """
        SELECT
            "State",
            "District",
            SUM("Registered_users") AS total_registered_users
        FROM map_user_list
        WHERE "Year" = '2018'
          AND "Quarter" = 1
        GROUP BY "State", "District"
        ORDER BY total_registered_users DESC
        LIMIT 10;
        """

top_districts_yq = pd.read_sql_query(query, engine)
top_districts_yq

            State                     District  total_registered_users
0       Karnataka     Bengaluru Urban District               1922368.0
1     Maharashtra                Pune District               1211643.0
2       Rajasthan              Jaipur District                900773.0
3     Maharashtra     Mumbai Suburban District                719300.0
4       Telangana           Hyderabad District                655175.0
5       Telangana          Rangareddy District                635175.0
6     Maharashtra               Thane District                631864.0
7         Gujarat           Ahmadabad District                572811.0
8       Telangana  Medchal Malkajgiri District                549429.0
9  Andhra Pradesh       Visakhapatnam District                497187.0